### ISSUE TITLE
Reapplication instructions review

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1005]
@greboun the home page says "All journals that were accepted into DOAJ before March 2014 are now required to reapply. If you have a journal indexed in DOAJ, please log into your Publisher Area and follow the instructions."

It should probably not say that. Or we can keep it till end of April if you want.

It'd probably also be wise to review the rest of the site for reapplication text. If that's difficult for you to do we could try to give you a list of places where "reapplication" is mentioned in a public or publisher-facing page.

**Comment by greboun** [comment]
Hi Emanuil

I was checking that phrase too a short while ago, and think it should be
deleted
Instead I suggest we write
   "All journals that were accepted into DOAJ before March 2014 and failed
to reapply before the deadline of march 31,2016 will be removed from DOAJ
by May 1, 2016. If you did not reapply but you still want your journal  to
remain listed please contact  us at feedback@doaj.org mentioning
"reapplication request"*before april 21* in order to be offered a last
chance to this effect.

If you could offer us handles where to look for reapplication txts that
should be removed that would be great

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by dommitchell** [comment]
I changed this. Closing
