### ISSUE TITLE
Archive off journals that have not reapplied at all

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1006]
1. Find all applications where reapplications status is "pending"
2. For each of those applications, remove the journal identified by "current_journal"
3. Remove each of those applications
4. Output a list of the journals that are being removed

**Comment by richard-jones** [comment]
To be run in the first few days of May, after the reapplication shutdown

**Comment by richard-jones** [comment]
Note: unsubmitted reapplication status is actually "reapplication"

**Comment by richard-jones** [comment]
I've created a PR for this: https://github.com/DOAJ/doaj/pull/1011

Note that as this is a destructive script, we need to run it in a recent clone of live on the test server before deploying it to production.

In terms of the output, this produces a CSV which contains a list of all the journals (with issns, ids, and owner information) which are taken from in_doaj=True to in_doaj=False.  This means that if a journal was already in_doaj=False, it will not appear in the CSV, but the corresponding reapplication record will still be deleted.  This means there will be a difference in number between the number of "Reapplication Pending" records, and the number of rows in the output CSV.

**Comment by emanuil-tolev** [comment]
And we want to do this asap after 30 Apr. We should probably test this next week eh.

**Comment by dommitchell** [comment]
@emanuil-tolev @richard-jones Can you provide us with the exact date and time that you will remove the journals so that we can put a message out to the community?

**Comment by emanuil-tolev** [comment]
That's a good question - I suppose originally this was intended to be 1 May (since the reapps are open 21-30 April) but that's Sunday... and we're at a conference 2-5 May. We could run the removal 2 May if there is an urgent need to do it that I don't see. If there's no urgent need I'd recommend 6th or 9th May? Probably best 9th (Mon).

**Comment by dommitchell** [comment]
9th May works for us, what time please?

**Comment by emanuil-tolev** [comment]
Hmm, how about 11am UK time?

**Comment by dommitchell** [comment]
Yes, that works well.

Just to confirm: the journals will be removed on 9th May at 11am UK / 12am CET.

Thanks!

**Comment by emanuil-tolev** [comment]
Test run succeeded, sorry for the delay - didn't expect it to take quite this long. Running in live.

**Comment by dommitchell** [comment]
When will the home page update?

**Comment by emanuil-tolev** [comment]
It updates about every 30 min. It's not a regular job - it self-checks how out of date it is for each user that requests the homepage. Keep in mind the archival script may take more than 30 min to run. In that case, an interim number of journals (interim = however far the script got on with removing) until another 30 min pass.

All that means the home page should stabilise on the final number of journals no later than 30 min after the archival script has finished running, but it could also be just 5-10 minutes.

Also the /search page is real-time so the # of journals there is going to change as the script goes on.

**Comment by dommitchell** [comment]
Great! One more question:

- we know there are more reapp records pending than journals that will be removed because we have removed a whole load of journals since the reapps were generated. Where criteria (1) and (2) above aren't met:
Find all applications where reapplications status is "pending" - YES
For each of those applications, remove the journal identified by "current_journal" - NO, already removed.

Will we be able to find out how many fit that description?

**Comment by emanuil-tolev** [comment]
> Will we be able to find out how many fit that description?

It might be wise to discuss this at the meeting tomorrow since it is (appears to be?) kind of complicated to describe here - adding it to the agenda now.

**Comment by dommitchell** [comment]
This one has been answered.
