### ISSUE TITLE
Ensure test site stays on between 20/6 and 23/6

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1019]
We are having a training meeting over 4 days and we will be relying on the testdoaj site as a training site. Can you ensure that it remains up and available for these 4 days? 20th June to 23rd June inclusive

**Comment by richard-jones** [comment]
We can try, but in general you should view the test site as something internal to the development projects - often it is running brand-new code (which is automatically deployed from the development branch of the code), and on much smaller resources than the live site, so it can't be considered "stable".  Additionally, outside of development projects it may be suspended, as it is paid for from development budget rather than hosting budget.

If you require a more stable training instance of the DOAJ in general, it would be more appropriate to set that up as a clone of the live instance instead.

**Comment by dommitchell** [comment]
I think we discussed before that we could use the test site as a training area on the understanding that it may not be available at times or show a different version of the DOAJ than the live one. I think we're OK with that. It was really just a note to ask that should you have the urge to take it down during those 4 days, please don't :)

**Comment by richard-jones** [comment]
Ah, ok, no problem - we definitely won't take it down on those days :)

@emanuil-tolev - just leaving this assigned to you to remind ourselves.  After 23rd June we can just close off.

**Comment by dommitchell** [comment]
Done
