### ISSUE TITLE
Question: add us to your address book

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1022]
How would DOAJ facilitate an 'add us to your address book' functionality via the automated emails that go out to users, OR via Mailchimp?

**Comment by dommitchell** [comment]
Dom to find example.

**Comment by dommitchell** [comment]
Here is an example, from an email generated by MailChimp. Seems it generates a VCARD:

Copyright © 2016 Blha Blah Records, All rights reserved.
You have previously been a customer at Northern Star Records.
Our mailing address is:
blah blah blah

Add us to your address book: http://northernstarrecords.us1.list-manage.com/vcard?u=9dbe9e9ac81502824d450a935&id=3720d5501d

**Comment by emanuil-tolev** [comment]
I think we can just have a vcard since the feedback@doaj.org address is known. What do you think of this one? (Not sure how you're seeing/viewing them, I just read them as text files - but it's probably more useful to try it in Outlook or something.)

[doaj.vcf.zip](https://github.com/DOAJ/doaj/files/311654/doaj.vcf.zip)


I just used http://vcardmaker.com/ to make this one.

Then once we have a reasonable one we can just host it at doaj.org and put a link to it (if that's useful to have) in all the emails.

**Comment by dommitchell** [comment]
I think that this is all that is needed. Perfect!

**Comment by richard-jones** [comment]
@ClaraDOAJ - do you want us to add this one to tnm?
