### ISSUE TITLE
Migrate DOAJ Seal facet to Admin view

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1030]
There is currently only a Seal facet in the public view. It would be beneficial to have one in the Admin view.

I am aware that there is a larger piece of work here to upgrade the admin view completely.  I'd like your opinion on doing just the Seal facet for now.

**Comment by richard-jones** [comment]
It's no problem to add the Seal facet from a technical point of view, but there is a slightly wider infrastructure question we should raise just before doing it.

The test server is only just holding up under the weight of the data and the queries, and one of the areas that suffers is the admin area, because the number of facets available.  Infrastructure (especially test) shouldn't really guide us on the functionality that we can have, but if there's an option to remove some facets, it would make that area of the system more stable.

**Comment by dommitchell** [comment]
You can remove the journal title facet and replace it with the Seal. Thanks!

**Comment by richard-jones** [comment]
Also put the seal in the result display

**Comment by Steven-Eardley** [comment]
Are we talking both facetviews, ```admin.journalarticle.facetview.js``` as well as ```admin.journals.facetview.js```? Or would you like to pick a favourite?

Just out of interest, why do we have both?

**Comment by richard-jones** [comment]
Confirmed to just put this under the admin.journals.facetview.js

**Comment by Steven-Eardley** [comment]
@dommitchell this is live now!

**Comment by dommitchell** [comment]
Great!
