### ISSUE TITLE
Add PLoS One to the testdoaj site

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1031]
The journal PLoS One is missing from the DOAJ site. Can you add it so I can see what the Tables of contents look like? Possible?

**Comment by emanuil-tolev** [comment]
It's just not "in doaj", seems to be there in the admin area: http://testdoaj.cottagelabs.com/admin/journals?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22plos%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

**Comment by dommitchell** [comment]
Great! But bad gateway: http://testdoaj.cottagelabs.com/admin/journal/2fdf1470373343b7bd4f825179c685f5/activate

**Comment by emanuil-tolev** [comment]
Ah ... it's got loads and loads of articles associated, so that endpoint is taking too long.

**Comment by dommitchell** [comment]
Hi @emanuil-tolev it looks like we missed one: https://europepmc.org/search?query=1555-5887

**Comment by emanuil-tolev** [comment]
If you're talking about PLOS data on live, yes, I noted in an email that we are missing one journal - the PLOS clinical trials journal. There isn't even a record for it. I think you'd need an application and approval for it first?

(Just for clarity, this specific issue is about making a modification to PLOS ONE journal record on the test site since hitting Put in DOAJ takes too long (since it's a huge journal). We've not solved this yet.)

**Comment by emanuil-tolev** [comment]
> I think you'd need an application and approval for it first?

Once that is done and the journal record in "in DOAJ" and associated with the PLOS account, the harvester should I think pick it up automatically next morning.

**Comment by dommitchell** [comment]
Ah yes! Thanks. (Sorry for polluting this issue!)

**Comment by dommitchell** [comment]
Closing this for now as we don't need PLOS in the test site.
