### ISSUE TITLE
Automated emails are encoding URLs in the body of the text

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1052]
For example:

I want to harvest articles on Library and Information Science using PKP Harvester. I have noticed that base url is http://email.doaj.org/c/eJwtjTsOwyAQBU8DndHyW5yCIk3uscASk1gCIe6v2FKkV0wxo1eitbok2aIBjRAAtXfBotI7IijvDYBwUDp9Nhpj0_KITldwHPgBlDJjrq4Wtsknosx1D_KMx1pD2Kcwr2t3rPp8X9ipKZqr5ZOVnLEyl0T5-3-4pR9ClSrq However, I am unable to workout how to download articles from selected journals (by subject).

**Comment by emanuil-tolev** [comment]
Sorry, what?

Which automated email are we talking about? And what does information in a DOAJ-originating email have to do with harvesting articles via OAI (or in any other way)?

**Comment by dommitchell** [comment]
Sorry for not being clear. Forget the OAI thing.

All emails coming to feedback@doaj.org ar ehaving any email encoded. Here is another example: 

1. The new home page for the journal is http://email.doaj.org/c/eJwtzDEOwyAMQNHTwBaEITVhYMjSexjsNGkrEQHt-Zuh0p_e8Dl5D5z1kZwFtAGCXXxw0bjoozMBL1Gz5UrPic5zAr0ngoC4OEHACLBxYQJGtBI8zlJu-p32MU7lV-XuV02-Rx9Us4xuPmSk65Y2Ec5UXv-5qe3xAyroKII

We don't need URLs in INCOMING emails encoded but only OUTGOING, right?

**Comment by emanuil-tolev** [comment]
Oh gosh, are you saying emails that are coming into the DOAJ feedback@ inbox, written manually by members of the public (or the research community) are having URLs encoded?

That should certainly not happen.

**Comment by dommitchell** [comment]
The ones you emailed aren't encoding.

But it's any URL submitted via the contact form.

![contact](https://cloud.githubusercontent.com/assets/5955396/16953671/375149c0-4dce-11e6-864c-0c170dcc2ab7.jpg)
![contact2](https://cloud.githubusercontent.com/assets/5955396/16953689/51e6389a-4dce-11e6-8447-73b91f3d9bd4.jpg)

**Comment by emanuil-tolev** [comment]
> But it's any URL submitted via the contact form.

Ah. But those are emails automatically sent by the DOAJ system...

**Comment by emanuil-tolev** [comment]
OK, we can turn off click tracking (and therefore URL encoding) for certain emails of our choosing. We should do this for emails sent via contact form. I'll have to dig a bit to get an estimate of how long, it mostly depends on the flexibility of the email sending utility function we have, and the library it uses underneath. We need to include a new header when sending emails to Mailgun, our current email ISP.

**Comment by emanuil-tolev** [comment]
Thought it'd be best to add a simple recap of this issue so far.

It is not a bug, it's the system sending automatic emails (with click tracking and opens tracking turned on).

This behaviour is a bit unintuitive since it relates to emails destined for DOAJ staff. This is despite the emails being "outbound" from a purely technical perspective - the system is sending email to somebody, and doesn't distinguish between feedback@doaj.org and other targets.

I believe it would be best if clicks and opens on DOAJ emails *are not counted* in mailgun.com statistics if they come from DOAJ staff manning feedback@doaj.org . It's for DOAJ's benefit to know how engaging its campaigns are, thus best not to muddy the numeric waters with our own use.

This can be achieved by disabling clicks and opens tracking for all emails to be sent out by the DOAJ contact form. Technical reference: https://documentation.mailgun.com/api-sending.html#sending . This will take a bit of development to do. I will confirm how long it will take so that @dommitchell can confirm its priority and whether to go ahead or not.
