### ISSUE TITLE
OAI protocol question

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1124]
Hello @richard-jones 

I have this question from a user that I am not able to answer:

**In 2014 I used the listidentifier verb to grab some article metadata via the oai protocol. Now I tried to update my article database by using the same verb with a "from" and "until" datestamp search. It seems like there is nothing available before 2016-06-24.**
Could you please support?

Many thanks!

**Comment by richard-jones** [comment]
Hi @ClaraDOAJ 

The DOAJ OAI-PMH interface is not intended as a search in the way the user is approaching it, instead it is a change feed ordered by last_updated date.  So that noting is available when they search just tells us that all items have been updated since 2016-06-24.  If the user is looking for specific records, we have an API they can use to query, if that would be more appropriate?

The appropriate way to use PMH is to start querying from when you last left off, and iterate forwards to the present, which ensures you are up to date with the state of DOAJ.  It's not intended as a tracker for all changes of state in DOAJ for all time, from which the caller can cherry-pick.

Note, we do have a tracker for all changes of state in DOAJ records - the history system. But it is enormous and stored zipped in archival storage, and exposing it via PMH would be virtually impossible.

Hope that helps

Cheers,

Richard

**Comment by emanuil-tolev** [comment]
Can they use the API somehow? Would need to know what they're trying to do, maybe they don't really need to search by timestamp.

**Comment by ClaraDOAJ** [comment]
Will check and get back to you :)
