### ISSUE TITLE
Database query:Journals with seal latest metadata

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1167]
Dear CL
It is a requirement that the journals with the seal keep uploading metadata. In order to monitor this, we would like to request a query to our database that shows the following info in columns:

Title
issn
publisher
date of metadata upload
name of journal's contact person	
contact person's email

If the date of the last metadata upload is empty or very old we will know we need to enquire about this. 

Is this possible? Is it also possible to run this query regularly (once every couple of months/three months)?

Many thanks,
Clara

**Comment by emanuil-tolev** [comment]
If this is going to be an ongoing editorial need should we not consider just adding an appropriate filter or a new page to the Managing Editor interface?

It'll be more efficient + much cheaper mid-to-long-term to give Managing Editors the ability to see this at a glance rather than keep running queries with custom information being output into a CSV.

**Comment by emanuil-tolev** [comment]
On implementation @DOAJ/doaj-developers I have one discussion point:

We could write a query that ties a particular journal to the "upload" document type and checks the latest metadata upload.

Or, we could update the journal with a `latest_article_metadata_upload_time`.

Since we're using an index, which by nature works quickly by duplicating information, I'd be inclined to go for adding the new field to the metadata upload background task that we're writing in the bulk edit + background jobs project. Migration to add it retrospectively should be reasonably straightforward as well. Once in place this strikes me as a simper solution that would be easier to surface on search interfaces and the like, including a new facet on the Journals tab for Managing Editors to show "journals that have not recently uploaded metadata".

There is something about the requirements as well:

There is the issue of comprehensiveness of updates - as it is it would be possible to keep updating 1 article record and never submit any new records, and this would be enough to satisfy the system that the journal is well-behaved. There isn't really any way around that, unless we make this more complicated than "last metadata upload date". I'd suggest that we don't make things more complex, do it the simple way and see if that works well.

**Comment by Steven-Eardley** [comment]
I agree with an ```article_metadata_last_updated``` timestamp in journals. Then we can facet over a threshold (if our version of facetview has those features) and display it in the admin facetveiw.

**Comment by ClaraDOAJ** [comment]
Whatever is best for the mid-to-long-term usage!



Clara Armengou
DOAJ - Community Manager

**Comment by ClaraDOAJ** [comment]
We will need to know if the journal has the seal too. So these would be the fields we would need:
Title
issn
publisher
Seal?
date of metadata upload
name of journal's contact person
contact person's email

**Comment by richard-jones** [comment]
TODO:

* Update the article ingest process to add a date stamp to the journal
* Add a range facet to the Journals facetview over that date.  Periods 0-3 months, 3-6 months, 6+ months
