### ISSUE TITLE
xml not uploading

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1173]
Copying user email here

I have a great problem. The xsd for the journals have change and I have try to upload my xml of the journal CEM 2015 but you never accepted despite the validator tell me my xml is well formed. But when I validate my xml against your xsd  it gives always errors sometimes as if it was an html. I try a lot different ways and none is accepted. So I have checked the xsd validity and the message of error were huge.
I don’t know what to do. Can you or other person help me. Anyway I send attach my xml.
So many thanks
Kind regards

and xml

[xml 2015.txt](https://github.com/DOAJ/doaj/files/707733/xml.2015.txt)

**Comment by Steven-Eardley** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:iso_639-2b="http://www.doaj.org/schemas/iso_639-2b/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import schemaLocation="http://www.doaj.org/static/doaj/iso_639-2b.xsd" namespace="http://www.doaj.org/schemas/iso_639-2b/1.0">
<records xsi:noNamespaceSchemaLocation="http://www.doaj.org/schemas/doajArticles.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

We are getting ```http``` to ```https``` redirects when validating the schema. We should consider making these available again over HTTP so older links work.

Changing ```http://``` to ```https://``` in all doaj URLs in the snippet above shows the actual validation errors that the xsd is throwing.

**Comment by emanuil-tolev** [comment]
They are supposed to be served over plain http, but the www. might complicate things since you'll get redirected to the non-www version. We should check plain HTTP with and without www in any case.

The doaj gateway nginx config under deploy/ has the details.

Why are their files incorrect though? Our XML documentation page has the right info (I hope?). Maybe they're copying from old files, pre-2013.

**Comment by Steven-Eardley** [comment]
I did verify our docs, they show the right link the the schema. This does look like an old file.

**Comment by emanuil-tolev** [comment]
In a way, we do expect those links to work since we put exceptions in the nginx https config for them. But also, if the solution is for the user to fix the file, maybe that's enough for now. Could you write something for Clara to send back to request they update their uploads, if you think that's a sensible approach?

**Comment by Steven-Eardley** [comment]
I shall. In addition, should we include a full example of a upload template that validates against our xsd? The publisher info page points you to the validator and the xsd separately, and the example we provide on the /features page doesn't contain schema information, although it is valid.

In fact, shouldn't these be in the same place anyway? only publishers can upload article XML.

**Comment by emanuil-tolev** [comment]
On 17 January 2017 at 13:10, Steven Eardley <notifications@github.com>
wrote:

> I shall. In addition, should we include a full example of a upload
> template that validates against our xsd?
>
Yeah, we likely should if we don't have this. I thought /features had it
since it's a line by line breakdown, but we should provide a "download this
as an example" or something in addition to the line by line breakdown. In
fact the line by line should likely include these lines and point out the
links should be https, non-www.

> The publisher info page points you to the validator and the xsd
> separately, and the example we provide on the /features page doesn't
> contain schema information, although it is valid.
>
> In fact, shouldn't these be in the same place anyway? only publishers can
> upload article XML.
>
That I'm not sure about, that's how it was requested a long while back.
Maybe Dom felt it was too much info for the publishers page, which already
has a lot of info?

**Comment by Steven-Eardley** [comment]
I verified the docs but not the [xsd itself](https://doaj.org/static/doaj/doajArticles.xsd). It still has some outdated information:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs ="http://www.w3.org/2001/XMLSchema"
  xmlns:iso_639-2b="http://www.doaj.org/schemas/iso_639-2b/1.0">

 <xs:import namespace="http://www.doaj.org/schemas/iso_639-2b/1.0" 
       schemaLocation="http://www.doaj.org/static/doaj/iso_639-2b.xsd">
...
```

**Comment by Steven-Eardley** [comment]
@ClaraDOAJ: the main issue for the user is that their link to the DOAJ schema is experiencing a redirect to HTTPS, so is not validating properly. Basically, if they replace ```http://www.doaj.org``` in their links with ```https://doaj.org```, the real validation errors will appear (and there are some in that document).

@emanuil-tolev: You've already agreed to a couple of these, but this is what I reckon needs improvement:
- [ ] Ensure we can reach the XSD via common permutations of HTTP(S) / www etc.
- [ ] In the xsd file, the namespaces are un-representative of the DOAJ (not that it matters for namespaces) - update these to ```https://doaj.org```.
- [ ] The xsd file that's embedded line-by-line on /features is outdated. We should either update the static text, or embed the actual XSD there.
- [ ] the example upload on /features - the help people with validation, the schema could be included in the example, as below:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<records xsi:noNamespaceSchemaLocation="https://doaj.org/schemas/doajArticles.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <record>
    <language>eng</language>
    <publisher>Popular Chemistry</publisher>
    <journalTitle>Botanical Magazine</journalTitle>
    <issn>17497221</issn>
    <eissn>17497234</eissn>
    <publicationDate>2002-09-30</publicationDate>
    <volume>98</volume>
    <issue>2</issue>
    <startPage>1234</startPage>
    <endPage>1235</endPage>
    <doi>1234567</doi>
    <publisherRecordId>12345</publisherRecordId>
    <documentType>article</documentType>
    <title language="eng">Roses and Lilies</title>
    
    <authors>
      <author>
        <name>Fritz Haber </name>
        <email>fritz.haber@some.university.org</email>
        <affiliationId>1</affiliationId>
        <affiliationId>2</affiliationId>
        <affiliationId>3</affiliationId>
      </author>
    </authors>
    <affiliationsList>
      <affiliationName affiliationId="1">
        University of A     
      </affiliationName>
      <affiliationName affiliationId="2">
        Universitaty of B
      </affiliationName> 
      <affiliationName affiliationId="3">
        University of C
      </affiliationName>
    </affiliationsList>
    <abstract language="eng">
      The catalytic formation of ammonia from hydrogen
      and atmospheric nitrogen under conditions of high
      temperature and high pressure.
    </abstract>
    <fullTextUrl format="pdf">
      http://www.science.org/articles/HaberBosch.pdf
    </fullTextUrl>
    <keywords language="eng">    
      <keyword>garden</keyword>
      <keyword>rose</keyword>
    </keywords>
  </record>
</records>
```

**Comment by richard-jones** [comment]
Just throwing a bit of information in here as it occurs to me.  I believe one of the issues is that XSD expressly does not support https.  That is, even if the schema is available over https, the validators will still not validate.  So we just have to be sure that when someone hits the http url, they never get redirected to an https one.

**Comment by richard-jones** [comment]
Ok, a couple of odd things going on here:

The XML they sent starts like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:iso_639-2b="http://www.doaj.org/schemas/iso_639-2b/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import schemaLocation="http://www.doaj.org/static/doaj/iso_639-2b.xsd" namespace="http://www.doaj.org/schemas/iso_639-2b/1.0">
<records xsi:noNamespaceSchemaLocation="http://www.doaj.org/schemas/doajArticles.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

This xs:schema and xs:import elements shouldn't be there, and when this is validated against the DOAJ schema, the new article upload error interface gives us:

    Failed to upload file: Unable to validate document with any available ingesters; Validation messages from schema 'doaj': 2:0:ERROR:SCHEMASV:SCHEMAV_CVC_ELT_1: Element '{http://www.w3.org/2001/XMLSchema}schema': No matching global declaration available for the validation root.

If you remove those tags (and the corresponding close tags at the end of the xml), and try the file again, you get this message:

    Failed to upload file: Unable to validate document with any available ingesters; Validation messages from schema 'doaj': 21:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'affiliationList': This element is not expected. Expected is one of ( affiliationsList, abstract, fullTextUrl ).

So, there's an error in their XML, where they have used "affiliationList" rather than "affiliationsList".


Regarding the comments above about the XSD and HTTPs, I don't think there's anything wrong with the xsd or how we're serving it - certainly it seems to be validating fine at our end.

**Comment by ClaraDOAJ** [comment]
They have managed to upload the file...they just did not tell me.

Thanks! closing now...
