### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1187]
Dear CL

This journal's "Nauka ta Progres Transportu" site is not accessible via our directory. If I paste the url on the browser it does display but not when clicking from DOAJ. I checked the database and the url is the same.

The error is this one:

![image](https://cloud.githubusercontent.com/assets/22593616/22245695/99fe345a-e231-11e6-9730-c56ab936910c.png)

And the url

http://stp.diit.edu.ua/

Could you help me please?

Thanks!

**Comment by richard-jones** [comment]
for reference: it's the ToC page that's not rendering: https://doaj.org/toc/2307-6666

**Comment by richard-jones** [comment]
@ClaraDOAJ - are you having problems accessing http://stp.diit.edu.ua/ ?  I found this slow, but it did resolve eventually.  That's their domain, though, so we have no control over it.

**Comment by ClaraDOAJ** [comment]
@richard-jones yes, it was slow but it did resolve. 

So, shall I let them know it is a problem in their domain?

**Comment by richard-jones** [comment]
There's definitely a problem on our side, as https://doaj.org/toc/2307-6666 should resolve to the journal page in DOAJ.  Their url is just slow to resolve, which could be for any number of reasons, and I don't think there's anything wrong with it.

**Comment by emanuil-tolev** [comment]
The error we issue might be somewhat misleading. What it is used for is (among other things) when the website can't decide which journal to show, because multiple records exist with the ISSN in the URL.

When you open that URL, all the DOAJ app knows is that you want the journal with p-ISSN or e-ISSN 2307-6666. However, if there are two or more journal records all marked **In DOAJ**, then what should it do? Currently, it shows this error.

I would suggest:

- we show an improved error. Something else in the 4xx or 5xx range. Bad Request implies the browser or user did something wrong.

- Prevent this from happening in the first place by improving the validation on the ISSN fields, so you can't put a journal into DOAJ that has a duplicate current ISSN. You also won't be able to edit an existing journal that is in DOAJ and change its ISSNs to ones that already belong to another journal in DOAJ.

    This won't affect or take note of journals taken out of DOAJ by a managing editor.

* * *

If you want to fix it right now, see https://doaj.org/admin/journals?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%222307%5C%5C-6666%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D (admin journal search with this *exact* ISSN). The problem will be removed once this search returns only one record.

I suspect the two records refer to the same journal, so I expect one of these records might need to be removed after its metadata and articles are reassigned to the other one. Best case - one of them has all the metadata and articles, the other one is nearly empty, so you just delete the empty one. Otherwise it's trickier if data is spread across the two records.

**Comment by ClaraDOAJ** [comment]
This is solved. Our editor had added two records by mistake and now has removed one.

**Comment by ClaraDOAJ** [comment]
Many thanks all for your swift response!
