### ISSUE TITLE
articles not showing

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1206]
Hi CL

We keep getting this sort of query

Vértices
https://doaj.org/toc/1809-2667

Our journal has been accepted into DOAJ. We tried to upload metadata via "Upload Article XML" and "Enter Article Metadata" but we failed.
In our "Publisher Area" we can see the message "successfully processed" (89 articles imported (75 new, 14 updated), but we are not able to see the articles in the "tables of contents" page. We request some help to solve this problem.

Best regards,

Essentia Ed

**Comment by richard-jones** [comment]
Hm, this is an interesting one.  I've had a look for this ISSN in the admin area, and the articles are there, but they are marked as in_doaj=False.  

https://doaj.org/admin/admin_site_search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22%5C%221809%5C%5C-2667%5C%22%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

I think this is because there are 2 versions of this journal, one in doaj the other not:

https://doaj.org/admin/admin_site_search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22journal%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22%5C%221809%5C%5C-2667%5C%22%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

I think a quick fix for this in the immediate term would be to withdraw and then reinstate the current version of the journal, but I suspect we should also look a bit more carefully at the article ingest code and see why it is preferring to attach the articles to the in_doaj=False journal.

**Comment by ClaraDOAJ** [comment]
What do you think I should do, then?

**Comment by richard-jones** [comment]
For the moment I'd just withdraw and then reinstate the current journal - that should fix the issue in the immediate term.

In the mean time, we'll have a think about the article ingest code and look at why it is preferring the older journal to the newer journal to pull the article in_doaj status from.

On a related note, for the background jobs project we looked at exactly this issue for another piece of code, so I expect a longer term solution would be easiest once we've rolled out that project.

**Comment by richard-jones** [comment]
After doing the withdraw and reinstate, if it's possible to delete the old withdrawn journal, I'd also do that.  That will mean all new articles will be attached to the correct one going forward.

**Comment by richard-jones** [comment]
@ClaraDOAJ just assigning this to you to confirm whether the fix above worked or not?

**Comment by ClaraDOAJ** [comment]
I have just done this and it worked! Magic!

Closing issue now.
