### ISSUE TITLE
Different date information in admin and editor screens

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1252]
Hello,

In the Admin screen, I can see Last Updated dates of November and December, but in an editor's screen, and in the Editor view, the oldest Last Updated dates are 28 February 2017, and just a few seconds apart. This suggests some kind of automated update.

It is not helpful for the information in the system to differ between screens. Do you know what happened?

Thanks

Clara

**Comment by emanuil-tolev** [comment]
We've always had last updated for all updates  (either a manual update or a batch/system job modified the record). There was a request a while back to add a "last time this was updated by a person",because we sometimes make changes to the records en-masse, e. g. to add a new field. 

Perhaps this is a user experience issue with which of those dates we display. While checking this, we should also ensure the choices in the sort records menu are consistent with the record display - ensure you're definitely sorting by what you're seeing.

**Comment by ClaraDOAJ** [comment]
hi Emanuil

No, they are  looking at exactly the same data in different screens - Admin and Editor - In progress records, Middle East & Persian Gulf group, sorted by Last Updated date in ascending order (oldest first).

See screenshots attached.

Thanks!
![screen shot 2017-03-27 at 07 29 21](https://cloud.githubusercontent.com/assets/22593616/24343889/15cc4d98-12c9-11e7-9880-ef31f0b24c91.png)
![screen shot 2017-03-27 at 07 27 42](https://cloud.githubusercontent.com/assets/22593616/24343890/15ccbb02-12c9-11e7-8330-4781fbbb9d18.png)

**Comment by Steven-Eardley** [comment]
Could be related to the 'human last updated' field added in https://github.com/DOAJ/doaj/issues/811 - and the fact that facetviews aren't always kept equivalent across the board.

**Comment by richard-jones** [comment]
Yes, that's all this is - the Admin screen is displaying the data from "last_manual_update" and the Editor screen is displaying the data from "last_update".  Probably we should just do a quick review of all the facetviews (there are quite a few) to make sure they are using the fields consistently, and then update those that are out of line.

**Comment by ClaraDOAJ** [comment]
I agree. Admin view and Editor view should be the same. Please let me know
when this is solved.

Many many thanks! :)

Clara Armengou
Community Manager

*Directory of Open Access Journals*
*www.doaj.org <http://www.doaj.org> *

**Comment by Steven-Eardley** [comment]
In PR #1322 I've given editors and associate editors the same date sorting and results view as admins do for applications and journals. 

Only the Administrative site search (journals and articles) remains using the old ```last_updated``` date, because that searches over articles too, which don't have the ```last_manual_update``` field.

Saving the remainder of the facetview review for the refactoring work.

**Comment by Steven-Eardley** [comment]
Released to live now.

**Comment by ClaraDOAJ** [comment]
Thanks!!
