### ISSUE TITLE
xml not valid

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1258]
Email from user 15965996

I have prepared xml files for our published articles which are available at https://www.tjpr.org/xml/metadatalist.php. For each of the files, I carried out xml validation using the XML INPUT at http://www.freeformatter.com/xml-validator-xsd.html and all the files were accepted. However, I observed you did not have access to the files and when I tried to upload each of the files, only schemas appear to be acceptable. Can you advise

[tjpr_xmldata (1).zip](https://github.com/DOAJ/doaj/files/885741/tjpr_xmldata.1.zip)

**Comment by emanuil-tolev** [comment]
One quick note - best to not post email addresses here since the github repository is public. The username (e.g. 15965996 in this case) is usually best, though it does mean an extra trip to the DOAJ users list: put in the email, get the username.

**Comment by ClaraDOAJ** [comment]
Ah, true. Thanks for advising!

**Comment by ClaraDOAJ** [comment]
@emanuil-tolev I just checked this one and it is not solved. Could you have a look at the xml, please?

Many thanks!

**Comment by emanuil-tolev** [comment]
There are several uploads related to this account.

The oldest one, possibly relevant to the original user's message, is actually an attempt to ask DOAJ to download the files from https://www.tjpr.org/xml/metadatalist.php and process them. We can't do that, we only take links directly to each file. I say this may be relevant because the user says

> I observed you did not have access to the files and when I tried to upload each of the files

We can't not have access if they're being uploaded directly, so I assume they mean remote upload by URL when they say "did not have access.

* * *

On to the XML. I haven't tried all of them, but the first and the last files in the archive do indeed fail. We provide a lot more information nowadays (since those uploads were last attempted) so now it shows the exact issue. The issue is simply "using HTML entities in an XML file", which is not allowed.

The problem is the use of character entities not defined in the schema / DTD. There are only 5 character entities defined in XML by default: http://xml.silmaril.ie/specials.html . The schemas referred to by the XML file should define anything else, like `&reg;` and `&beta;`. The XML files I looked at do not refer to any other schemas.

Processing always happens in the context of the DOAJ schema (in addition to anything else the files may refer to). The DOAJ schema does not define any extra character entities.

So there's nowhere for the character entity definitions to come from. We don't support HTML entities in XML files, and neither does any other XML parser (by default). They could try:

1. Providing an XML file which refers to a publicly accessible DTD or XSD, which defines the HTML char entities like `&reg;` and `&beta;`. I'm afraid we don't have an example handy in the DOAJ test fixtures, but I think something like a simple single line at the very top of the file would do:

    ```xml
    <!DOCTYPE html SYSTEM "http://mysite.com/html.dtd">
    ```

    If they decide to go this way, there are some tricks line inline DTDs and using predefined schemas (like the XHTML one) which may shorten the work considerably: https://stackoverflow.com/questions/6508860/how-do-i-define-html-entity-references-inside-a-valid-xml-document .

2. Replace the character entities with text e.g. `&reg;` => `(r)`. Replace or strip all HTML entities this way. Remember only http://xml.silmaril.ie/specials.html are allowed.
