### ISSUE TITLE
Question: if a journal applies again after being deleted do they have to upload all their metadata again?

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1284]
We would like to ask you one question.
We have just reapplied our journal in DOAJ six months after we were rejected in this past October.
The question is: In case of being readmitted, should we have to enter metadata for all the articles of our journal again? Or will DOAJ automatically recover all the data we have already entered in the last years?
We appreciate your willingness and look forward to receiving your response.

**Comment by emanuil-tolev** [comment]
That depends on how the journal was "deleted" as per the issue title. That's decided by the DOAJ editorial team.

Ifi t was actually deleted: they would have to reupload.
If it was withdrawn from DOAJ (which is the usual recommended action): they would not have to reupload.

Maybe they thought they were "deleted" since they no longer appear in the public search results?

If the DOAJ Editors have only withdrawn the journal record, then it is of course possible to reinstate it along with any articles.

**Comment by ClaraDOAJ** [comment]
In this case the journal record is still in our records but not in the public interface. 

We will do so if/when the journal is reaccepted.

Many thanks!
