### ISSUE TITLE
Write global article duplication script for on-demand execution

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1296]
We occasionally want to look at the state of the DOAJ to ensure that no article duplicates have emerged in the system.  We could do with a script which does the following:

* For each article does a global check to see if there are any other articles which are "duplicate"
* Outputs each "set" of duplicate articles, along with the criteria for which they were determined duplicate
* Further identifies articles which are duplicate within a single user's account
* Identifies articles which appear in more than one "set" - that is, they may be duplicate with one set of articles by DOI, and duplicate with a different set by URL, etc

This may require enhancements to the article duplication check function to return more information about the nature of the check.

**Comment by dommitchell** [comment]
Where did we get with this one? What was the outcome?

**Comment by Steven-Eardley** [comment]
This is still on my to-do list. I started this a while ago and shall prioritise finishing it off and reporting back.

**Comment by ClaraDOAJ** [comment]
Hello Steve,

I am attaching an example of this again. Unfortunately you will not be able to access the duplication now as I have deleted one of the copies.

![image](https://user-images.githubusercontent.com/22593616/32104553-3eddab00-bb25-11e7-9cbe-7e3ecbfba6ee.png)

**Comment by dommitchell** [comment]
What's the status of this one @Steven-Eardley ?

**Comment by Steven-Eardley** [comment]
The script is currently running on the test server (report only), and I believe it's producing good results. Since the data is shared, we can see some of the duplicates in the live system:

Correct duplicate match:
```
e3d97accbd084418b354909f366aae37
	6 DOI duplicates: 444bf649032547b2b2eae62c22538cb2, 4b5f13de046a48cfbaad620f543fb2c9, 6807a1d8c55c4c3ab953e41cfd2adefc, 72d55082bd5e47fa859369e91c22311d, a43e1ef27fc547e4904d3711ef20d4af, e2102ab58a2749ab8feef9d8a62375e8
	6 fulltext duplicates: 444bf649032547b2b2eae62c22538cb2, 4b5f13de046a48cfbaad620f543fb2c9, 6807a1d8c55c4c3ab953e41cfd2adefc, 72d55082bd5e47fa859369e91c22311d, a43e1ef27fc547e4904d3711ef20d4af, e2102ab58a2749ab8feef9d8a62375e8
```
https://doaj.org/admin/admin_site_search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22444bf649032547b2b2eae62c22538cb2%20OR%204b5f13de046a48cfbaad620f543fb2c9%20OR%206807a1d8c55c4c3ab953e41cfd2adefc%20OR%2072d55082bd5e47fa859369e91c22311d%20OR%20a43e1ef27fc547e4904d3711ef20d4af%20OR%20e2102ab58a2749ab8feef9d8a62375e8%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

And a false-positive (multiple distinct articles share the same full text URL):
```
e58dfc954b9f4d85ba385192d997faf2
	10 fulltext duplicates: 02a10bf120d947d0b0f0f7223ebb611f, 14643ac7416d4acbb57d178480c5e8cf, 23b97ce5b3c84cdd8ed0fc243b1bc458, 4279722812d141d2845b88fb26fa6e98, 468b28049c1b4fadb760c501171e4f45, 4749210c5bd74770b50c7a6c44b8b6c7, 4763f069a4804ad080f62aec542208ab, 482d30a4a4044c6e9128133a84bf4321, 4d00bff01e8b405ca34dd73c3f48f0c5, 4e5c089474984803bb921d92f0f85dc9
```
https://doaj.org/admin/admin_site_search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%2202a10bf120d947d0b0f0f7223ebb611f%20OR%2014643ac7416d4acbb57d178480c5e8cf%20OR%2023b97ce5b3c84cdd8ed0fc243b1bc458%20OR%204279722812d141d2845b88fb26fa6e98%20OR%20468b28049c1b4fadb760c501171e4f45%20OR%204749210c5bd74770b50c7a6c44b8b6c7%20OR%204763f069a4804ad080f62aec542208ab%20OR%20482d30a4a4044c6e9128133a84bf4321%20OR%204d00bff01e8b405ca34dd73c3f48f0c5%20OR%204e5c089474984803bb921d92f0f85dc9%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

**Comment by Steven-Eardley** [comment]
So at the moment I think there should be some further changes - if we are going to run this script with deletion, both criteria should be met. At the moment it requires either-or, and that would be more likely to be greedy and delete more than we want / expect.

That said, I'd like to clarify
* Fulltext or DOI duplicates on their own are also a sign of rubbish data, should we be flagging or deleting these too?

**Comment by Steven-Eardley** [comment]
Answer - yes, these are rubbish data so we don't want to introduce these in the system. Leave the duplicate detection to be OR.

The delete script, though, should be more cautious. Use an AND to only delete articles that fulfil both criteria.

**Comment by Steven-Eardley** [comment]
This is ready for testing again
- [ ] Test server
- [ ] Production server
