### ISSUE TITLE
2148-4155 duplicate - both copies not available

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1299]
Hello CL

This is a weird one. It all started with an email asking for help on xml upload. However, I realised this journal is duplicate and NOT available. Could you help me, please?

Original email>

We have two issues which may or may not be connected. Let me elaborate:
Issue 1st- Our attempts to upload our article metadata XML from OJS have failed with the following errors:
"All articles in file failed to import (what does this mean?)
The following ISSNs in your article metadata are owned by you and another user. This is a problem at our end, please contact us with the details:2148-4155
The following ISSNs in your article metadata are owned by another user, you cannot associate articles with them. If you believe you should own these ISSNs, please contact us with the details: 2148-4147"

We believe we should own these ISSN information.

Issue 2nd: The following link, which is the link to our Journal's profile (page) on DOAJ are not working: https://doaj.org/toc/2148-4155

We would appreciate your help in advance for solving these issues,

**Comment by richard-jones** [comment]
Hi @ClaraDOAJ 

On the first issue, if you look at the first ISSN in the Journal admin area:

https://doaj.org/admin/journals?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22%5C%222148%5C%5C-4155%5C%22%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

you can see that there are two journals in doaj with that issn, and they are owned by different user accounts.  One of them also has the other ISSN 2148-4147 attached to it.  So that's the reason for those error messages.  You need to resolve the correct ownership of one or other or both of those journals.


The second issue, I have no idea - it is giving me a "Bad Request" error, which is extremely weird.  @Steven-Eardley @emanuil-tolev - can you see if any error is being recorded on the server for me?

**Comment by richard-jones** [comment]
Oh actually, no it's not weird, the error is just uninformative.  It's for the same reason that they can't upload - the ownership of the ISSN is confused, so the ToC doesn't know what to render at that URL.  If you sort the ISSNs the ToC will follow.

**Comment by ClaraDOAJ** [comment]
I will sort the issns now. Thanks, guys!

**Comment by ClaraDOAJ** [comment]
sorted! Many thanks!
