### ISSUE TITLE
2 names for South Korea

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1325]
A list of journals from South Korea; however, already there is a "Korea, Republic of" as country name. 

We should only be able to write ISO country names. Could you have a look at this?

Many thanks
![image](https://user-images.githubusercontent.com/22593616/27689250-f0851e7a-5cdd-11e7-8b7d-f08efad0620f.png)

**Comment by Steven-Eardley** [comment]
The journals with the incorrect 'South Korea' (24 of them including those out of DOAJ)  were all added to the DOAJ between 2003-12-10 and 2013-07-04, so this is a legacy data quality issue. These can either be edited manually via the form, or scripted. I'd recommend the former since the number is relatively low.

**Comment by ClaraDOAJ** [comment]
Thanks, I have made the change on the ones that are active.

Closing ticket now.
