### ISSUE TITLE
Bulk edit- comments 

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1329]
- It would be very easy to make a mistake and withdraw every journal from DOAJ. Perhaps there should be some upper limit on the number of records that can be changed?
- Would be good that  we could allocate journals to 1 specific person or editorial group
- Search by date

**Comment by Steven-Eardley** [comment]
> It would be very easy to make a mistake and withdraw every journal from DOAJ. Perhaps there should be some upper limit on the number of records that can be changed?

That's the reason for our confirmation step, we hope users will read it!
```This operation will affect X journals.```

However, if you want a limit, what do you think is sensible? A number, e.g. 1000? or 10% of the total number of that type? 

One issue is that there's a couple of orders of magnitude more articles than journals, so doing a bulk action on, say, Elsevier's articles would require changes to 93,000 articles which is more than the number of journals we have.

**Comment by ClaraDOAJ** [comment]
To be honest, I think the warning message is enough.

**Comment by richard-jones** [comment]
If the message is sufficient, I will close this issue, and have opened two other issues so that we can track the other requirements:

* #1338 - extend the editor group selection to also allow editor selection, which can be done under tnm
* #1339 - add date search to admin search interfaces; this may be easier to leave until we do the refactor
