### ISSUE TITLE
discontinued tag in API

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1356]
Hello CL

Is there an API field for when  a journal is discontinued and not replaced by another one?
There is an "oa_end" element... could we rely on this?

**Comment by Steven-Eardley** [comment]
I don't think there is - the field we need seems to be omitted from the API. The journal model contains the field ```discontinued_date``` which is used to show the "Ceased publication" field on the TOC, but this isn't in the model the API uses. That could possibly be because it was added more recently than API v1 was released.

We have been discussing how we can add a new improved API version (v2) as these improvements add up - APIs should ideally remain the same once they are released, preventing breaking everyone's code.

As for ```oa_end```, it's the field we use for the answer to *Year in which the journal stopped publishing OA content* so that could be useful, but I'm having trouble finding an example. Using the query below I looked for journals that were not continued but were discontinued:

https://doaj.org/admin/journals?source={"query":{"filtered":{"filter":{"bool":{"must":[{"term":{"index.continued.exact":"No"}},{"range":{"bibjson.discontinued_date":{"lt":"1483228800000","gte":"1451606400000"}}}]}},"query":{"match_all":{}}}},"from":0,"size":10}

However, the first couple of journals we get back have a ```discontinued_date``` and an ```oa_start```, but no ```oa_end```.

**Comment by ClaraDOAJ** [comment]
Thanks! Let's leave this open and see if we can make an improvement now that Dom is back.

**Comment by ClaraDOAJ** [comment]
Hi @Steven-Eardley 

This is the reply:

 Unfortunately, we really require the discontinued information. Is there any possibility for a workaround solution, e.g. do you see a chance to copy the "discontinued_date" into "oa_end"? From my perspective that would be logically correct.

Could we also suggest to release a new version of the API, including elements added more recently?

**Comment by dommitchell** [comment]
@ClaraDOAJ can you forward me the whole thread via email?

**Comment by ClaraDOAJ** [comment]
@dommitchell sure. I just did.

**Comment by dommitchell** [comment]
I think it would be unwise to use the OA_end field actually. It is a legacy field now but I am certain that some records still have that value in and we may choose to start recording when journals ceased to be OA, especially when we start adding back journals that were previously removed because they stopped being OA.

A separate discontinued field would be much better in the long-term.
