### ISSUE TITLE
Display updated CC licences on journals' homepage

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1392]
Hello CL
Our current pages display the icon for CC licenses on the top right of the journal record. When you click on this icon, you are taken to the 3.0 version of the CC licenses. A new 4.0 version has been released and we need to get this update.

![image](https://user-images.githubusercontent.com/22593616/30699521-44bb7d06-9ee5-11e7-95c1-f068e39ca2df.png)

These are the new links:
CC BY
https://creativecommons.org/licenses/by/4.0/
CC BY-NC
https://creativecommons.org/licenses/by-nc/4.0/
CC BY-NC-ND
https://creativecommons.org/licenses/by-nc-nd/4.0/
CC BY-NC-SA
https://creativecommons.org/licenses/by-nc-sa/4.0/
CC BY-ND
https://creativecommons.org/licenses/by-nd/4.0/
CC BY-SA
https://creativecommons.org/licenses/by-sa/4.0/

Many thanks

**Comment by Steven-Eardley** [comment]
There's a question here whether we _can_ just change the license version. Since the license has changed over time, are we sure we can alter it without checking whether each publication actually provides the content under the newer license?

The difference table can be found here:
https://wiki.creativecommons.org/wiki/License_Versions

Also:
* We don't specify a license version when we store the record.
    - Does this matter to the DOAJ? The user can always find the exact version from the journal's actual website, after being classified on the DOAJ as one of the CC licenses
* On the application form, we point users towards the page https://creativecommons.org/licenses/ which always shows the most recent (4.0 currently, since 2013-11-25)

So, given that all users have 'seen' that link since the reapplication project, perhaps there's an argument that any time the license has been selected it means CC 4.0, and we can just change the UI as Clara requests.

**Comment by ClaraDOAJ** [comment]
Exactly, that is what I guessed given we point them to the latest versions. I think we can assume that any accepted reapp or new application does have the new CC 4.0.

@dommitchell do you agree?

**Comment by dommitchell** [comment]
There's no massive licensing changes between 3.0 and 4.0 (https://creativecommons.org/share-your-work/licensing-considerations/version4/). Let's go ahead and repoint the logos to the most recent version. Thanks!

**Comment by Steven-Eardley** [comment]
Live now, ready for review.

**Comment by ClaraDOAJ** [comment]
Fantastic! Closing issue.
