### ISSUE TITLE
Discrepancies List of journals online vs CSV file

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1402]
Hello CL, 
This is weird and worrying. Could you help, please?

Hi there,
 
I am trying to download the listing of all medical journals in the DOAJ. When I select “Medicine” as the subject in the main search page, I come up with 595 journals. However, when I download the CSV file, I find 2325 journals with “Medicine” as the subject (see yellow highlight in attached file). Are you able to please help me understand the discrepancy in these 2 numbers and which is the most comprehensive/correct list of medical journals to use?
 
Many thanks in advance,
[doaj_20170926_1730_utf8 LS.xlsx](https://github.com/DOAJ/doaj/files/1336262/doaj_20170926_1730_utf8.LS.xlsx)

**Comment by ClaraDOAJ** [comment]
Hello CL,

This one is quite urgent, could you have a look, please?

Thanks!

**Comment by dommitchell** [comment]
I think that this might be because of inheritance: the Medicine category is a parent so all journals in any subcategory under Medicine also inherit Medicine. That's right, right @richard-jones ?

**Comment by Steven-Eardley** [comment]
Bang on, Dom. 

For example, on the search page we see that the [Indian Journal of Orthopaedics](https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22journal%22}}]}},%22query%22:{%22query_string%22:{%22query%22:%22Indian%20Journal%20of%20Orthopaedics%22,%22default_field%22:%22bibjson.title%22,%22default_operator%22:%22AND%22}}}},%22from%22:0,%22size%22:10}#.WdN_oEyZNL8) has the category **'Orthopaedic surgery'** in the facet list, but this is displayed in the results as **'Medicine: Surgery: Orthopedic surgery'**

It's the latter bit of text we put on the CSV, so the parent category appears there while it isn't on the filter list. 

The (currently 600) journals appearing under a [filter just for **Medicine**](https://doaj.org/search?source={"query":{"filtered":{"filter":{"bool":{"must":[{"term":{"index.classification.exact":"Medicine"}},{"term":{"_type":"journal"}}]}},"query":{"match_all":{}}}},"from":0,"size":10}) are those journals that have the parent category selected alone.

I can see how this can be confusing, perhaps it would be worth making an enhancement to show all medicine subcategories under medicine, since they are hierarchical. I'm not sure at this stage how we'd show only those with the parent category selected in that case.
