### ISSUE TITLE
Journal application submitted without answers to compulsory questions

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1404]
Can you tell me how this was submitted?
https://doaj.org/admin/suggestion/5e2d3a5ba1544f7c8ff9f35dc4bedb17

It was filled in online, manually and the 'bug' happened twice. (https://doaj.org/admin/suggestion/239ff6a2d95549358d5f0b1af0094da0 - but we asked the submitter to fill it in again.)

**Comment by Steven-Eardley** [comment]
Interesting. I'm having trouble replicating this. When I try to submit the form after copying all of the fields, it fails validation as expected:

<img width="594" alt="screen shot 2017-10-04 at 10 13 06" src="https://user-images.githubusercontent.com/1446355/31168380-042a34a0-a8ed-11e7-94c9-11bc93d005ce.png">

But I can confirm these fields are missing from the saved application record.

**Comment by dommitchell** [comment]
Another one here: https://doaj.org/admin/suggestion/a29fc2ff235c48298b3a5ba7ddf859f9

**Comment by greboun** [comment]
this really should not be possible  content  licensing info is missing
except for deposit policy question
Are there still more of these?
The application was not triaged yet, so Bella would go and reject it



Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by dommitchell** [comment]
The last time this happened, [I think] it was tied to an Internal Server Error where something had failed exactly as someone was making a submission. CL will be able to confirm. Bella will alert us if there are more.

**Comment by richard-jones** [comment]
@richard-jones @Steven-Eardley and @emanuil-tolev to review possibilities for reproducing this

@dommitchell to review the extent of the problem.

**Comment by richard-jones** [comment]
We have had a look at this in our tech meeting today, and now know the answer.  There is a bug in the form crosswalk which emerges under the following situation:

* A user selects "Other" on question 47
* A user provides the text "None" next to the "Other" selection on question 47.

This will pass form validation, and then the crosswalk will erroneously interpret the text "None" as a python-language NoneType, and ignore that entire section of the form, resulting in the behaviour described in this issue.

The issue could also be reproduced with the following values in Other: "none", "False", "false".

I will look into a fix for this today, and provide a PR later.

In the mean time, the extent of the problem is as follows:

* 12 items are affected
* Affected items range in date from 16th April to 3rd October

The ids of affected items are:

5e2d3a5ba1544f7c8ff9f35dc4bedb17
b6c483383e8742d5839ac65cd8f9e9fb
9e3d4b960d534a5caa387a93833394ed
bbbff67d836743ac8aa7f6d8dc747346
7df42d641cba43e4aa28ef4778672970
d87331bf59bb4c33aaa89ca6d0b78476
a29fc2ff235c48298b3a5ba7ddf859f9
83cb365fcd274825ac143863888bf5a3
e178c203fd0f4c6eab5e1d7ae237b1bc
93066a95f4424e75bb28d8378d8520a2

The good news is that not only is this a small number of applications, but that they are also applications where we can be sure that they selected "Other" and entered "None" in the licence field, which would likely make them ineligible for entry into DOAJ.

**Comment by richard-jones** [comment]
I've tagged this tnm due to the age of the bug, and it's a quick fix

**Comment by dommitchell** [comment]
Wow! Fantastic work guys! Thanks for the sleuthing and analysis. Much appreciated.

And a relief to see that its limited to a few!

**Comment by dommitchell** [comment]
I have now rejected all of these and asked the publishers to submit again. Closing
