### ISSUE TITLE
OAI-PMH: deleted records labelled as transient

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1408]
http://www.openarchives.org/OAI/openarchivesprotocol.html#DeletedRecords

https://doaj.org/oai.article?verb=Identify

Why do we label deleted records as transient and not persistent? That we do it this way is causing users of the OAI-PMH feed to have a lot of dead wood in their metadata for us.

**Comment by dommitchell** [comment]
Notes from call: labelled as transient because we don't record that the record has been deleted, we just remove it. 

To avoid limbo records: they would have to reharvest everything and delete anything that wasn't still in DOAJ.

**Comment by richard-jones** [comment]
We label the deleted records as "transient" because the OAI-PMH implementation on DOAJ is effectively a wrapper around the search interface, which presents the /latest/ versions of articles and journals ordered by their last update date.  The consequences of this are as follows:

1. We cannot represent deleted items - as they are deleted, they are no longer present in the search interface, so they simply vanish from the feed

2. We cannot represent incremental changes to articles and journals, as only the most recent version is available in the search interface

3. The "earliestDatestamp" always shows the oldest last updated date, which does not coincide with the oldest created date of items in the dataset

The reason for the decision to do it this way is down to practicality and ease of implementation.  Making the OAI-PMH interface a wrapper around the search interface provides a "good enough" implementation.  To do a full implementation, supporting deletes and incremental changes, would require creating a full publicly accessible history system which could be filtered by sets and paged, so is considerably more work, and requires more substantial server infrastructure.  The rate at which items are updated in DOAJ is fairly significant (especially articles), so the decision was taken not to attempt to do it that way.

**Comment by dommitchell** [comment]
Thank you very much!
