### ISSUE TITLE
OAI-PMH service is timing out.

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1432]
From user:
> How many articles are currently in DOAJ? The website says 2,680,000
> articles. When we retrieve the metadata of all articles through OAI-PMH we
> receive only 760,000 articles. Previously we had around 2,280,000 articles.
> Is this big decrease because of the Reapplication project? Or should we be
> retrieving more articles?

ET said: 'FYI, inability to harvest the entire article dataset, seems like a timeout The problem is that it's kinda hard to reproduce. If it happened during a high load period then when you try again it won't happen.  We can try harvesting all the data from the OAI endpoint ourselves, there's a script that does that. If that repeatedly fails on live, then the problem is isolated and easier to fix.'

Can you advise what a suitable response back to the publisher should be please?

**Comment by richard-jones** [comment]
We need to ask the user more information about how they come to this situation.  It could be one of a couple of situations:

* They get to 760,000 articles, and there is no more resumption tokens, the cursor and article count in the response indicate that they are at the end of the feed.

* They get to 760,000 articles, and attempt to retrieve the next page of results and receive an error, which stops their harvester.

Can we find out which one of these situations, or any other situation that we haven't thought of, occurs?

**Comment by dommitchell** [comment]
Answer from contact:
/start/
There was no error when the retrieval stopped, so there was probably no resumption token. To be sure, I would have to run the retrieval again.

It is to be expected that we retrieve more articles?
-------------------------
We tried again and retrieved 2,723,742 articles (of the 2,725,232 listed on your homepage). Thank you for your help.
/ends/

It would seem that this may have been connected to the system issues we have been having, or? @richard-jones thoughts?

**Comment by richard-jones** [comment]
We know that there are some inconsistencies between the data on the front page and the data in the search results (see #881 ) so that probably accounts for the difference.  Also, those numbers for articles are constantly changing, so it's a difficult one to verify.  That they are in the same ball-park, suggests that everything is working fine.

I'd be very surprised if there was no resumption token part-way through their processing.  The number of results they have is a round number, which is very suspicious - it means that they got a full result page, and then not the next page.  This would imply a bug in the OAI-PMH code at our side if that were the case (rather than a problem with the index), and that code is well tested - if this could happen, it would have happened already.

Probably a timeout, which failed silently at their end, would be my guess.

**Comment by dommitchell** [comment]
Thank you. So any action here?

**Comment by richard-jones** [comment]
I don't think so, no.
