### ISSUE TITLE
Full text not working for 1988-7884

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1450]
Hello CL

We detected that the full text of the articles at the journal Ciencia Cognitiva (1988-7884) were not working. I mentioned that to the publisher and they replied with something that I think is very relevant, see below: 

I think it is a matter of metadata upload, but I am not sure if/what they are doing wrong. Apparently they are uploading their urls correctly, but they sometimes get a string of text in their url and then the link does not resolve correctly.

----

Hello, Clara. Thank you for checking these things. 

It does not seem a problem on our side, though. The link to the fulltext in the article's page at DOAJ (https://doaj.org/article/2fb5f0e2ce894288b2e43468c4353b27) is the following: 

https://doaj.org/article/www.cienciacognitiva.org/?p=413

If you remove from this link the initial part and leave only the part that pertains to us it becomes:

www.cienciacognitiva.org/?p=413

If you try this link in a browser, you will see that it works well and takes you to the correct article. 

When I fill up the metadata of a paper at DOAJ, I input the link to the full text as follows: http://www.cienciacognitiva.org/?p=413

So, it looks like the problem is that DOAJ's software is adding some text to the link which makes it useless.

Keep me up with this issue, please, and let me know if there is anything else in which I can help.

**Comment by richard-jones** [comment]
The problem here is that the database only has the string "www.cienciacognitiva.org/?p=413" as the URL.  This means when it is rendered on the page, the browser does not see an "http" prefix, so it assumes it's a relative URL, which would be resolved at https://doaj.org/article/www.cienciacognitiva.org/?p=413.

I had a quick check through of the crosswalk, and everything looks fine.  Plus, this is probably one of the most widely used bits of code in the whole DOAJ.  If the article crosswalk removed the "http" from the start of urls erroneously, this would be a problem for every article.

I'd guess they are missing the leading "http" in their XML in the fullTextURL field.  Could you ask them to send us an XML file that when uploaded exhibits this problem?

**Comment by ClaraDOAJ** [comment]
Thanks! 

Interesting. Yes, of course. I have asked the publisher to send us an xml. Will keep you posted!

**Comment by ClaraDOAJ** [comment]
They say they do not use xml import but manual entering. They say they always use the http
Example:
http://www.cienciacognitiva.org/?p=1538

**Comment by richard-jones** [comment]
I've tested the crosswalk for the article metadata form, and it does not destroy the "http" portion of the URLs.  I believe this is user error, and that they have only put in www.cienciacognitiva.org/?p=1538 in this case.

**Comment by dommitchell** [comment]
Awaiting comment from publisher
