### ISSUE TITLE
Google Analytics Site search

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1454]
I am trying to set up Site Search for DOAJ in Google Analytics and have become stuck. GA is asking for the query parameters that designate a search. A typical search URL may be:

https://doaj.org/search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22%20Journal%20of%20Aeronautical%20Materials%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

Can you help me identify what the query parameter(s) is/are?

Thanks

**Comment by Steven-Eardley** [comment]
As you've seen, the elastic search queries we expose don't play well with google analytics. If you URL decode the above query it's a bit more readable:

```https://doaj.org/search?source={"query":{"query_string":{"query":" Journal of Aeronautical Materials","default_operator":"AND"}},"from":0,"size":10}```

So the only query parameter they'd recognise is the ```?source=``` with the entire ES string as the value. They actually want something like 
```/search?query=Journal+of+Aeronautical+Materials&default_operator=AND&from=0&size=10```

It would in fact be possible for us to use a URL convention like that above, and translate it to ES queries in the back-end for sending to the query endpoint. This would require a little bit of development in facetview / edges.

Instead, I think we might want to deliberately send site search data, rather than getting google analytics to read it from a URL. From the [docs](https://support.google.com/analytics/answer/1012264?hl=en):

>Option 2: Customize the tracking code on your results page to dynamically specify a virtual page path that includes the query keywords. The tracking code on the results page would look something like:

    analytics.js: ga('send', 'pageview', '/search_results.php?q=keyword');

Which means we'd specify a pretend page which represents the searches, and we can choose how we generate the URLs. This is a little bit simpler, but again would be best implemented in facetview or edges.

**Comment by dommitchell** [comment]
Thank you! This is then "post Refactor"?

**Comment by dommitchell** [comment]
Leaving for now. Dom to investigate.
