### ISSUE TITLE
Fix and extend Google Analytics reporting for non-UI endpoints

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1462]
The GA recording has recently ceased working, and we need to diagnose and fix.

The Universal Analytics python module is a couple of years old, perhaps the API has changed, and we need an update.  This project has not changed on github for a couple of years, so it's possible it no longer provides the support we need.

See also some advice by Google on how to record analytics:

https://cloud.google.com/appengine/docs/flexible/python/integrating-with-analytics

We would basically be integrating with their Measurement Protocol, which is documented here:

https://developers.google.com/analytics/devguides/collection/protocol/v1/

I'd like to see us put together an analytics module which also wraps up some of the shared secrets from the analytics code.  For example, instead of specify the string "API Hit", this should be a reference to a constant.

We should have both a decorator and a direct function for recording events.

Currently the analytics is only applied to the API, and we should extend this to cover all the other non-UI endpoints:

* OAI-PMH
* Atom
* OpenURL
* Journal CSV download
* any others?

**Comment by richard-jones** [comment]
Remember that once we've done this, this could open up better ways of tracking widget usage.

**Comment by Steven-Eardley** [comment]
@dommitchell Can you clarify, has Google Analytics completely stopped working in production? I.e. the dashboard shows no users or sessions whatsoever.

I've tried adding GA to the test server without changing the code, and it works for the main pages.

**Comment by dommitchell** [comment]
Nope, that's the wrong view. Use this one:
https://analytics.google.com/analytics/web/?authuser=1#embed/report-home/a46560124w77600930p80218834/

**Comment by Steven-Eardley** [comment]
API data is missing from behaviour / events (the historical data)

**Comment by Steven-Eardley** [comment]
Okay @dommitchell, I reckon I've fixed events so that they appear in the behaviour reports (on the test server currently). Next I'd like to know a little more about what you'd like to gather from the non-UI endpoints.

### OAI-PMH
At the moment we have the following actions:
* Identify
* ListMetadataFormats
* GetRecord
* ListSets    
* ListRecords
* ListIdentifiers
And two types, article and journal. I'd propose an event like this:
```JavaScript
{
    event_category: "OAI-PMH"
    event_action: "article|journal:{identify|listmetadataformats|getrecord|...}"
    event_label: "<record ID>"
}
```
I.e. For each of the 6 actions we preface their type for 12 total different actions:
```article:identify, article:getrecord, journal:identify, journal:getrecord etc...```

For the record ID in the label we'd put the record that's been requested, e.g. see this real request:
```/oai.article?verb=GetRecord&identifier=oai:doaj.org/article:7ac94ce43e954d5688a1d45c61a90ff7&metadataPrefix=oai_doaj```

### Atom
As far as I can tell, the atom feed doesn't take any parameters in from users. An event would look like:
```JavaScript
{
    event_category: "Atom"
    event_action: "feed request"
    event_label: "(not set)"
}
```

### OpenURL
OpenURL is a proxy for our query endpoint, so it can take a wide range of parameters. It's possible to differentiate between articles and journals, though.
```JavaScript
{
    event_category: "OpenURL"
    event_action: "retrieve article|retrieve journal"
    event_label: "<query parameters>"
}
```
The event_label in this case could be a parsed list of what the request was searching for, e.g. ```issn=1932-6246&genre=journal```. 

### Journal CSV download
This would look very much like Atom - a log of the request with the event category "JournalCSV"

### any others?
Are there any more things we'd like to include?

**Comment by Steven-Eardley** [comment]
Actually, there may be much more we can do than the above by utilising custom parameters in events. Stay tuned.

**Comment by dommitchell** [comment]
So you don't need feedback from me yet?

**Comment by Steven-Eardley** [comment]
Not yet, I think there's more designing I can do.
