### ISSUE TITLE
Server errors

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1477]
Webmaster Tools reported a large number of 503 errors (3600) on 22nd Dec, continuing through to 2nd Jan at lower levels:

https://www.google.com/webmasters/tools/crawl-errors?siteUrl=https://doaj.org/&authuser=1

Please can you take a look and let us know what has caused this. I presume it is because DOAJ went down but no-one would have reported it. Can I have the details please?

**Comment by Steven-Eardley** [comment]
There were a large number of requests from the Yahoo 'Slurp' spider, which were rate limited with 503s in order to keep the site responsive for other users. There were no downtime incidents logged at all over that period.

There are also some rate limited requests from typical API users, which might be irritating, so we'll be taking a look at this when we profile the performance of the app in the future.

**Comment by Steven-Eardley** [comment]
Also, rate limited requests to agent strings similar to:

```"Mozilla/4.0 (compatible; Pure dk.atira.pure.base-uk.cust-uk-macquarie:cust:5.10.1-1)"```

Which seem to be related to Pure / Elsevier.

**Comment by dommitchell** [comment]
Fab. Thanks for your sleuthing.
