### ISSUE TITLE
Provenance reports missing

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1481]
Last batch we received was 1st Nov. We're missing 1st Dec and 1st Jan.

**Comment by dommitchell** [comment]
Duplicate - closing

**Comment by Steven-Eardley** [comment]
Once again, they've generated fine and this time it thinks sending the email succeeded. I've even found the January run in mailgun's log:

<img width="1340" alt="screen shot 2018-01-08 at 16 18 04" src="https://user-images.githubusercontent.com/1446355/34679988-99543b50-f48f-11e7-974d-2970a9b6d74d.png">

I can't see December's because they only keep logs for 30 days, not ideal for a monthly task.

It would be good to know why these aren't getting to you, so can you look again, otherwise I can send them myself from the server.

**Comment by Steven-Eardley** [comment]
Also, the times are so off in that screenshot because as noted they are in EST, i've configured that now to UTC.

**Comment by dommitchell** [comment]
@Steven-Eardley  I must apologise. I found them in the feedback inbox by searching (although they weren't in the inbox). Can you change the delivery email address to mine? dom@doaj.org that way we will skip a step.

Thank you!

**Comment by Steven-Eardley** [comment]
I've added your email to the config in addition to feedback, let's see what happens in another month!
