### ISSUE TITLE
'No' answers displaying as 'false'

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1483]
Somehow, answers on ToCs that are 'No' in the application form are displaying as False. Can this be corrected please?

https://doaj.org/toc/2089-4392

**Comment by richard-jones** [comment]
Ok, I see the issue - the "copyright" field is being stored as the string "False" rather than the boolean value False, so the UI converter renders it as-is.  Same as the other field where this issue arrises.  There is a quick fix, will look at it today.

We should check why this field is stored as a string rather than a boolean, like the other fields of a similar nature.  We might not be able to change it, though, given the ES mappings, so probably just a matter of ensuring that the UI presents the data correctly.

**Comment by Steven-Eardley** [comment]
Good spot.

This is ultimately because in [shared_structs.py](https://github.com/DOAJ/doaj/blob/develop/portality/models/shared_structs.py#L140) we coerce the bibjson record of copyright to a string:

```
"author_copyright" : {
    "fields" : {
        "copyright" : {"coerce" : "unicode"},
        "url" : {"coerce" : "unicode"}
    }
},
"author_publishing_rights" : {
    "fields" : {
        "publishing_rights" : {"coerce" : "unicode"},
        "url" : {"coerce" : "unicode"}
    }
},
```

Which explains why the template [toc.html](https://github.com/DOAJ/doaj/blob/develop/portality/templates/doaj/toc.html#L288) can't evaluate it in its map:

```
{%
    set TYN = {
        True : "Yes",
        False : "No",
    }
%}
```

Whereas it does work correctly in the TOC for plagiarism detection, which is coerced correctly:
```
"plagiarism_detection" : {
    "fields" : {
        "detection" : {"coerce" : "bool"},
        "url" : {"coerce" : "unicode"}
    }
},
```

**Comment by Steven-Eardley** [comment]
Pipped to the post by @richard-jones

**Comment by richard-jones** [comment]
Do you want to put in a quick fix, or shall I?  I'd probably just add "True" and "False" to TYN.  Then we can talk about the data-type later.

**Comment by Steven-Eardley** [comment]
I'll do that fix now.

**Comment by dommitchell** [comment]
Why did this change, out of interest? I am certain that both fields used to say 'No'.

**Comment by richard-jones** [comment]
This code hasn't changed for a while, so it's probably been like that for a long time without us noticing.  It was probably introduced when we updated the Journal data model, which was back in September 2016.

**Comment by Steven-Eardley** [comment]
@dommitchell ToC fix released now.

**Comment by dommitchell** [comment]
CLosing
