### ISSUE TITLE
Can 'Year of publication (articles)' default to Most recent year first?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#159]
When you expand the 'Year of publication (articles)' facet, the default view is count decreasing. It should be Most recent year first (Descending chronological order) as per the image here:

![default_by_year](https://cloud.githubusercontent.com/assets/5955396/2640894/18c07be4-bef0-11e3-9684-7e2ab1341489.gif)

**Comment by richard-jones** [comment]
I've now implemented a default display of descending year.

Though, note, this is actually an alphabetical listing, not a numerical listing, on account of the "year" field in the XML also being essentially free text.  The consequence is that there are some articles with odd years, like 2103 or 2!

Will be ready for review when the test server is ready and my recent PR has been merged.

**Comment by dommitchell** [comment]
https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22journal%22}}]}}%2C%22query%22%3A{%22match_all%22%3A{}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

There is no option to display more years and it seems to be limited to 14. What happens if I want to select articles from 1998?

**Comment by richard-jones** [comment]
This facet only appears for journals, so you can't use it to limit date added for articles.  We could also provide it for articles, though, if necessary.

This facet is a date histogram over the entire dataset, so it is only limited to the dates that are present in the data.  If 1998 isn't present, it's because there are no journals with a created_date in that year.  It also isn't limited to 14 years, it will be as large as is necessary to accommodate all the dates in the dataset: 2002 - 2015 inclusive in this case.  In 2016, it will have 15 entries, and so on.

**Comment by richard-jones** [comment]
Oh wait, we're talking at cross-purposes.

The link you sent me takes me to the page of journals with the Date added to DOAJ, which behave as I described above.

If you go to the article list instead:

https://doaj.cottagelabs.com/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

The Year of publication is a terms facet ordered alphabetically by default, which puts the most recent years at the top, but is therefore also polluted by the odd things that people put in this field.

We can't do a date histogram on this field unfortunately, precisely because it does contain all this other non-year data.

**Comment by dommitchell** [comment]
Oops, my mistake. So here's a link to articles:
https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}]}}%2C%22query%22%3A{%22match_all%22%3A{}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

The default sorting is A-Z and I think it should be chronological but you said:

> The Year of publication is a terms facet ordered alphabetically by default, which puts the most recent years at the top, but is therefore also polluted by the odd things that people put in this field.

so to get this to work, we need to clean up the data, right?

**Comment by richard-jones** [comment]
Yes, unfortunately people don't just put numbers in this field so you can't order it chronologically.  The only option to get exactly what you want is a data cleanup, and an update of the ingest rules and article XML schema.

**Comment by richard-jones** [comment]
We could do something in a migrate script that inspected the year field and pulled it into another field specially designed for faceting in the case that it is a 4 digit year - that would give us a facet that made sense to the user, and the expense of not covering all the articles.

**Comment by richard-jones** [comment]
Decision: make the above facetable field, if the value is a 4 digit number in the range 1800 -> current year

**Comment by richard-jones** [comment]
Note to self: actually we've already got the indexed data to handle this.  We just need to provide a facet which is a date histogram of year granularity over the index.date field

**Comment by richard-jones** [comment]
Phew, that was significantly harder than I was expecting!

I've implemented this as a date histogram over index.date, which gives us what we want.  But since there are over 100 years worth of dates, the facet is unusably large (and date histogram facets don't have ranges - you get everything).  So, I've implemented a show all/less feature for fv2 for that facet.

**Comment by dommitchell** [comment]
This is great! Closing

**Comment by dommitchell** [comment]
Can you remind my what the caveat was for this method of creating the histogram? Someone has asked: 

My team is doing some research correlating content in DOAJ with other factors such as APC, and have uncovered what appears to be a problem with harvesting or displaying articles published in the year 2013.

Our data was screen scraped in May 2014. To determine if this was an anomaly I did an article search today by year of publication and came up with these results:

3012 (2)
2102 (2)
2015 (1)
2014 (1331)
2013 (6938)
2012 (211568)
2011 (119665)
2010 (63834)
2009 (50864)
2008 (44019)
2007 (39430)
2006 (36098)
2005 (32899)
2004 (27876)
2003 (24549)

Following are the sums of article counts for a couple of years based on our screen scrape as of May 2014:

2013:  169,292
2012:  226,837

The 2014 numbers were also understated, eg some journals with only 1 article in DOAJ from 2004 - 2013 published one or two full issues in 2012.

**Comment by richard-jones** [comment]
The main caveat is that the articles need to have coherent dates associated with them.  Articles with no date, and articles with dates that we can't make sense of aren't included in the histogram.

If they can give us some details of a specific incongruity that would be interesting - a ToC for a journal with articles in this period where the count doesn't look correct.  Then we could see what the specific reason is.

**Comment by dommitchell** [comment]
@richard-jones don't suppose you can tell me easily how many articles have not been picked up by the histogram can you?

**Comment by richard-jones** [comment]
There 7565 which are missing the index.date field that it's built over.

Reasons for missing that field are either no publication year or malformed publication year/month data.

**Comment by dommitchell** [comment]
Perfect!
