### ISSUE TITLE
Embedded metadata + enhance search results

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#178]
see also #12 

Is there anyway to improve the display of search results now that the effects of the sitemap are being seen in Google? For example, a search on an article returns: http://bit.ly/1iQ2SKx where the 3rd result down shows the volume number, 6, and DOAJ.

Ideally this would show the name of the journal and say 'Volume 6' (and DOAJ if possible).

Is this related to our future development request for structured metadata perhaps?

Thoughts?

**Comment by richard-jones** [comment]
* Embedded metadata for the ToC pages (use meta tags)
* Urls should contain the journal title (but not have any effect on the routing otherwise)
* Queries for the ISSN should redirect to the canonical url
* Update search interface to point to correct url

**Comment by emanuil-tolev** [comment]
We should use subject and keywords in the meta keywords tag. + a few generic ones like DOAJ

**Comment by emanuil-tolev** [comment]
> Embedded metadata for the ToC pages (use meta tags)

Done.

> Urls should contain the journal title (but not have any effect on the routing otherwise)

Not done. This has proven to be quite sticky to achieve, mostly because we use the URL to also put in other optional args like volume and issue. Basically the only straightforward situation right now that could merit journal title in the URL would be if you also specify the volume and issue, which is a bit pointless.

However, I do have an alternative approach in mind. Putting a separator, like three dashes --- after the ISSN or internal ID in the URL, and then putting in a slug of the journal's (or article's) title.

http://doaj.org/toc/1307-4733---Novitas_ROYAL - obvious
http://doaj.org/toc/1307-4733---Novitas_ROYAL/6 - vol. 6 of the same journal
http://doaj.org/toc/1307-4733---Novitas_ROYAL/6/8 - vol. 6, iss. 8 of the same journal

This requires a bit more trickery and is outside the scope of the original issue for getting basic SEO in so Google doesn't display gibberish, but I think has some value as one of the 3 main things search engines look for. As it's both worth introducing and outside of scope I'll try to find some time this or next week to do it but no guarantee. It can be easily hotfixed in, in as much as the work is non-trivial (need to slugify titles in python and JS and modify the /toc route), but once "done" is very self-contained and can be rolled out on its own at any time.

> Queries for the ISSN should redirect to the canonical url

> Update search interface to point to correct url

**Comment by emanuil-tolev** [comment]
@dommitchell you can observe this e.g. here: https://doaj.org/toc/1980-6108

Notice the title of the page. You can also see the description tag if you press Ctrl+U to view page source. This toc's tag is ```<meta name="description" content="Information about the open-access journal Scientia Medica in DOAJ. DOAJ is an online directory that indexes and provides access to quality open access, peer-reviewed journals.">```.

Finally, I've done the same for article pages, see e.g. https://doaj.org/article/0000178c89214dc8b82df1a25c0c478e .

This should resolve the original problem of weird Google search results. Close the issue if those look good.
