### ISSUE TITLE
[BUG] Invalid Swagger for APIv2

### ISSUE THREAD

**Issue by mauromsl** [DOAJ/doaj#1836]
**Contact details of bug reporter (or proxy of bug reporter)** 
Mauro Sanchez - mauro.sanchez@openlibhums.org

**User account you are logged in to when this occurred**
NA

**Where this happened**
API

**When this happened**
From 2021-91-19

**What happened**
We are adapting our API client for compatibility with the DOAJ API v2 and we were planning on using the swagger spec to auto-generate our client.
It seems the swagger.json exposed on the doaj.org site is not swagger 2.0 compatible.

**Expected behaviour**
Swagger to pass validation

**How to reproduce**
Try to validate the [swagger.json](https://doaj.org/api/v2/swagger.json) with any of the multiple validation tools.
e.g: https://validator.swagger.io/

**Screenshots**
```
---
messages:
- "attribute info.base_url is unexpected"
- "attribute paths.'/api/v2/applications'(post).[application_json].type is unexpected"
- "attribute paths.'/api/v2/applications/{application_id}'(put).[application_json].type\
  \ is unexpected"
- "attribute paths.'/api/v2/articles'(post).[article_json].type is unexpected"
- "attribute paths.'/api/v2/articles/{article_id}'(put).[article_json].type is unexpected
```
[...]

**Comment by dommitchell** [comment]
Thanks Mauro! We'll respond to this as soon as we can.

**Comment by dommitchell** [comment]
Hello @mauromsl 

We have reviewed Swagger. Thanks for logging this. We did spot some oddities:

- We are using a property base_url that we shouldn't be. We will look into why this property is being used, and if we can get rid of it
- For the objects of in: body we are using a type field rather than a schema field to define the content. We will find a fix here. 
- Some objects are missing descriptions, which will be easy to add

We have also opened a separate task to upgrade swagger which is now on our To Do list.
