### ISSUE TITLE
Applications should not be able to be assigned to ed/AssEds without an owner

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#217]
http://test.doaj.cottagelabs.com/admin/suggestion/1659dbfd4ce144459c91542c135c709f

Obviously, this has only been produced through testing and is unlikely to happen on the live site. However, no application (or journals for that matter) should ever be assigned to a user group without having an owner. 

Can we control for that?

**Comment by dommitchell** [comment]
This seems to have reverted. Adding an owner field is compulsory again. Can you change that?

![rejected](https://cloud.githubusercontent.com/assets/5955396/7292138/541444a8-e999-11e4-9dfd-d35b3071b59e.jpg)

**Comment by richard-jones** [comment]
Ah, ok, I see how this has happened.  Actually the code for this has not changed, it is behaving "correctly", in that this field is optional if the status field is set to one of the base status elements.  But since we've been moving the status elements around to be viewed differently by different user classes, the optionality of this field has got a bit confused.

Let me just be totally clear what we want - the Owner field should be completely optional for all ManEds, under all circumstances.

**Comment by dommitchell** [comment]
> Let me just be totally clear what we want - the Owner field should be completely optional for all ManEds, under all circumstances.

The Owner field should be completely optional for all ManEds, apart for Accepted where is should be compulsory.

**Comment by richard-jones** [comment]
fixed by next hotfix

**Comment by richard-jones** [comment]
should be fixed on live
