### ISSUE TITLE
Question 27 in public application form is not qu 27 in admin application form

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#330]
Seems to be the same for all records. As per our call (3rd Nov), we agreed that this is a numbering problem rather than a "missing" data question.

http://doaj.org/application/new
Does the journal provide, or intend to provide, article level metadata to DOAJ? *
Yes No
For new applications, metadata must be provided within 3 months of acceptance into DOAJ

vs

https://doaj.org/admin/journal/5b571ebb1aa74a4697f9ab5e1f8003d0
What was the first calendar year in which a complete volume of the journal provided online Open Access content to the Full Text of all articles? (Full Text may be provided as PDFs. Does not apply for new journals.) *

Use 4 digits for the year, i.e. YYYY format

**Comment by dommitchell** [comment]
@emanuil-tolev this is old and can be closed right?

**Comment by emanuil-tolev** [comment]
I think it can, we cleared this up a while ago in meetings. Do *you* have any questions around it :)? If not, feel free to close.

**Comment by dommitchell** [comment]
Reopening this because something has happened that might be similar. Will move into new task if not.

Question 29 in the Admin view of the application form is not question 29 in public application form. 'Does the journal provide, or intend to provide, article level metadata to DOAJ?' is missing from Admin view

https://doaj.org/admin/journal/0d518f1f25fa4de8a94bdc9345ac9897

https://doaj.org/application/new

**Comment by richard-jones** [comment]
We talked about this but didn't update the issue.  The reason is that the journal form and the application form have different questions in them.  In particular there are 2 fields in the application form which are considered part of the application process, but not part of the journal metadata (to do with how many articles were published in the last calendar year).

As such, the numbering of the questions differs between these two forms, as they are for two different object types with different internal data.

@dommitchell - not sure what the action we can/should take on this is.

**Comment by dommitchell** [comment]
I think the obvious answer is to have the numbering locked to each question so that  27 is always 27. How feasible would a solution like that be?

**Comment by richard-jones** [comment]
We should look at this after the reapplication shutdown, when we can start to modify the application form again.

**Comment by dommitchell** [comment]
We now have reached a situation where we wish to go back and review those journals who said that they will provide metadata to us but have not. We can only find this information in the "closed" application record and we can't update the live journal record. This is becoming a real issue for us and needs to be fixed.

https://doaj.org/admin/suggestion/5639852b801c4ee89bafc53f403e4239
https://doaj.org/admin/journal/f4ddafb6a9b44bacafced1d2a7c99440

1) Is there a workaround? Somewhere we can manually edit the answer
2) What would it take to fix this?

**Comment by richard-jones** [comment]
The root of this issue is in the data modelling - we've taken "plans to provide metadata" as a review question, rather than a property of the journal, so it doesn't go into the journal record.  I think we've been viewing the application up to this point as disposable, being replaced by the journal record once accepted.

So, I think we should take a quick step back and consider the models as a whole first, and then work out what to do about this.  It might be that an "accepted" application is still an active document (which is what this issue now suggests), rather than just a record that a journal once applied.

Discussion in the next meeting?

**Comment by dommitchell** [comment]
> It might be that an "accepted" application is still an active document (which is what this issue now suggests)

I don't think it suggests that. It is an archived copy that we need to refer to but one particular piece of information is missing or, actually "not visible". All I need is some way of being able to see that information. We never use accepted applications under any circumstance.

**Comment by richard-jones** [comment]
So, you can see the information in the application record, under the link here:

https://doaj.org/admin/suggestion/5639852b801c4ee89bafc53f403e4239

I thought what you meant was that you wanted to be able to change that from Yes to No in the cases that the journal won't provide the information.

Otherwise, we'll need to add this information to the journal record, which is relatively straightforward in terms of process, but will require a bit of work, as there are a number of aspects of the code that will need to change.

**Comment by dommitchell** [comment]
> So, you can see the information in the application record, under the link here:
> 
> https://doaj.org/admin/suggestion/5639852b801c4ee89bafc53f403e4239

Yes, but that question: 'Does the journal provide, or intend to provide, article level metadata to DOAJ?' doesn't exist in the active journal record and it is *there* that we may wish to update this question.

> we'll need to add this information to the journal record,

But shouldn't it be in the journal record already? Why isn't it?

Let's discuss on the call today. Thanks!

**Comment by dommitchell** [comment]
Not currently part of the journal record. Can just expose it in the Admin record?

Not a quick change, including the data model and the forms and transition to accepted journal. 

RJ will assess

**Comment by richard-jones** [comment]
Closing this off again, as I've opened a specific issue #1110
