### ISSUE TITLE
Potential problem with HTTP XML upload of article metadata

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#338]
Just so this doesn't get lost:

"Uploading some more files in DOAJ panel, we came across a problem - some of them, for unknown to us reason, fail to be processed and imported. That is the case e.g. with http://doaj.versita.com/j/amm.2014.59.issue-2.xml. Other files, in the same format and put in the same catalogue structure, are processed and imported correctly. Could you please check what could be the reason?"

**Comment by richard-jones** [comment]
The file http://doaj.versita.com/j/amm.2014.59.issue-2.xml gives me a 404, so I can't look at it.

If it was 404ing before that might have caused the error, but I suspect they've just removed the file since this problem arose.

My guess would be the usual: there are articles in this upload which are for a journal owned by another user account.

**Comment by richard-jones** [comment]
@dommitchell - assigning back to you for the moment; if you can get hold of a copy of that file, I can take a look again.

**Comment by dommitchell** [comment]
No longer an issue.
