### ISSUE TITLE
Question: sort applications that have No editor

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#343]
Is there any way we can add functionality that will allow Managing Editors and Editors to See all journals, applications and reapplications that have NOT been assigned to an Editorial Group or AssEd?

So for example, could all records be assigned a default flag when they are generated (like 'None') which is removed or trumped when the record get assigned?

Use case: managing editor goes into the list of applications and wants to find all applications received for the language Russian that have not be assigned to an Editorial group. 

Can we create a facet under Editorial Group and Editor: 'None'

**Comment by dommitchell** [comment]
@emanuil-tolev  Need to come back to this one. As ManEds are working through the back log, they cannot currently see all applications that are NOT allocated to someone and they need to be able to do this. Is there a way we can surface this info?

Have updated the original stub.

**Comment by emanuil-tolev** [comment]
Let me ask a technical question before answering that with definite options on what to do. 

@richard-jones were you going to upgrade facetview to v2 in pvod project?

**Comment by richard-jones** [comment]
Yup, we are upgrading to fv2 during pvod.

Spoke about this during today's meeting.  I will have a look at the shape of the query that will return the results, and then we can consider how this would go into the interface.

@dommitchell - if you could outline the criteria that you'd be interested in initially, that will give me a handle on the problem to work with.

**Comment by emanuil-tolev** [comment]
@richard-jones good to remember in that case about https://github.com/DOAJ/facetview - a fork of facetview (v1) modified for DOAJ purposes. This is what changed between original facetview1 and DOAJ facetview1: https://github.com/DOAJ/facetview/compare/doaj_version .

I'd recommend *not* maintaining a DOAJ-specific fork this time of course. And it should not be needed, with support for "themes".

**Comment by dommitchell** [comment]
As per our call today, the criteria would be a way to display:

All applications or reapplications, of any Application status, that have not been assigned to an editorial group.

**Comment by richard-jones** [comment]
I've taken a look into the form of the query to do this, and am happy that we can create these queries.  The only thing is that doing it within the current search framework isn't possible - we will only be able to do it with the new version of facetview.  

Even then, it is moderately tricky to work this into the UI, so it would be a good few days work, I'd anticipate.  But, we'd actually be solving the problem in general, so then you would be able to check any fields you like for emptyness.

The interface could be expressed in a couple of ways:

1. For each filter on the left, have a "show all missing" value inserted in there

2. A separate filter which lists the fields to look for emptyness on

Not sure which would be better.

**Comment by dommitchell** [comment]
Needs to wait until the new facet view is in place.

**Comment by dommitchell** [comment]
I think (1) would be more intuitive here so we'd like to go for that if possible.

**Comment by dommitchell** [comment]
Adding to tnm

**Comment by richard-jones** [comment]
For my benefit during implementation:

1. Add new option to facet, to turn on "show all missing".  This requires a default value (false), and will require the terms facet renderer to render a custom link at the top/bottom of the facets.  When "show all missing" is selected, this should be rendered as a removable filter option, as if it were a normal filter value, which means modifying the first part of renderTermsFacetValues.
2. Bind that link to a new function like clickShowMissing, which will remove all active filters on that term, and then set a new active_filter with a value like "_missing" (this should also be configurable, so that clashes with the data are avoided)
3. Change the ES query builder in makeFilters to respect the new "_missing" term filter value (we'll create a new function called missingFilter which will build the relevant query part)
4. Add support for parsing "missing" filters from URL query, which will need to create options._active_filters as per (2)
5. Modify deriveOptions if necessary to read _active_filters to active_filters
6. Modify clickClearFilter and deSelectFilter to handle the "_missing" value for a term filter
7. Modify renderActiveTermsFilter so that it displays a sensible "showing all missing" text value, with the usual remove option (bound to the same clickClearFilter as the facet, so that should just work)
8. Check that there are no value_functions on the facets which will be affected; if there are, they will need to also suitably modify the value - perhaps this is the place to customise what is shown in (7)?

That's probably it, but there will no doubt be some extra complexity involved.

**Comment by richard-jones** [comment]
@dommitchell - just bouncing this over to you one more time before putting it on the approved list; I've done an analysis of the amount of work involved, and it is at least a day, possibly a little longer depending on how well the difficult bits go.  Are you happy to go ahead on that basis?

**Comment by dommitchell** [comment]
@richard-jones yes, this is fine. Please proceed

**Comment by richard-jones** [comment]
While doing this, also look at #688

**Comment by dommitchell** [comment]
@emanuil-tolev I'd like an update on this one please. Specifically: is there anything that you did on #994 that makes this one easier and less time consuming to tackle?

**Comment by richard-jones** [comment]
@dommitchell - we've been having another think about this in the light of #994 .  We /could/ use the same approach here as we did there, but it would have consequences.  If we did it that way, we would be able to offer you /another/ facet, which was something like:

+ Has Editor Group
  Yes (100)
  No (50)

But this would necessarily be another facet, and not part of the "Editor Group" facet.

How does that sound?  Could you live with that awkwardness?  If so, we anticipate that would take quite a bit less time to implement than the currently proposed solution, which puts that functionality into the "Editor Group" facet.

**Comment by dommitchell** [comment]
This is clunky but ideal for what we need! Thank you! OK to go ahead as you suggest.

**Comment by dommitchell** [comment]
This is SO good and SO what we need. Let's get it live!

**Comment by emanuil-tolev** [comment]
How does the live version look now? Code deployed and migration ran.

**Comment by dommitchell** [comment]
Looking good!
