### ISSUE TITLE
Autofill in publisher dropdown not working

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#406]
For example, I know that there are 57 journals in DOAJ with the publisher 'De Gruyter Open' (DGO). If I open one of them and remove DGO as the publisher and then start typing De Gruyter.... some choices should appear below the field, right?

They don't.

![autofill](https://cloud.githubusercontent.com/assets/5955396/5106326/284b475c-6ff7-11e4-9965-d73ed656f1e2.jpg)

**Comment by emanuil-tolev** [comment]
It does work, but can't deal with spaces, so "de g" won't give you De Gruyter Open, but "ope" will.

**Comment by emanuil-tolev** [comment]
Or "gruy"

**Comment by richard-jones** [comment]
Just to summarise some of the conversation around this.  Basically, the issue is in the best way to obtain a good suggestion for the value of the field from the index with suitable performance.

Right now we use a prefix query, which is fast, but works on analysed fields, meaning they have been tokenised.  This has the advantage of allowing us to prefix search any of the words in a publisher name, and get back the whole publisher name.  So "Gru" and "Ope" will both match "De Gruyter Open".

The other thing we do is hold off on querying the index at all until the user has given us 3 characters.  The consequence here is that "De " covers the whole first word of "De Gruyter Open" and the space that the tokeniser spits the field on.  Meaning "De " is not a prefix of "De".

Options for making this better (and their consequeces) are:

* reduce the number of characters required before we issue the search to 2.  This will increase overall load on the index, and may give the user too many options to choose from to be useful.

* strip spacing in the back-end before prefix searching.  This will only improve the situation for a space at the end of the input string anyway, so "De " would find "De Gruyter Open", but "De G" would still not.

* Replace the autocomplete with a wildcard search on the non-analysed publisher field, then return a term facet on that field.  This is an expensive query, but the results would be excellent in the case that the user is searching for the actual first characters in the name.  Depending on whether we use one or two wildcards (two making the query /extremely/ expensive) we could also still support "Ope" detecting "De Gruyter Open".

* Carry on as we are, except if there is a space in the query string, in which case fall back to the wildcard query.  This could give us the best of both worlds - issuing expensive queries only when absolutely necessary.

**Comment by emanuil-tolev** [comment]
> reduce the number of characters required before we issue the search to 2. This will increase overall load on the index, and may give the user too many options to choose from to be useful.

Additionally we limit *results* we display to 5. If the minimum chars are decreased this almost certainly has to be increased.

**Comment by dommitchell** [comment]
I'd like to exhume this one. As we take on more and more people, the weaknesses in the sytem are going to become more problematic.

This one could produce all sorts of duplicates, errors etc.

@richard-jones how would the last option you describe above work?

**Comment by richard-jones** [comment]
We're agreed that we want to go with my 4th option above

**Comment by richard-jones** [comment]
I've now done an implementation of this which gives us some flexibility in the behaviour.

Right now it is set up to do a word-prefix search initially, and then when the user enters a space, goes into a full substring match mode.  The results of this are pretty good, though there are more options for the user to choose from this way, so their top 5 may not be the optimal ones.

So, for example, the following autocomplete suggestions now work:

    Gruy -> De Gruyter Open
    yter Op -> De Gruyter Open
    De<space> - > De Gruyter Open

I think we should try out the configuration I've set it up with initially, and then make a call as to whether to go back to a pure prefix query.  The pure prefix query means that if the user enters a space, we would expect the string they have entered to match the very beginning on whatever string they were going for.

So, to compare with the above, you would see the following:

    Gruy -> De Gruyter Open
    yter Op -> <no match>
    De<space> - > De Gruyter Open

**Comment by richard-jones** [comment]
deployed on test, ready for review @dommitchell

**Comment by dommitchell** [comment]
Works a treat. Thanks!

**Comment by emanuil-tolev** [comment]
Best check this works on live too ;).

The migration has been run on live and the code deployed.

It output
```
/home/cloo/repl/production/doaj/src/doaj/portality/datasets.py:594: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if variant.lower() == r:
Running in production
Loaded final config from /home/cloo/repl/production/doaj/src/doaj/production.cfg
Source {'index': 'doaj', 'host': 'http://gateway:9200'}
Target {'index': 'doaj', 'host': 'http://gateway:9200', 'mappings': False}
Upgrading journal
added journal 000b0582055346aaac5bc897061e4183 to batch update
# ...... lots of similar lines
added journal fffe303b17d64c309cfe0b05984f3eb4 to batch update
writing  302 to journal
```

**Comment by dommitchell** [comment]
It does! All good. Closing
