### ISSUE TITLE
Can we add timezone details to the Upload Date?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#462]
Currently this field says:

04 Dec 2014 15:23:38 

Can we add GMT or UTC? Or something to indicate it is not local time?

**Comment by Steven-Eardley** [comment]
@emanuil-tolev @richard-jones I've spent more time (ha) on this and I've decided there's either a naïve and superficial solution, or a real fix that actually changes quite a few things.

The problem is simply that in the dao underlying everything the timezones aren't recorded. So timestamps in the index are relative to whichever machine they were created on. To add a timezone label  when we display the timestamp, we could do the following:

* naïvely, use something like ```tzlocal.get_localzone()``` to find the timezone on the server and append its name whenever we print out a timestamp. In our case, this will say 'GMT' for files uploaded in winter, 'BST' for files uploaded in summer, and will only affect the UI. The problem is, if the server data has crossed timezones these will be incorrect - we are only checking where the server is *now*.

As an example:
```python
>>> here = tzlocal.get_localzone()   # here is a tzinfo object
>>> here.tzname(datetime.now())    # as of 07 Jan 2015
'GMT'
>>> summer = datetime(2014,6,6)    # 06 Jun 2014 00:00:00
>>> here.tzname(summer)
'BST'
```

* properly, we only ever encode dates using ```datetime.utcnow()``` to prevent these daft problems. Wherever the server is, the timestamps are written unambiguously and if there's a requirement to show local times, the translation is trivial using available libraries. This method will require some changes to the dao and each time ```datetime.now()``` is used, and a migration if the timestamps already written to the index are to be trusted.

**Comment by richard-jones** [comment]
Yes, you are quite right - the real underlying problem is that we record the times in the timezone of the server, rather than absolutely with timezone information.  I would like, overall, to fix that, by - as you suggest - always storing the utc time when we store a timestamp.

But, from a practical point of view for this project, I propose that we do your first option, since this should work provided that DOAJ runs on the same machine.  You can see how I did this for page lock timestamps here:

https://github.com/DOAJ/doaj/blob/develop/portality/models/lock.py#L52

So, propose to do the fix the simple way, but could you open an issue describing what we should do in the long run, and we'll look at how much is required to implement that later.

**Comment by Steven-Eardley** [comment]
Splendid, thanks.

**Comment by emanuil-tolev** [comment]
FYI we usually setup ntp and set the machine to the Europe/London timezone. But Richard's server had (and maybe still is) reverted to one of the US timezones for some reason. The live server should be ok, yes.

**Comment by Steven-Eardley** [comment]
UTC being shown was intended - It's the only timezone that's sensible to use as a baseline across the world. I.e. telling someone in the US that they uploaded it at some time GMT or BST is liable to be more confusing! 

What I've done is convert the server's local time to UTC, and displayed that. All times should really be stored internally as UTC, see #506.

**Comment by emanuil-tolev** [comment]
> @Steven-Eardley What am I looking for? GMT? I see UTC in the upload pane. Is that correct?

Yeah, coordinated universal time.

The issue originally said:

> Currently this field says:
> 
> 04 Dec 2014 15:23:38
> 
> Can we add GMT or UTC? Or something to indicate it is not local time?

So looks ok to me?

**Comment by dommitchell** [comment]
Yes, this is great! Closing
