### ISSUE TITLE
URLs being modified when they lack .com

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#467]
Acc: 14686996 - form accepted www.apa in all URL fields I tried If I look at it now the URLs are all www.apa.com. Did you change them? I didn't change anything.

This shouldn't be happening - check what is going on and make any relevant fixes.

**Comment by Steven-Eardley** [comment]
I can't reproduce this, so I suspect if a ```.com``` is being added it's happening browser side, possibly due to auto-complete. From what I see, the form will only prepend ```http://``` to some links, but accepts a variety of strings with at least one ```.``` as valid URLs, and doesn't change the record next time the form is viewed.
