### ISSUE TITLE
Make volume field compulsory in metadata upload

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#473]
https://doaj.org/publisher/metadata

Journal Volume must be compulsory both in the schema and the manual form

**Comment by dommitchell** [comment]
@richard-jones I'd really like to get this one done soon. The form is causing problems as it is now.

**Comment by dommitchell** [comment]
Just wondered if this was an easy change?

**Comment by dommitchell** [comment]
Can we get this one done quickly after PVOD goes live, as a one-off?

**Comment by richard-jones** [comment]
I've had a bit of a poke around this, and the side-effects don't seem to bad.  The work is:

- [ ] change the upload form and related validators/xwalk
- [ ] change the published xml schema
- [ ] update relevant site documentation, such as links to the schema (if we produce a new version), and information for people on what to do now it has changed
- [ ] have the outgoing OAI tests validate against the old schema not the new schema still, as articles without volumes will not validate.  Will probably also need to publish a separate schema for the OAI interface for users to reference, so that the differences are clear.

The considerations before going ahead are:

1. What, if anything, should we do about existing data that doesn't meet the new schema requirements?
2. If Journals are moving away from volume/issue publishing, is this a wise move in the first place?

@dommitchell - bouncing back to you for a decision on whether to go ahead.  We're probably looking at at least 2 days work here.

**Comment by dommitchell** [comment]
And actually, I think we should do the continuation/toc work first and then come back to this.

Removing from tnm for now.

**Comment by dommitchell** [comment]
This is now irrelevant. Closing
