### ISSUE TITLE
URL Shortening: Make search URLs more user friendly

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#51]
Is there anyway we can tidy up the search string URLs so that they are more user friendly? e.g:

http://www.doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22Practical%20Issues%20in%20Management%22,%22default_field%22:%22index.title%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22journal%22}}]}}}}}

**Comment by dommitchell** [comment]
@richard-jones  Isn't this part of PVOD project?

**Comment by richard-jones** [comment]
Ok, so we're at a point where we need to decide how to do this.

I'd be happy to create a new index type which offered "short" urls, and stored, in return, a serialised query string.

The only challenge would be creating a shortened url which we could generate reliably and uniquely.  Like uuid.uuid4() but much shorter.

Any thoughts?

**Comment by markmacgillivray** [comment]
I already made a url shortening separate service. I could install it on the
infrastructure if you want. I'll find the code... It was years ago.

**Comment by markmacgillivray** [comment]
Let me know if you do want this, I will buy a generic short domain for use on the shortener. I fancy clbs.xyz. Then we can use it to shorten any URL on any service. Keeps other service indexes/databases cleaner too. If the shortened url should still show doaj, then a proxy to the shortening service can just be written into the doaj nginx config - say doaj.org/u/SHORTID would go to clbs.xyz/SHORTID which would have the actual URL stored. 

Note however that this shortening service does not affect what is actually in the URL of the browser when a user is using it - if they copy that it will still be the same long URL. The short URL would have to be offered on the page itself - a button click to generate the short url.

To generate them on the fly, it would be bad to actually make and record a short url for every single page hit - that would happen very very often for any possible combination of search query, and result in a very big and very loaded index.

If it absolutely had to be that the URL of the browser as the user was using it had to show the short URL, then instead an algorithm should be implemented that actually encodes the URL generated by fv2 on the browser page, passes that as the URL param, and then the same algorithm implemented on the server side decodes it back into the full query param.

**Comment by richard-jones** [comment]
Decision: use bit.ly from search page, on request by user

http://dev.bitly.com/get_started.html

**Comment by richard-jones** [comment]
I've implemented a connection to bit.ly which handles shortening urls for doaj search queries only (necessary to prevent potential abuse of our bit.ly account to shorten arbitrary urls).

When the PR is merged and the test server is up this can be reviewed.

To see a URL being shortened:

1. click on the new "share" link
2. click on "(shorten url)"

This is a few clicks before the user gets the URL they want, but the alternative is to pre-shorten the urls when the user clicks "share", which they may do by accident or inquisitively.  Since bit.ly applies a limit to the number of URLs you can shorten per month, it seemed best to do this on request.  Also, link shortening is not instant - it can take upwards of a second - so best to not do it when the user isn't expecting it.

@dommitchell - for the production box, we will need an oauth2 token which is specific to the DOAJ.  For the time being we can use my personal bit.ly account for testing, but we'll need you to register an account at some point.  Details are:

1. Sign up: https://bitly.com/a/sign_up
2. Verify your email address
3. Create an application: https://bitly.com/a/create_oauth_app

We may be able to do this for you - IIRC we have a shared mailbox, but I'm not sure of the credentials myself ( @emanuil-tolev probably knows)

**Comment by richard-jones** [comment]
Assigning to @emanuil-tolev for setting up the API key for Bitly

**Comment by dommitchell** [comment]
Please change the position of the Share button. It currently looks like it is associated with the search box.
The button should be at the top right hand corner of the search results, so that the right edge of the  Share button aligns with the right hand side of the search results block shading and should be on the same line as the orange navigation arrow.

**Comment by richard-jones** [comment]
Note to self: assign back to @emanuil-tolev when finished

**Comment by emanuil-tolev** [comment]
This works on https://doaj.cottagelabs.com now.

**Comment by richard-jones** [comment]
Putting the share button in the requested location turns out to be prohibitively difficult* so I've tried something else instead - I've moved it to the left side of the search bar, so that it cannot be confused with a "search" button.

* - the UI components in facetview all have their own bits of screen space in which to be rendered.  The "share" button is part of the search controls component, which renders itself at the top of the page, while the paging buttons are part of the search metadata component, which renders itself above and below the search results.  Putting the "share" button where you want it means putting it in as part of the page metadata component, but that also means it will be rendered top and bottom, which would be strange.  Facetview2 is much more flexible than the original version, but not quite flexible enough to allow that change unfortunately.

**Comment by dommitchell** [comment]
Is this on test? Cannot see any change, despite forcing browser refresh and using browser I've not used before.

**Comment by richard-jones** [comment]
Yup, I can see it.

Click the "share" button on the left side of the search controls at the top, then click "shorten url" when presented with the native "long" url.

**Comment by dommitchell** [comment]
> Putting the share button in the requested location turns out to be prohibitively difficult* so I've tried something else instead - I've moved it to the left side of the search bar, so that it cannot be confused with a "search" button.

I'm still seeing it on the right...
![share](https://cloud.githubusercontent.com/assets/5955396/7019680/e936df0c-dd12-11e4-8215-0b7d41013a0b.jpg)

**Comment by richard-jones** [comment]
Ok, that's really weird - I'm looking at doaj.cottagelabs.com, and it's
certainly on the left.  Shift+Reload?

On 7 April 2015 at 09:43, dommitchell <notifications@github.com> wrote:

> Assigned #51 <https://github.com/DOAJ/doaj/issues/51> to @richard-jones
> <https://github.com/richard-jones>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DOAJ/doaj/issues/51#event-274998367>.
>



-- 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by dommitchell** [comment]
Some questions:

- why does it say share or save? How do you save a search with this feature?
- can we make (shorten url) look more like a button? It looks like a link to help. Maybe move it to the right and change it to [SHORTEN] or have a proper button or make it look more like https://bitly.com/shorten/ ?

**Comment by richard-jones** [comment]
Ok, I've made a couple of changes for the next PR:

* changed the wording to remove save.  The idea was that you could save the link in your favourite social bookmarking tool, I guess.  Anyway, it's gone now!
* Converted the shorten link to a button with an appropriate icon, and messed around with the styles a little.  Hopefully that's clearer.

**Comment by dommitchell** [comment]
Great! Closing.
