### ISSUE TITLE
Chrome scrolling issue (bug in external software)

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#526]
Chrome issue - when you submit a form, it remembers the position of the page you were on (i.e. vertically, where you were exactly). From then on when you open that page it will always scroll to that position. Even if you submit the form again from the top of the page, it will always scroll back down to where you FIRST where. This is some kind of botched usability feature.

This could be a problem (low priority) on all public application, publisher reapplication, admin+editor application and journal forms. I guess more so for the admins and editors.
Consider fix where the page is always focussed on the top if no anchor is present. (We do want the page to focus on the first error or a specific question if that's the link people have followed/entered.)

**Comment by dommitchell** [comment]
Resurfacing this one as I think it is becoming more prominent as more people work on the system. See #730 as well.

**Comment by dommitchell** [comment]
Google Analytics tells me that 54% of all users use Chrome

**Comment by emanuil-tolev** [comment]
OK so we should scroll to anchor (like first error) or scroll to top. Is this a TnM thing? I think the bug label's from before we used the current labels, as I can't see how this is a bug in the DOAJ software.

It would take a few hours (hmm... >2 and up to 1 day roughly), mostly due to being a huge pain to fix as we're working around the browser - it might not be enough to add code to re-focus the page, as the browser's own re-focus could happen after that. So we need some kind of as-of-yet-undetermined method of detecting the wrong scroll, or a sufficient delay. As far as I can see the browser-initiated jump may be happening after window.onLoad, which is the height of silliness.

Weird how the usual problem of having to execute JS *ASAP* is actually turned on its head here.

**Comment by dommitchell** [comment]
Let's discuss at the next meeting.

**Comment by richard-jones** [comment]
I've removed the bug label, as basically this isn't an issue with the DOAJ, it's an issue with how browsers work.  We'd need to put in additional code to force the browsers to behave the way we want them to.

We have another issue #730 which may partially address this problem.

**Comment by richard-jones** [comment]
No movement on this for a year, so closing off
