### ISSUE TITLE
Unable to assign applications without filling in the 2 new questions 14 and 18

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#529]
https://doaj.org/admin/suggestion/678a3a49d78c45bbaa468ed5b22fa000#first_problem

![bug](https://cloud.githubusercontent.com/assets/5955396/5813160/035057c8-a079-11e4-8579-09e58a82d467.jpg)

This needs to be bypassed since no applications between 19th March 2014 and 19th Jan 2015 will have this info provided.

ManEds should be able to assign an application to to a group, and editors should be able to assign an pplication to an AssEd without these answer being filled in.

**Comment by richard-jones** [comment]
I can think of a couple of quick ways that we might do this:

1. allow validation of the application form to be disabled by maneds (in a
similar way to journals)
2. make it so that this field is not required for maneds, but required for
everyone else

Either of these would be about 0.5 days extra work, I'd guess.

We did previously discuss having (1) on the application form, and decided
against it for reasons which I've since forgotten.

(2) would be quite neat (and take advantage of the new form context
back-end code), but then maneds would not have any validation at all on
these fields, even when they start to get populated with data during the
reapplication.

The final alternative is to make a change as to how administrative
properties such as ownership are handled, which might be worthwhile in the
long run, but will be a few days more work, at a guess.

**Comment by dommitchell** [comment]
Unable to reject any old applications either. This is causing us serious problems.

**Comment by emanuil-tolev** [comment]
> but then maneds would not have any validation at all on
> these fields, even when they start to get populated with data during the
> reapplication.

custom validator that does not prevent submission (clears errors from the field) if the current user is a managing editor, but only if the field is empty?

**Comment by richard-jones** [comment]
I've taken the following approach:

* implement a new form which extends from the JournalInfo form
* override the fields that are currently required with fields which are optional
* compose the managing editor and editor forms using this JournalInfo sub-class, rather than the standard JournalInfo

This has the effect that both these fields are optional for managing editors and editors, but still compulsory for the public, publishers (during reapp) and associate editors.

PR made.

@dommitchell - we've done this as a hotfix, so it won't go to testing first, it will go straight into production once the PR has been merged.  Will let you know when it is live and you can check everything is behaving as the admins need.

**Comment by richard-jones** [comment]
@dommitchell - just assigned to you, but you won't be able to review in live for a short while.

**Comment by dommitchell** [comment]
Just acknowledging that I've seen this. Will review later. Thank you for the fast turnaround.

**Comment by richard-jones** [comment]
No probs.  Can confirm this is now live.

**Comment by dommitchell** [comment]
Can you remove the lines 'This field is optional for editors and managing editors only' under 14 and 18 please?

**Comment by emanuil-tolev** [comment]
Got that now too, will say in here when it's been rolled out.

**Comment by emanuil-tolev** [comment]
yep, ready for review on live

**Comment by dommitchell** [comment]
Looking good!
