### ISSUE TITLE
Search should not be sensitive to accented characters

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#54]
The search engine isn't ambivalent to accents on characters and it should be. Compare:

http://www.doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22M%C3%A9todos%20en%20Ecolog%C3%ADa%20y%20Sistem%C3%A1tica%22,%22default_field%22:%22index.title%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22journal%22}}]}}}},%22sort%22:[{%22bibjson.title.exact%22:{%22order%22:%22desc%22}}]}#.Ur3X9PRDsjw

with

http://www.doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22Metodos%20en%20Ecolog%C3%ADa%20y%20Sistem%C3%A1tica%22,%22default_field%22:%22index.title%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22journal%22}}]}}}},%22sort%22:[{%22bibjson.title.exact%22:{%22order%22:%22desc%22}}]}#.Ur3X9PRDsjw

where I changed Métodos to Metodos

**Comment by richard-jones** [comment]
cf #125 - @markmacgillivray assigning to you for analysis

**Comment by markmacgillivray** [comment]
It would be possible to asciifold in the index analyser. Would require a reindex. But then it does not get rid of punctuation etc. As journals are having to resubmit in english this will soon have no effect on journal title searches anyway - english having no accents. 

The alternative for this and for the result ordering punctuation issue is to do stuff to the incoming data in python before storing it in the index. However, storing the originals of every field plus the converted versions of every field will double the size of the index which is very bad for performance and reliability.

But then using the analyzer options, AND storing the originals, will have similar impact.

So in fact I suggest an alternative to both - if a user is typing in accented characters to the search box they should see a message saying they may get more results if they don't use them.

If a user is NOT typing accented characters, however, then they could not be shown such a message. The only alternative here is to asciifold or pre-process. If we are going to do this then we must also choose which fields to search on, rather than all fields, and then I would suggest pre-processing instead of using index analysis.

However my actual recommendation on this would be to leave it as is - searching for a word with or without an accent is a different sort of search for a different sort of thing. If a user is looking for articles in Spanish they would expect to type in Spanish words. If the title may be in English, we are no better placed to know that than the end user - so, if we were to DISABLE the ability for the end user to choose to search for accents or not, then we would degrade their search capability. It should be left to the user to choose to search for these characters or not.

**Comment by richard-jones** [comment]
Preprocess the title in 2 ways:

1/ Without punctuation
2/ Without punctuation and asciifolded

**Comment by markmacgillivray** [comment]
Try searching for "fur". returns some german titles as expected.

**Comment by dommitchell** [comment]
Great! Closing.
