### ISSUE TITLE
A sample XML file?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#56]
We have had a couple of publishers asking us if we have a sample XML file available so that they can create their own and use the XML upload. Can you send me one of the files that a publisher has uploaded so I can generate a sample for them?

**Comment by aqsazaid** [comment]
heloo sir can any one guide me which type of xml is uploaded on DOAJ and do we need specific software for it?

**Comment by dommitchell** [comment]
@aqsazaid please read here: https://doaj.org/features#xml_upload

**Comment by aqsazaid** [comment]
i read this file and a as it is copy from this and generate a xml file but i find this error"File could not be validated against a known schema "

**Comment by dommitchell** [comment]
@aqsazaid there is something fundamentally wrong with your xml file. If you have an email address I can email you a sample file. Send an email to feedback@doaj.org and mark it for my attention (Dom) and I will email you back.

**Comment by aqsazaid** [comment]
hello sir i sent u email.. waiting for your resonse

Date: Tue, 26 Apr 2016 00:54:57 -0700

**Comment by aqsazaid** [comment]
record was uploaded but duplicate example is also updated in current issue ..   to delete two records can u help me

Date: Tue, 26 Apr 2016 00:54:57 -0700

**Comment by aqsazaid** [comment]
any one please

**Comment by dommitchell** [comment]
Please send an email to dom@doaj.org with a **clear** description of what your problem is. Thanks!

**Comment by aqsazaid** [comment]
hello sir,

sir i want to create web API for my publication site, do u have any idea related to it? can u guide me step  by step...or just giving me a road map

**Comment by aqsazaid** [comment]
hello ,


Greeting from mehran university reserach journal i need your help. i have installed ojs 3 and when i am gng to export the xml file through doaj export plugin i am facing many error .


Validation errors:

element decl. 'language', attribute 'type': The QName value '{http://www.doaj.org/schemas/iso_639-2b/1.0}LanguageCodeType' does not resolve to a(n) type definition.

attribute decl. 'language', attribute 'type': The QName value '{http://www.doaj.org/schemas/iso_639-2b/1.0}LanguageCodeType' does not resolve to a(n) simple type definition.

attribute decl. 'language', attribute 'type': The QName value '{http://www.doaj.org/schemas/iso_639-2b/1.0}LanguageCodeType' does not resolve to a(n) simple type definition.

attribute decl. 'language', attribute 'type': The QName value '{http://www.doaj.org/schemas/iso_639-2b/1.0}LanguageCodeType' does not resolve to a(n) simple type definition.
Invalid XML:




i have searched on the internet, some one from the blog write that


"This error was fixed by opening the server firewall to probably communicate with doaj-site. "


can u help me out ? how to resolve this issue? plx reply me as soon as possible kind regards


Aqsa




________________________________
From: software student <engr_aqsa07sw@hotmail.com>
Sent: Thursday, April 28, 2016 1:13 PM
To: DOAJdoaj
Subject: RE: [DOAJ/doaj] A sample XML file? (#56)

record was uploaded but duplicate example is also updated in current issue ..   to delete two records can u help me


________________________________
Date: Tue, 26 Apr 2016 00:54:57 -0700

**Comment by dommitchell** [comment]
Aqsa, please email me your XML file so we can take a look: dom@doaj.org

Thanks Dom
