### ISSUE TITLE
Some links in search should open in new window

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#568]
I'd like advice from a UI perspective on the following.

All links in ALL article and journal views should open in a new tab. For example:

- an article's in search
- links to the full text (not sure what to do about direct links to PDFs?) in search
- any links in search
- any links in ToCs http://doaj.org/toc/7d262e2136824812993dcfa9975e5a7e
- all journal home page URLs
- all links on a journal home page (eg http://doaj.org/toc/9f2bd9ad4c9f4270bf6bf4457b7cf66d)
- the CC license logo.

**Comment by Nimphal** [comment]
From a UX perspective this is generally considered bad practice as it
breaks the flow of information. A link goes somewhere, that's its purpose.
Making it open in a new tab forces a behaviour on the user, disregarding
their desires. I'd advise against.

**Comment by dommitchell** [comment]
Thanks! Does the same apply to search results in general? I mean, to facilitate users coming back to their search results?

**Comment by Nimphal** [comment]
Particularly Facetview search creates a unique link of your search, so even
if a user clicks a links and goes away, they can navigate back to their
original search using the browser back button. I would encourage to leave
the 'open in new tab' behaviour to the user, rather than imposing it on
them.

2015-02-05 9:05 GMT+00:00 dommitchell <notifications@github.com>:
