### ISSUE TITLE
Page doesn't return to top

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#569]
Using the navigation arrow at the bottom of search results takes you to the bottom of the next results. So clicking on http://doaj.org/20 returns you to the bottom of http://doaj.org/30

I'm predominantly using
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

but is an issue in Chrome and IE too as well.

**Comment by richard-jones** [comment]
When we upgrade to fv2, I'll add a scroll-to-the top callback on the prev/next buttons

**Comment by richard-jones** [comment]
I've added a scroll-to-top feature on use of the next/previous buttons now, will be out in the next PR

**Comment by emanuil-tolev** [comment]
Test on https://doaj.cottagelabs.com/search

**Comment by dommitchell** [comment]
This seems clunky. Can't we have it so that when the new page loads, the page starts at the top?

**Comment by emanuil-tolev** [comment]
> This seems clunky. Can't we have it so that when the new page loads, the page starts at the top?

Isn't that what's happening now?


@richard-jones said

> I've added a scroll-to-top feature on use of the next/previous buttons now, will be out in the next PR

So, when you hit "next" or "previous", the page scrolls to the top (and it loads the next set of results too).

**Comment by dommitchell** [comment]
No. Currently, it scrolls you back to the top of the *existing* page and *then* loads the new one.

**Comment by richard-jones** [comment]
When you hit the "next/previous" buttons, the javascript application embedded in the page does the search and then displays the results /without/ taking you to a new web page - so there is no "next page" in the traditional sense.  This is why, in the old version, the page remained at the bottom of the results when you used the pager - the content of the page had changed, but the page itself had not.

The fix I've put in scrolls the page back to the top when the user hits one of those buttons, and I've configured it to do this over the course of 1 second.

I expect that I can just reduce the amount of time that the scroll operation takes, so that to the user it looks like a "new" page.

**Comment by richard-jones** [comment]
Reduced scroll time to 1ms, so it is effectively instant.  Looks ok.

**Comment by dommitchell** [comment]
Great! Closing
