### ISSUE TITLE
searching for text with a forward slash

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#58]
Seems that a query with forward slash in it never returns:
http://www.doaj.org/search?source={%22query%22:{%22query_string%22:{%22query%22:%22M%C3%A9todos%20a/a%22,%22default_operator%22:%22AND%22}}}#.Ur3X9PRDsjw

Probably not many people try that, but it will be mildly annoying to somebody looking up a DOI on DOAJ.. which is what I was doing.

Elasticsearch requires escaping of slashes as of one of the 0.90.x releases, probably query_string needs some escaping.

**Comment by richard-jones** [comment]
Me to check this issue, and close if resolved

**Comment by richard-jones** [comment]
Ok, this bug was very much active, but I believe I've squashed it.

The problem was that the code which escaped query strings for elasticsearch wasn't doing ALL special characters - it was missing quite a few, including "/".  It also never attempted to unescape query strings coming in via the URL bar.

The fix I've put in escapes almost all es special chars (except * and "), and also checks that " comes in pairs (if they do not, they get escaped too).  This means users can issue "exact match" queries and wildcard queries, but not any other complicated boolean stuff.

Then, when queries are received via the URL, they go through an exact mirror unescape procedure which puts the query string back the way it was.

**Comment by dommitchell** [comment]
Carried out a search on a DOI:
https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%2210.15503\\%2Fjecs20132\\-124\\-133%22%2C%22default_field%22%3A%22bibjson.identifier.id%22%2C%22default_operator%22%3A%22AND%22}}%2C%22from%22%3A0%2C%22size%22%3A10}

and 1 result successfully returned.

Anything else I can/should text here?

**Comment by emanuil-tolev** [comment]
Previously you literally couldn't search for anything with a /, so this seems reasonable enough. I can't think of what else to test here.

**Comment by dommitchell** [comment]
I have found one rather ugly example that is still broken:
http://bit.ly/1EUrq0z

where the publisher has used // to denote a language change. Can we account for that too, because the link generated from the publisher facet truncates at the // and returns no results.

(Note to self, this is a new publisher. We should ask them to reupload with no // in their article metadata)

**Comment by richard-jones** [comment]
Can you give me the full link to the test server?  The link doesn't work on the live server yet, because of the special character issues.

It sounds, from your description, that this is a separate issue - this issue deals with when the user puts a "/" in the search box.  If there is broken data in one of the fields, we may need to look at that as a separate task/part of the data cleanup.

**Comment by dommitchell** [comment]
https://doaj.org/admin/admin_site_search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22%D0%9E%D0%9E%D0%9E%20%D0%98%D0%B7%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9%20%D0%B4%D0%BE%D0%BC%20\%22%D0%92%D0%B8%D0%B4%D0%B0%D1%80-%D0%9C\%22%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22admin.in_doaj%22:%22T%22}}]}}}}}

**Comment by richard-jones** [comment]
The quote mark in the publisher name is breaking the Publisher facet - general fix required

**Comment by richard-jones** [comment]
I've done a review of the whole of fv2 for places where html escaping is required and implemented it.  All seems to be working fine now.  Will be ready for review at next PR.

**Comment by dommitchell** [comment]
Not fixed. 
https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}]}}%2C%22query%22%3A{%22match_all%22%3A{}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

Open publishers facet, change sorting to a-->z, clicking "Petru Maior" University Publishing House (186) returns no results

**Comment by richard-jones** [comment]
http://doaj.cottagelabs.com/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%2C%7B%22term%22%3A%7B%22index.publisher.exact%22%3A%22%5C%22Petru%20Maior%5C%22%20University%20Publishing%20House%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

That search works for me.  

Wouldn't have thought that was a browser issue, as the data is now being html escaped to prevent the issue, but let me know which browser you're using and it might be worth a check.

**Comment by dommitchell** [comment]
https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22index.publisher.exact%22%3A%22%22}}]}}%2C%22query%22%3A{%22match_all%22%3A{}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

![petru](https://cloud.githubusercontent.com/assets/5955396/7019720/48292024-dd13-11e4-9142-3288aec06c94.jpg)

**Comment by richard-jones** [comment]
Could you have another go at this, and see if it works now we've updated the code.

The link above is still broken, but that's to be expected - need to try navigating to the result from scratch again.

**Comment by dommitchell** [comment]
Fixed!
