### ISSUE TITLE
New/updated layout required in public Journal "long view"

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#585]
FINAL VERSION

![long_view](https://cloud.githubusercontent.com/assets/5955396/6636417/530b6242-c970-11e4-8fdc-1402b07fc5d9.jpg)

**Comment by richard-jones** [comment]
see also #145 and #454

**Comment by dommitchell** [comment]
@richard-jones @markmacgillivray Sorry. I am behind on this. Will upload a finalised mock-up first thing tomorrow. Here are my thoughts in the meantime. Let me know if you hear alarm bells.

![journal_long_view_draft](https://cloud.githubusercontent.com/assets/5955396/6600430/d4d34f5e-c80f-11e4-8a78-bf3be6fc961d.jpg)

**Comment by Steven-Eardley** [comment]
It has occurred to me that changes here will affect my article page design too.

**Comment by dommitchell** [comment]
Note to self: I need to think about pushing article content down the page. No show/reveal in this mock-up

**Comment by dommitchell** [comment]
General question: how will this display work for those journals that do not have the new data set?

**Comment by richard-jones** [comment]
I've done a first implementation of this which is ready for review (when PR is merged).  The only caveat is that country names are not yet expanded - this relies on some other code in another branch, and when all of it is merged we can revisit.

In answer to your question: the display will just degrade to represent whatever data is available in a given journal - if the data is missing, mention of it is entirely omitted.

**Comment by dommitchell** [comment]
Feedback:
- [ ] remove // from between ISSNs. They are not needed.
- [ ] add a line for former title and ISSN(s) if present, to be displayed under the ISSN(s).
- [ ] change 'Journal Homepage' to 'Homepage' and make open in a new window.
- [ ] make the labels in the two boxes bold (Publisher, Society etc) to differentiate them from the answers

- [ ] Add a content range or date range for journals with continuations, next to the appropriate ISSN(s), although this might change once I've seen the treatment in #145

**Comment by richard-jones** [comment]
I've made the main display changes listed above, but again have left the "open in a new window" link until after the next meeting.

I have also now expanded languages, countries and subject classifications in the same way as they are in the search interface.

The issues around continuations are partially completed.  I have made major additions to the journal model object to allow us to better interact with the continuations, and have modified the way that the toc page renders, so that it is capable of rendering /any/ bibjson, and links to previous and subsequent versions of the journal.  It still only works on the main journal, though, so @markmacgillivray and I need to put our heads together this week just to finish off how these pages will work.

I'm not sure what the final point means, though:

> Add a content range or date range for journals with continuations, next to the appropriate ISSN(s), 
> although this might change once I've seen the treatment in #145

Propose that we don't do anything about this until we've finished the treatment of continuations as we currently understand it, and then we can revisit.

**Comment by richard-jones** [comment]
Note that the links to continuations don't currently do anything

**Comment by dommitchell** [comment]
Just one thing: close up the space between (Print) and the ;

2071-257X (Print); 2311-6072 (Online) 

> Add a content range or date range for journals with continuations, next to the appropriate ISSN(s),
>     although this might change once I've seen the treatment in #145
> 
> Propose that we don't do anything about this until we've finished the treatment of continuations as we currently understand it, and then we can revisit.

OK, actually we can forget this.

**Comment by richard-jones** [comment]
Done in next PR

**Comment by dommitchell** [comment]
Great! Closing.

**Comment by dommitchell** [comment]
We're going to have to add the date added to DOAJ. Omitting this was an oversight on my part.

Please add in 'Date added to DOAJ:' in bold under Platform/Host/Aggregator:

**Comment by richard-jones** [comment]
Added for next PR

**Comment by dommitchell** [comment]
In and looking good
