### ISSUE TITLE
Generate reapplication records

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#590]
Please generate a reapplication for:
- [x] 2316-9834 ID: 632e1560c93f4efca995ba1cae489f0e
- [x] 0718-4654 ID: 838c2a593bd446faa62be0b6a0a81b14
- [x] 1280-9551 ID: 07431fb3126242bcafd007840cab3087
- [x] 1404-4013 ID: 526e77f7f6414acab743bf641ffeb920

**Comment by richard-jones** [comment]
Did this account/journal not get its reapplications generated when we initialised it?

**Comment by richard-jones** [comment]
It's possible that it was in_doaj=False when the reapplication started, in which case it wouldn't not have got one.  Is that what happened?

**Comment by dommitchell** [comment]
> Did this account/journal not get its reapplications generated when we initialised it?

The journal had been mistakenly removed from DOAJ. Any journals that are put back into DOAJ do not automatically get a reapplication.

**Comment by dommitchell** [comment]
Adding another one

**Comment by richard-jones** [comment]
I've now checked each one of these journals out to ensure that we're safe to regenerate the reapplications, with the following results:

* 2316-9834 - in doaj, owner has 9 other journals so a CSV will /not/ be generated.  Good to initialise.
* 0718-4654 - NOT in doaj, owner does not have any other journals, so a CSV will /not/ be generated.  Cannot initialise reapplication until journal is placed back in doaj.
* 1280-9551 - in doaj, owner has 3 other journals so a CSV will /not/ be generated.  Good to initialise.

@dommitchell - assigning to you to decide what you want to do about 0718-4654, then could you comment and assign to @emanuil-tolev for action.

@emanuil-tolev - in order to action these reapp initialisations, you'll need to run the following commands on the live server when @dommitchell gives the go-ahead.

2316-9834:
    python portality/migrate/reapplication/reapp_init.py -j 632e1560c93f4efca995ba1cae489f0e

0718-4654 (pending resolution):
    python portality/migrate/reapplication/reapp_init.py -j 838c2a593bd446faa62be0b6a0a81b14

1280-9551:
    python portality/migrate/reapplication/reapp_init.py -j 07431fb3126242bcafd007840cab3087

**Comment by dommitchell** [comment]
Thank you! 0718-4654 is now back in DOAJ.

On hold for now. @richard-jones I suspect there will be now and I suppose it will be better to do them all at once?

**Comment by dommitchell** [comment]
Note from call: OK to go ahead. Please run these now.

**Comment by richard-jones** [comment]
@emanuil-tolev - have these been done, can we close this issue off?

**Comment by richard-jones** [comment]
@emanuil-tolev - ping

**Comment by emanuil-tolev** [comment]
OK, the 3 reapplications mentioned in https://github.com/DOAJ/doaj/issues/590#issuecomment-115298680 have been run. I noticed there's an additional one in the original post, perhaps added later by editing, which is not mentioned anywhere in this issue:

> 1404-4013 ID: 526e77f7f6414acab743bf641ffeb920

I have not rerun the reapplication for this as I can see you guys discussed whether each of these should in fact be regenerated, so I'm not sure if 1404-4013 also needs to be double-checked in a similar manner.

For the other 3, feel free to check if everything is ok and poke me if not.

**Comment by dommitchell** [comment]
Thanks @emanuil-tolev . Please do run the 4th.

**Comment by emanuil-tolev** [comment]
OK, that has been run for 526e77f7f6414acab743bf641ffeb920. Feel free to double check it and close if this solves it.

**Comment by dommitchell** [comment]
All good!
