### ISSUE TITLE
" " in the csv file

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#606]
A comment in #58 about making sure that " came in pairs reminded me of a question that came up re the csv file. Some publisher names have "" around them which was apparently breaking the CSV formatting, which uses "" as delimiters. https://doaj.cottagelabs.com/csv

Will changes in the PVOD project help this in any way?
Can we do anything to strip out "" in publisher names?

**Comment by richard-jones** [comment]
" marks around a publisher name shouldn't break the csv - are there issues with it at the moment?  The csv writer will escape these characters where appropriate, so they come through the other side correctly.

Otherwise, the PVOD project won't be doing anything about quote marks in publisher names - that would probably be a data cleanup exercise, perhaps with some new data ingest/crosswalk rules.  Though whether the publisher has quotes around all/part of the name might also be an editorial decision.

**Comment by dommitchell** [comment]
Yes, we had a bug reported by a user where "" around the name were causing a break. I wonder if it could be the difference between "" and “ “. Possible?

**Comment by emanuil-tolev** [comment]
This is properly escaped. See http://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv .

```"Samsung U600 24"""``` translates to ```Samsung U600 24"```.

The actual publisher name has quotes in it, which means that the publisher (in human language) really is ```Grupo de Investigación "La Imagen Medieval, Espacio, Forma y Contenido"```. So there are no delimiters missing, the two double quotes ("""") should be translated by your CSV reader to a single " for display.

**Comment by emanuil-tolev** [comment]
And the CSV form of that publisher name is ```"Universidad Complutense de Madrid, Grupo de Investigación ""La Imagen Medieval, Espacio, Forma y Contenido"""``` which is what we've got in our CSV output :).

If there is third-party library this user can peruse (in their programming lang) to parse the CSV, that's best. These kinds of corner cases are usually taken care of by language core CSV libraries, but not if a more homebrew importer is written.
