### ISSUE TITLE
UI of facets

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#618]
I just wanted to ask a question about the new look facets. I couldn't find the correct task in GitHub so sorry for the email.

In the new display, the selected facet is tagged onto the parent and then displayed at the top of the search results:

![facet](https://cloud.githubusercontent.com/assets/5955396/6785792/2856805c-d188-11e4-9f11-c93c1f5cd3d7.jpg)

​The 'stem' of that fact above is actually clickable and produces the URL https://doaj.cottagelabs.com/_type but doesn't actually do anything. Under its current treatment it looks like it should do something.

Also; I'm not sure that by adding this to the top of the search results, it actually lends anything to search interface. Actually, it makes it more confusing. What's the theory behind it that UI? Is it to make it easier to know which one to remove when you have multiple ones clicked?

https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22journal%22}}%2C{%22term%22%3A{%22index.country.exact%22%3A%22Iran%2C%20Islamic%20Republic%20of%22}}%2C{%22term%22%3A{%22index.publisher.exact%22%3A%22Mashhad%20University%20of%20Medical%20Sciences%22}}%2C{%22term%22%3A{%22index.language.exact%22%3A%22Persian%22}}%2C{%22range%22%3A{%22created_date%22%3A{%22gte%22%3A%221356998400000%22}}}%2C{%22term%22%3A{%22index.classification.exact%22%3A%22Medical%20physics.%20Medical%20radiology.%20Nuclear%20medicine%22}}]}}%2C%22query%22%3A{%22match_all%22%3A{}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

Can we change the UI of the stem very easily? ie make them unclickable and maybe a different colour?

Thoughts?

**Comment by richard-jones** [comment]
Yeah, we've also wondered about the presentation of this.

Essentially, the non-clickable parts are styled that way so that the filter definition is consistently styled.  We could make it plain text, with an X next to the term to remove it (like in the facets themselves), which would give us consistent styling without the confusing buttons.

The alternative is to remove the filter definitions along the top altogether and rely on the facets on the left to tell the user what their filters are.

The "theory" (if could be called something so sophisticated!) is that when the user lands on the page from an external link, these filters up the top make it immediately apparent what the active search criteria are - expecting them to look at and understand the facets would probably be too much.

The current UI uses this same approach, but it doesn't tell the user what field the filters are applied to, which I've always found a bit unsatisfying, hence this upgrade in the new UI.

If you just let me know what you'd actually like it to look like, we can change it.

**Comment by dommitchell** [comment]
I think that they definitely have a use, especially if you look at the example above. One might want to deselect something and it's very helpful to see that Persian relates to language of the full text, for example.

Would this work?
- make the facet category and the facet all one block, no divide, same colour (the lighter orange) and no hyperlink
- add a colon between the facet category and the facet
- add a divide between the X and the rest of the label

so it looks like:

( Country of publisher: Iran, Islamic Republic of | x )

Thoughts?

**Comment by richard-jones** [comment]
Yes, we could do something like that, though we also need to take into account that the filter might look like (for example):

Country of publisher: Iran, Islamic Republic of | x OR England | x

would that make sense too?  Each filter can theoretically have multiple values, so the UI needs to support that.

**Comment by dommitchell** [comment]
Yes, this is good. Go ahead.

**Comment by richard-jones** [comment]
Ok, I've made this change for the next UI Tweaks PR

**Comment by dommitchell** [comment]
Looking good, closing
