### ISSUE TITLE
XML: list of what's required, what isn't, what attributes must be present, rules

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#631]
Today we queried whether two field were needed in the XML. You consulted the XSD file and checked to see if any crosswalk was done on them. It would be very helpful for me to get a complete set of rules for the XML so I can publish something on the web site to help publishers. 

Can you get me one?

**Comment by richard-jones** [comment]
XSD can be accessed here: https://doaj.org/static/doaj/doajArticles.xsd

Otherwise, in summary, the rules are:

0-1 language, iso code
0-1 publisher
1 journal title
0-1 issn
0-1 eissn
1 publication date
0-1 vol
0-1 issue
0-1 start page
0-1 end page
0-1 doi
0-1 document type
1-* title
0-* authors
0-* affiliations
0-* abstracts
1 fulltext url
0-* keywords

**Comment by dommitchell** [comment]
What is the difference between these:

0-1
1
1-*
0-*

Thanks!

**Comment by Steven-Eardley** [comment]
I understand it as 

0-1     is 0 or 1 of these things (optional, but max. 1)
1        1 only (i.e. required)
1-*     1 or more (so required and may be more than one)
0-*     0 or more (so fully optional)

**Comment by richard-jones** [comment]
Yup, what Steve said :)  Sorry. should have added dox on the notation!

**Comment by dommitchell** [comment]
@richard-jones Was this information included in the XML info you released onto the site? I don't see it here: https://doaj.org/features or here: https://doaj.org/publishers and it was supposed to be part of #984

**Comment by dommitchell** [comment]
This when you can. You said it would be easy to drop this stuff in.
