### ISSUE TITLE
Introduce read-only mode for application

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#648]
Needs to do the following:

* in login_required decorator, if app.config.READ_ONLY, serve a "read only" page
* for application form route, do the same
* all scripts that make data changes should also check this
* site statistics generation

**Comment by richard-jones** [comment]
I've added a write_required decorator, which I've applied to all the relevant routes.  login_required is a flask decorator, so I couldn't modify it directly.  Also, though, with a specific decorator for writes, we can keep some of the admin area functional while at the same time using the same decorator to disable the application form.

**Comment by richard-jones** [comment]
I've also added a check in initialise_index, and put checks in the DAO so that any requests to methods which write to the index are blocked.

**Comment by richard-jones** [comment]
@emanuil-tolev has created a hotfix against master for this too, so we will be able to turn the current production version to read-only mode too when we do the upgrade

**Comment by emanuil-tolev** [comment]
Reviewed on test server, seems to work well.

Code deployed to live now. All we need to do is flip the config and restart the app, and it should go in read-only mode. I need to go into a bit more detail during our Mon meeting as to when the best time for this will be, as I think it's probably best if it happens the eve before the deploy.

So:
0. perform code release from develop to production (5-10 min) without deploying it, obviously
1. turn on readonly mode in the evening (8-9pm UK time)
2. stop all regular jobs and the backups
3. initiate a data backup (45min)
4. download the backup to new infrastructure (15 min)
5. decompress the backup (15 min)
6. restore the backup to the new infrastructure (2h 15min)
7. delete /toc
8. in one single command, let migration scripts run overnight (3h+?) and let the index be optimized by Elasticsearch (reduce size from 33GiB to 15GiB, takes 4-6 more hours!) - this consolidates it after the initial bulk restore and the migrations and we proceed with a relatively clean/fast/small slate.

Everything will have a separate log of course, and the next command will only proceed if the previous was successful.

Then in the morning, we should be ready to roll. Actual switchover may happen in the afternoon due to other factors - we'll talk those things over in the meeting.

But considering the data tasks take so long, it might be best to do readonly mode overnight.

**Comment by richard-jones** [comment]
@richard-jones needs to separate the READ_ONLY mode between UI and scripts, so scripts can still run while the UI is still in read only.

**Comment by richard-jones** [comment]
@emanuil-tolev can you cherry pick this commit for the production branch: https://github.com/DOAJ/doaj/commit/ae2fe8c3095fb1c9e9a424a0c4da79e677fc995e

**Comment by emanuil-tolev** [comment]
> @emanuil-tolev can you cherry pick this commit for the production branch: ae2fe8c

Yes, but will have to first merge the whole branch into develop. Otherwise have commit in production and not develop. Technically possible but better not. But yes, will do soon as I review your PVOD review PR!

**Comment by emanuil-tolev** [comment]
> @emanuil-tolev can you cherry pick this commit for the production branch: ae2fe8c

done and released to live
