### ISSUE TITLE
OpenURL error page

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#652]
Saw that this page is produced when OpenURL fails

![openurl_error](https://cloud.githubusercontent.com/assets/5955396/7113260/3decefd2-e1d2-11e4-9c03-cb03f7d4a091.jpg)

e.g. https://doaj.cottagelabs.com/openurl?rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.spage=41&rft.issue=2&rft.volume=4&rft.date=2010&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004&rft.issn=19909128&rft.genre=article

Is this message entirely correct? "Check the parameters or try reducing search constraints." doesn't apply to OpenURL does it?

**Comment by Steven-Eardley** [comment]
I suppose it pertains more to our implementation that OpenURL's philosophy - from our perspective it's a search because we run it through an ElasticSearch query, so if you've over-specified the metadata it might help if you remove some. E.g. if you are finding the resource with ISSN and alternative title, but the alternative title isn't in our index. 

From an OpenURL perspective, a URL is meant to reach a resource and there's no specific manner in which it must happen. It's not a search; it's fetching a resource. There'll be a better way of phrasing the message, for sure.

However, the user's best action for a chance of finding something is still to discard parameters from the URL - I'm not sure we can categorically say it's not there due to the uncertainty of a ranked search.

**Comment by dommitchell** [comment]
@Steven-Eardley Yes, I see. I htink we can just delete "Check the parameters or try reducing search constraints." because the page then goes on to say do a search which I think is the correct process.

Sound good?

**Comment by Steven-Eardley** [comment]
Yup, I'll take that out as I'm writing my documentation.

**Comment by Steven-Eardley** [comment]
My changes are visible on the test server; here's a bogus url to see the page.
http://testdoaj.cottagelabs.com/openurl?rft.issn=invalid_issn

**Comment by dommitchell** [comment]
Looking good!
