### ISSUE TITLE
Accepted reapplications are inheriting a 'Rejected' status once they've been accepted

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#655]
E.G. https://doaj.org/editor/suggestion/017fd746386c4694af267afac567555e has the status Accepted in search results: https://doaj.org/editor/group_applications?source={%22query%22:{%22match_all%22:{}}} 

![acc1](https://cloud.githubusercontent.com/assets/5955396/7137455/08358d0c-e2ba-11e4-87c4-1dc7fa75b0ae.jpg)

but the status Rejected when you open the record.

![acc2](https://cloud.githubusercontent.com/assets/5955396/7137459/1051ebde-e2ba-11e4-88ea-0903ec2a3d44.jpg)

**Comment by emanuil-tolev** [comment]
But it has "Accepted" when you view it as admin: https://doaj.org/admin/suggestion/017fd746386c4694af267afac567555e

This is probably a browser thing where it will assign the nearest choice when the selected choice isn't available. It's not really rejected, it's just that that's what the browser picks since "Accepted" isn't available for editors to assign ..... or see, as a result of the fact it's not available for them to assign.

Not sure to be honest, we can add the "Accepted" choice back in but specify "Accepted (man.ed. only)" as the text? Or remove the design affordance (a dropdown menu invites selecting something, but really an editor can't select anything - they can't move an application off the "Accepted" status, so it's misleading to let them think they can in UX design terms) - when you can't make that choice, replace the dropdown with a text label?

This is just some brainstorming of what a solution might even look like, I'll readily admit I've not looked into how hard or time-consuming either of these are.

**Comment by dommitchell** [comment]
I see. Closing for now as this will never affect editors who will rarely open their old applications.
