### ISSUE TITLE
Journal home page returns 400 Bad Request error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#687]
https://doaj.org/toc/1751-7192

**Comment by richard-jones** [comment]
This is an interesting one - there is more than one journal in the index with this ISSN, one in_doaj=True and the other in_doaj=False.

SInce the ToC doesn't appear to restrict by in_doaj, then it doesn't know what to do, so it throws this error.

Probably the fix is to restrict toc to in_doaj=True, which will eliminate this problem.  If we ever wind up with 2 journals with the same issn in_doaj=True, though, the problem will reappear, but that will be a data error rather than a code problem as such.

**Comment by richard-jones** [comment]
In forthcoming hotfix

**Comment by richard-jones** [comment]
Fixed on live

**Comment by dommitchell** [comment]
One more which doesn't seem to have any duplicates: https://doaj.org/toc/1646-9895

**Comment by emanuil-tolev** [comment]
This is not a 400 Bad Request (which is what happens on duplicates), it's a 404 Not Found. You're getting the Not Found because this journal is not "in DOAJ". Hit "Put journal in DOAJ" at https://doaj.org/admin/journal/86f3b575e5924014909dc58ab2cc7f2c to fix, if applicable :).

On a related note, the journal is neither in nor out of doaj (admin.in_doaj simply is not present). There are 3 journals like that, I believe we discussed this elsewhere. The other two are https://doaj.org/admin/journal/b356da3a55ab414ca7d3a755b516ce88 and https://doaj.org/admin/journal/1b4f5507c768494ea17c5cdcb4fe9099 . I would recommend reviewing them and doing one of:

1. if they need to be in DOAJ: putting them in - hit the Put in DOAJ button
2. if they need to NOT be in DOAJ: put them in by hitting the Put in DOAJ button, then take them out immediately afterwards by hitting the now-red Take out of DOAJ button. This will ensure that the journals are clearly labelled (rather than the data simply missing) and they will show up properly in admin facetviews (right now they wouldn't be counted in the In DOAJ? facets).

**Comment by dommitchell** [comment]
@emanuil-tolev thank you! Closing because this is indeed in another task.
