### ISSUE TITLE
Unanswered fields show as 'No' on journal homepage

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#688]
I'd like to explore the possibility of suppressing 3 fields of a journal record for all journals that have now reapplied.

Now the new data has gone live, all journals that haven't reapplied show incorrect information:

Article Processing Charges (APCs): No.
Submission Charges: No.
Waiver policy for charges? No. 

which is incorrect. Can we suppress the 'No' until the journal has successfully reapplied?

**Comment by richard-jones** [comment]
hotfix and PR made

**Comment by dommitchell** [comment]
Not sure this has quite worked as expected. https://doaj.org/admin/journal/086cff769b9f4c12b4a2bfbd175efcae has replied with 'No' but their ToC says: Information on publication charges not yet available for this journal
Maybe this isn't live on the site yet?

**Comment by richard-jones** [comment]
This is quite weird - that journal does not have a value for last_reapplication, which is what the code uses to determine whether to show the information.

Can you give me some other examples of journals that have been through the reapplication?

And can you give me an outline of what has happened to this particular journal since the reapplication was approved (i.e. has it been edited by anyone, etc).

**Comment by dommitchell** [comment]
Any journal that has been accepted recently, whether it has APCs or not: http://bit.ly/1IPWhtD. In particular https://doaj.org/toc/2052-5397 which shows APCs in search results but not on the ToC.

**Comment by richard-jones** [comment]
For reference, there are ones that are working, for example: https://doaj.org/toc/1687-8884

**Comment by richard-jones** [comment]
@dommitchell - I think I might know what's happening, but can you just clarify for me.

2052-5397 has a created_date of 2015-05-04T13:25:23Z and a last_updated date of 2015-05-04T13:25:23Z and no last_reapplication date- this would suggest that it's a new journal rather than a reapplication of an existing journal.  Can you confirm?

The current rule looks for the last_reapplication date, which in retrospect is a mistake, because that does mean that new journals get this "information missing" error - they are not reapplications so they do not have the last_reapplication date.  Perhaps the better test would be whether the journal is ticked or not?  All journals submitted since last March should have the correct APC data, right?

Anyway, let me know if that makes sense, as if not I'll have to dig deeper in case there is a bug with last_reapplication dates.

**Comment by dommitchell** [comment]
> 2052-5397 has a created_date of 2015-05-04T13:25:23Z and a last_updated date of 2015-05-04T13:25:23Z and no last_reapplication date- this would suggest that it's a new journal rather than a reapplication of an existing journal. Can you confirm?

I can only confirm by checking Notes and the Date added but it does look like a new application rather than a reapp.

So yes, I think the rule needs to look for records that have a 'Date Added to DOAJ' date of pre-March 2014, no? It's those records that we want to apply this message too because they have the old Y/N APC info which doesn't show up in our post-PVOD upgrade. As a last_reapplication date is applied, that message should disappear and the new data be shown.

Make sense?

**Comment by dommitchell** [comment]
Yes, looking good. Follow up question:

- is there anyway we can adjust the facet display so it shows that ~9120 journals actually have 'No info'?

**Comment by richard-jones** [comment]
This final request is closely related to #343 

I'm going to close this issue off and add that requirement to the other issue, and put them both through on tnm.
