### ISSUE TITLE
Preserver Last Updated date for future upgrades

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#689]
Every time a new project is released on the site, the Last Updated date across all the records gets wiped. In the absence of provenance tracking, we rely on this date to keep track of our workflow.

Is there a way to preserve this date and stop it being wiped at future updates.

**Comment by emanuil-tolev** [comment]
@dommitchell not quite - the transfer from server to server (in case that is necessary at all) does NOT wipe this field. To the machines it's simply data, just like a journal's title, they don't understand the Last Updated field as a special field that should be updated - and so, they will leave the value alone.

What does change it, is migration scripts which change the structure of each record. For this project, we have a script which goes through every article, journal and suggestion, changing their structure to achieve what the user interface needs ( @richard-jones can provide more specifics ). We have had such scripts in the past few projects.

Now, those records *have* changed on that date by a script. It'd be much worse provenance to not record *that* fact. What we need is perhaps a field telling us when the last human intervention on a record was performed. This could be a bit thorny to implement (simply because you have to now make a distinction between human and automated change) but if that's what's needed, we should discuss it.

**Comment by richard-jones** [comment]
Yes, basically what @emanuil-tolev said.  The records /have/ been updated, so the update to the last_updated date is correct - we often, when we roll out a new version, have to run migration on the data so this will often happen at these points.

Unfortunately, the only way to do something about this which is meaningful is to introduce some form of provenance tracking.  That could be something such as Emanuil suggests, separating "human" last_updated from the low-level last_updated, through to a full record of who did what when in perpetuity.

**Comment by dommitchell** [comment]
Yep, we need to make sure this the human updated date remains untouched. Can someone create a 'provenance' label so I can add this to it?

**Comment by Steven-Eardley** [comment]
This issue was superseded by #811. Closing.
