### ISSUE TITLE
Was this record an application or a reapplication?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#715]
https://doaj.org/admin/suggestion/5752e15b3f954f7e91c114abad213240

Can you tell?

**Comment by dommitchell** [comment]
We think it was a reapplication, which begs the question: why did the existing record not get rejected when the reapplication was rejected? 

https://doaj.org/admin/journals?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%222320\\-088X%22%2C%22default_operator%22%3A%22AND%22}}%2C%22from%22%3A0%2C%22size%22%3A10}

**Comment by emanuil-tolev** [comment]
It seems to be a reapplication, this was in the record:

```current_journal: "ad67d58fb89f4df5a52e9300dbbc844d"```

Good question. Is rejecting the reapplication supposed to withdraw the journal? Presumably people can reapply again to provide more info, not sure that you would have wanted to automatically withdraw the journal in DOAJ. Trying to think quite hard of discussing automatically pulling journals from DOAJ based on application / reapplication decisions but I can't remember that you wanted anything like this to happen, and can't find it in github issues. It doesn't seem that straightforward a decision either (see point about potential multiple reapplications) - you sure you want journals pulled automatically on reapplication rejection?

If the reapplication is specious and you really don't want to deal with that journal anymore (a strange scenario - why is it in DOAJ now in that case? what happened, did its leadership team get replaced by space lizards?), simply pull it from DOAJ via its admin page.

**Comment by dommitchell** [comment]
Hmm, I was certain that rejecting a reapplication updates the journal record (i.e. withdraws it), just as accepting a reapplication updates the existing journal record. That's the whole reason why we can't accept new applications in the place of an existing reapplication record.

@richard-jones I am remembering correctly, right?

**Comment by greboun** [comment]
Is it not so , that in the case of a rejected re application the old
records should remain available in the database?
I don't think that the journal should be automatically removed from DOAJ.
Or am I missing something

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by emanuil-tolev** [comment]
> Is it not so , that in the case of a rejected re application the old
> records should remain available in the database?

The records are available, but the in_doaj flag gets set to False. The data is not removed, but the journal is no longer visible in the public user interfaces (like the /search page, OAI-PMH, the table of contents pages etc.).

**Comment by dommitchell** [comment]
Yep that is how it should work so I wonder why it didn't happen this time? We'll wait for RJ to wade in.

**Comment by richard-jones** [comment]
There's no code that I'm aware of in the system that does anything to an existing journal when a reapplication is rejected.  Current journals are /only/ modified when a Managing Editor sets the status of a re-application to "accepted":

https://github.com/DOAJ/doaj/blob/develop/portality/formcontext/formcontext.py#L537
and then
https://github.com/DOAJ/doaj/blob/develop/portality/models/suggestion.py#L35

@emanuil-tolev - where did you see something that suggests that in_doaj would be set to False in this case?

I don't recall any discussion on having reapplications cause their related journal to be withdrawn, I'm afraid - it's not in my notes or in any of the issues that I can find, which would be why it doesn't work!

**Comment by emanuil-tolev** [comment]
> @emanuil-tolev - where did you see something that suggests that in_doaj would be set to False in this case?

I don't, I thought you or @dommitchell might remember :). I'm pretty sure we've not discussed this as well, otherwise I would remember plenty of detail points (e.g. see my questions in https://github.com/DOAJ/doaj/issues/715#issuecomment-101655014 ).

The most poignant question for me remains:

> If the reapplication is specious and you really don't want to deal with that journal anymore (a strange scenario - why is it in DOAJ now in that case?), simply pull it from DOAJ via its admin page.

Think about it:

1. the journal is in DOAJ
2. the reapplication is spam - how could that happen? Presumably if it's in DOAJ now it should be a *relatively* well-behaved journal?
3. If it the journal is not behaving itself, let's just remove it from DOAJ, using the red button on its admin page. Presumably there shouldn't be tons of journals which *were* in DOAJ but whose **first** reapplications we want to reject PLUS withdraw the journals (on the **first** rejected reapplication).

If you do find you are taking lots of journals out without giving them a chance at 2nd reapplication, then we should consider adding this behaviour.

**Comment by emanuil-tolev** [comment]
add to questions next meeting definitely :)

**Comment by dommitchell** [comment]
I found evidence from Notes that DOAJ must remove the journal manually when rejecting a reapplication.

This has its own problems: there is no way to identify a reapplication from an application once it is absorbed into the main workflow. What can we do about that?

Can we develop something so rejected reapplications automatically reject the journal record?

**Comment by greboun** [comment]
If a reapplication is rejected , and the in_doaj flag is set to no, you
cannot search record via the user interface any more, right?
But I can imagine that when a reapplication is rejected the journals has
changed for the worst, old records could still be useful for the scientific
community.
If the reapplication is rejected because the first application only passed
just because of fewer and less stringent criteria, than it could be OK to
remove the old records.
When we use the admin button to remove a journal, are all the journal
records removed, or is it just the flag in_doaj set to No?



Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by emanuil-tolev** [comment]
> If a reapplication is rejected , and the in_doaj flag is set to no, you
> cannot search record via the user interface any more, right?

To be precise, you cannot reach these records via the **public** interface. You can still see them in the **admin** part of the site, obviously.

> When we use the admin button to remove a journal, are all the journal
> records removed, or is it just the flag in_doaj set to No?

The flag is just set to no, for the journal and all its articles.

**Comment by dommitchell** [comment]
Closing.
