### ISSUE TITLE
PDF URLs redirect to publisher homepage

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#720]
A bug maybe?

Something odd happening here: https://doaj.org/toc/2308-2399/1/1

All URLs on DOAJ redirect to the publisher's homepage: http://www.samanmjournals.org/ and yet work on the publisher's site.

URL on DOAJ and publisher's site are identical:
http://www.samanmjournals.org/wp-content/uploads/ARE-CELLULAR-AND-LANDLINE-SUBSITUTES-OR-COMPLEMENTS1.pdf
http://www.samanmjournals.org/wp-content/uploads/ARE-CELLULAR-AND-LANDLINE-SUBSITUTES-OR-COMPLEMENTS1.pdf

**Comment by emanuil-tolev** [comment]
This is definitely not a bug in the DOAJ system. We can only go as far as generate the correct link. What they and their server does is a different matter.

It is possible to restrict PDF-s (more conventionally this has in fact been done to **images**) so that you can only download them if you're coming from the same website they're hosted on. This is called hotlinking protection.

I see that this is a wordpress site. Wordpress isn't particularly famous for disabling hotlinking, so perhaps they're (knowingly or unknowingly) using a plugin which has disabled hotlinking.

Let me illustrate - this is the link to their logo: http://www.samanmjournals.org/wp-content/uploads/bs-final.jpg

Modern browsers may fake the referrer information to allow you to still see the image (if you've been to that website before). For example, I opened that image link in Firefox and it redirected me to the homepage, but every time afterwards, it actually showed me the image :)! But if I try to fetch that link with a command-line tool that's not so clever, I get redirected to their homepage - I can't download their logo. 

(New things to learn every day about the web, eh :)?)

**Comment by emanuil-tolev** [comment]
Oh yeah, you and the editorial team might have an opinion about journals whose PDF links don't work outside of their own site.

**Comment by dommitchell** [comment]
Huh! Well, I never knew that! Thanks!!
