### ISSUE TITLE
Scroll to application form error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#730]
Possible bug? Referencing #386: here is why people are unlocking without saving:

User (AssEd or Editor) removes a piece of information, from the answers, that is obligatory. They move down the page, making notes and clicking Save. The error message that announces that there is a problem with the form appears at the top of the form *and* the page doesn't scroll up to show the error message. User thinks all is well and clicks Unlock. Changes, including all Notes, aren't saved.

Upon error message scroll to the top or, better still, to the error.

**Comment by greboun** [comment]
Would it be possible to have an alert box preventing  the unlocking, *your
changes have not been saved, proceed anyway*?

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by dommitchell** [comment]
@greboun yes, that is noted for the revamp beginning 2016. This is hopefully a quick fix we can have done now.

**Comment by richard-jones** [comment]
This could be related to the "feature" of some browsers (notably Chrome) to scroll the page to the last place you were scrolled to when the page next loads.  We have this problem widely across the edit forms, and there doesn't appear to be a nice fix.  The browser should actually scroll to the first error - at least that's the way the page is designed.

I'll see what we can do about forcing a scroll using javascript, as apparently using the fragment identifier in the URL is not working.

**Comment by richard-jones** [comment]
@emanuil-tolev - assigning this to you without asking you first :)

**Comment by greboun** [comment]
Are there any more issues related to Chrome that might impact on usage of
websites?
I for example have difficulties downloading PDF files sometimes. the
download gets stuck in an incomplete file

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by emanuil-tolev** [comment]
> Are there any more issues related to Chrome that might impact on usage of
> websites?
> I for example have difficulties downloading PDF files sometimes. the
> download gets stuck in an incomplete file

Heh, in general there's quite a few issues for each major browser, their bug tracking databases contain thousands of open issues.

Related to DOAJ, we usually just track these in their separate DOAJ issues and describe them in the sense of "what problem does this cause for DOAJ specifically", like here. I don't have a list handy because of that, but there are quite a few problems that originate in the way browsers do one thing or another - probably at least 20% of problems arise because of that.

**Comment by dommitchell** [comment]
> They move down the page, making notes and clicking Save. The error message that announces that there is a problem with the form appears at the top of the form and the page doesn't scroll up to show the error message.

Can you remind me about this: why can't we fix the page so that it scrolls to the place where there is an error?

**Comment by emanuil-tolev** [comment]
Well, this is a Chrome issue. We could specifically scroll the page ourselves to the first error or something (though this would take quite a bit of trial/error to get the speed of activation, speed of scrolling etc. right). Thus we just override Chrome's behaviour, if we can. The problem is, Chrome waits for the page to load (and so will we), so we need to scroll the page *after* Chrome. It's quite fiddly and generally I'm not in the habit of recommending going over the head of browser features. It's a bit like disabling right click so people can't copy your images (silly and ineffective). I suppose this is more of a gray area since this browser "feature" just seems plain stupid for form work.

**Comment by dommitchell** [comment]
Seems that it is also an issue in Safari: Version 9.0.1 - Editor has reported that happening last night.

**Comment by dommitchell** [comment]
Closing for now
