### ISSUE TITLE
RSS feed content needs to be tweaked

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#732]
The following changes need to be made to the RSS feed:

1) Journal URL should point to the journal on DOAJ and not the journal's web site
2) Title of the feed should be 'DOAJ Recent Journals Added'
3) Remove the repeated journal name
4) Add ?rss to all URLs so we can track them in GA
5) (and include ISSN if possible?)

(5) not important if very difficult.

![rss](https://cloud.githubusercontent.com/assets/5955396/7879380/3e751d7a-05f0-11e5-90f4-bcd87c0f0440.jpg)

""<entry>
    <author>
      <name>Consejo Superior de Investigaciones Científicas</name>
    </author>
    <category term="LCC:Archaeology"/>
    <content src="https://doaj.org/toc/1988-3110"/>
    <id>urn:uuid:cbb963772a6c4bd2ade9c29fad10d361</id>
    <link rel="alternate" href="http://aespa.revistas.csic.es/"/>
    <rights>(c) DOAJ 2013. CC BY-SA.</rights>
    <summary>Archivo Español de Arqueología</summary>
    <title>Archivo Español de Arqueología</title>
    <updated>2015-05-28T18:32:36Z</updated>
  </entry>""

**Comment by dommitchell** [comment]
Added one more item to ticket above

**Comment by richard-jones** [comment]
@dommitchell - the repeated title is because the title appears in both the "title" and the "summary" elements of the atom feed.  How about we put something useful in the "summary" element?  (Technically, the summary is required by the atom spec in our usage, so we need to give it something)

How about a few of the key fields from the ToC?  Like, say, what appears in the left-hand orange-bordered box?

In the mean time I'll make the other changes...

**Comment by richard-jones** [comment]
I've made these changes, and done something I consider sensible for the summary.  It will now read something like:

Published by {publisher} in {country} on {platform}
Date added to DOAJ: {date}
LCC Subject Classification: {classifications}

PR is made, but not yet merged.

**Comment by emanuil-tolev** [comment]
@richard-jones your latest PR on this has been deployed to live.

**Comment by dommitchell** [comment]
Thanks @richard-jones. Sorry for the silence. Your summary implementation is perfect! I see this live on the site so closing.
