### ISSUE TITLE
Discovery API - public endpoint

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#735]
- [x] define url structure (versioning /api/v1/, paths for public endpoints)
- [x] public search over journals and articles

**Comment by emanuil-tolev** [comment]
https://github.com/CottageLabs/oaspectrum#search-api

**Comment by emanuil-tolev** [comment]
After #783 is merged you can go ahead with this @richard-jones - I've pretty much put in the structure of this route as an example, and even written a custom json encoder so you can concentrate on the DiscoveryApi class returning living DOAJ models - the new jsonify_models encoder will read their .data attribute and convert them to JSON for you, so no conversion stuff for you to do, just return model objects. The swagger yaml I've written is also correct so feel free to build on it.

One note - I've put the search query as a path parameter instead of the usual GET param. so /search/article/computers%20are20good%20for%20you is the way to call it. This is somewhat down to taste, but basically since the URL is already url-encoded I didn't think there was any point in dealing with request params, might as well take it from the path (and it makes error handling a bit easier, e.g. Flask will just issue 404 when the search query is missing because it won't match the route).

You will need to change @blueprint.route('/search/<search_type>/<search_query>') to @blueprint.route('/search/<search_type>/<search_query:path>') in the code I've put down in order to allow forward slashes, but after that you should be away..

**Comment by emanuil-tolev** [comment]
> One note - I've put the search query as a path parameter instead of the usual GET param

but feel free to change it back to a ?q GET param if *you* find something wrong with that

**Comment by richard-jones** [comment]
There are going to be other url parameters (paging and page size) so we don't get away with not having to deal with them.  As you say, a matter of taste, and perhaps it shows that I'm old-fashioned in that I prefer the query args :)

**Comment by emanuil-tolev** [comment]
ah yeah. OK, definitely feel free to change it then.

For swagger docs, instead of ```in:path``` use ```in:body``` to describe your params in that case.

**Comment by richard-jones** [comment]
Actually I spent a bit of time consulting the Gods Of REST (the internet), and concluded that actually, while still a matter of taste ultimately, in the path is the sensible place to put the query!

**Comment by emanuil-tolev** [comment]
and the page size and page number is in the args?

**Comment by richard-jones** [comment]
@emanuil-tolev - assigned to you now this is finished, but maybe we can just close?

**Comment by Nimphal** [comment]
@richard-jones should the API be returning a JSON 404 ? Right now it redirects to a Not found page. And are there any other return codes?

**Comment by Nimphal** [comment]
In portality/settings.py

```
DISCOVERY_MAX_PAGE_SIZE = 100
```

but in the search function it's defaulting to 10

```python
# get the values for the 2 other bits of search info: the page number and the page size
    page = request.values.get("page", 1)
    psize = request.values.get("pageSize", 10)
```

**Comment by richard-jones** [comment]
Just to provide a response (handled in a meeting) on the above, note that the default is 10, but the DISCOVERY_MAX_PAGE_SIZE parameter specifies the largest allowable value supplied by the user.  We do not have a configurable default size, but it is easy to add.

**Comment by richard-jones** [comment]
Documentation points for the Search API that need to be covered:

# The query string itself

The format of the query part of the URL is that of a Lucene query string, as documented here: https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

Some of the lucene query syntax has been disabled in order to prevent queries which may damage performance.  The disabled features are:

1. Wildcard searches.  You may not put a * into a query string: https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Wildcard Searches

2. Fuzzy Searches.  You may not use the ~ notation: https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Fuzzy Searches

3. Proximity Searches. https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Proximity Searches

When you are querying on a specific field you can use the json dot notation used by Elasticsearch, so for example to access the journal title of an article, you could use

    bibjson.journal.title:"Journal of Science"

Note that all fields are analysed, which means that the above search does not look for the exact string "Journal of Science".  To do that, add ".exact" to any string field (not date or number fields) to match the exact contents:

    bibjson.journal.title.exact:"Journal of Science"

For convenience we also offer shorter field names for you to use when querying.  These substitutions are as follows:

**Articles**

* title - search within the article title
* doi - the article's doi
* issn - the article's journal's issn
* publisher - the article's journal's publisher (not exact match)
* abstract - search within the article abstract

For example

    doi:10.139890/blah

**Journals**

* title - search within the journal's title
* issn - the journal's issn
* publisher - the journal's publisher (not exact match)
* license - the exact licence expression

For example:

    license:CC-BY

**Applications**

* title - search within the application's title
* issn - the journal's issn
* publisher - the journal's publisher (not exact match)
* license - the exact licence expression

# The sort options

Each request can take a "sort" url parameter, which can be of the form of one of:

    sort=field
    sort=field:dir

The field again uses the dot notation.

If specifying the direction (dir), it must be one of "asc" or "desc".  If no direction is supplied then "asc" is used.

So for example

   sort=bibjson.title
   sort=bibjson.title:desc

Note that for fields which may contain multiple values (i.e. arrays), the sort will use the "smallest" value in that field to sort by (depending on the definition of "smallest" for that field type)

Substitutions are also available here for convenience:

**Article**

* title - order by the normalised, unpunctuated version of the title

For example

    sort=title:asc

**Journal**

* title - order by the normalised, unpunctuated version of the title
* issn - sort by issn

For example

    sort=issn:desc

**Application**

* title - order by the normalised, unpunctuated version of the title
* issn - sort by issn

# An example: putting it all together

Search for all journals with "acta" in the title which are also published by "wiley", and get the second page of 50 records, ordered by the normalised title in descending order:

    /api/v1/seach/journals/title:acta%20AND%20publisher:wiley?page=2&pageSize=50&sort=title:desc

**Comment by richard-jones** [comment]
Also, note, that the API will also support jsonp, which means that the user can provide a "callback" url parameter, and that will return the json wrapped in that callback as a javascript function.  So:

    /api/v1/seach/journals/title:acta%20AND%20publisher:wiley?page=2&pageSize=50&sort=title:desc&callback=myjsonp

will give back

   myjsonp(
     {the result object}
    )

**Comment by Nimphal** [comment]
Tthis is too much to put in a description and definitely too complex formatting for Swagger UI to handle. I propose we have two pages - one with the swagger generated docs, which has interactive examples, short descriptions and schemas, and one with more general descriptions like the comment above. There's still value in the interactive examples, but it seems there are some things only a markdown page can achieve.

**Comment by emanuil-tolev** [comment]
Can we add that in a section below / above the interactive examples? Can be collapsible and with a clear, big heading.

**Comment by emanuil-tolev** [comment]
> doi:10.139890/blah

This doesn't work unfortunately. DOI searching with forward slashes again I think. Not too hard to fix hopefully.

For the query

```
doi:10.3389/fpsyg.2013.00479
```

sent through the live demo docs, I get this in the log:

```
ERROR in discovery [/home/emanuil/cl/doaj/src/doaj/portality/api/v1/discovery.py:167]:
Error executing discovery query search: SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[eG-1JZJ3SB2EzQPS2eC_3Q][doaj][0]: SearchParseException[[doaj][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"must": [{"filtered": {"filter": {"bool": {"must": [{"term": {"admin.in_doaj": true}}]}}, "query": {"query_string": {"query": "bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479"}}}}]}}, "_source": {"exclude": [], "include": ["last_updated", "created_date", "id", "bibjson"]}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[doaj] Failed to parse query [bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479]]; nested: ParseException[Cannot parse 'bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479': Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; nested: TokenMgrError[Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; }{[eG-1JZJ3SB2EzQPS2eC_3Q][doaj][1]: SearchParseException[[doaj][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"must": [{"filtered": {"filter": {"bool": {"must": [{"term": {"admin.in_doaj": true}}]}}, "query": {"query_string": {"query": "bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479"}}}}]}}, "_source": {"exclude": [], "include": ["last_updated", "created_date", "id", "bibjson"]}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[doaj] Failed to parse query [bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479]]; nested: ParseException[Cannot parse 'bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479': Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; nested: TokenMgrError[Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; }{[eG-1JZJ3SB2EzQPS2eC_3Q][doaj][2]: SearchParseException[[doaj][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"must": [{"filtered": {"filter": {"bool": {"must": [{"term": {"admin.in_doaj": true}}]}}, "query": {"query_string": {"query": "bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479"}}}}]}}, "_source": {"exclude": [], "include": ["last_updated", "created_date", "id", "bibjson"]}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[doaj] Failed to parse query [bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479]]; nested: ParseException[Cannot parse 'bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479': Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; nested: TokenMgrError[Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; }{[eG-1JZJ3SB2EzQPS2eC_3Q][doaj][3]: SearchParseException[[doaj][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"must": [{"filtered": {"filter": {"bool": {"must": [{"term": {"admin.in_doaj": true}}]}}, "query": {"query_string": {"query": "bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479"}}}}]}}, "_source": {"exclude": [], "include": ["last_updated", "created_date", "id", "bibjson"]}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[doaj] Failed to parse query [bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479]]; nested: ParseException[Cannot parse 'bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479': Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; nested: TokenMgrError[Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; }{[eG-1JZJ3SB2EzQPS2eC_3Q][doaj][4]: SearchParseException[[doaj][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"must": [{"filtered": {"filter": {"bool": {"must": [{"term": {"admin.in_doaj": true}}]}}, "query": {"query_string": {"query": "bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479"}}}}]}}, "_source": {"exclude": [], "include": ["last_updated", "created_date", "id", "bibjson"]}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[doaj] Failed to parse query [bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479]]; nested: ParseException[Cannot parse 'bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479': Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; nested: TokenMgrError[Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; }{[eG-1JZJ3SB2EzQPS2eC_3Q][doaj][5]: SearchParseException[[doaj][5]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"must": [{"filtered": {"filter": {"bool": {"must": [{"term": {"admin.in_doaj": true}}]}}, "query": {"query_string": {"query": "bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479"}}}}]}}, "_source": {"exclude": [], "include": ["last_updated", "created_date", "id", "bibjson"]}, "from": 0, "size": 10}]]]; nested: QueryParsingException[[doaj] Failed to parse query [bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479]]; nested: ParseException[Cannot parse 'bibjson.identifier.id.exact:10.3389/fpsyg.2013.00479': Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; nested: TokenMgrError[Lexical error at line 1, column 53.  Encountered: <EOF> after : "/fpsyg.2013.00479"]; }] (ref: 2a51d832-2c9d-11e5-b56b-34028650adca)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in common [/home/emanuil/cl/doaj/src/doaj/portality/api/v1/common.py:28]:
Sending 400 Bad Request from client: There was an error executing your query (ref: 2a51d832-2c9d-11e5-b56b-34028650adca)
```

**Comment by richard-jones** [comment]
I've now had a bit of a deep think about this, and just wanted to document what I plan to do before I do it.

First off, I've found an updated version of the query syntax documentation which actually lists "/" as a reserved character.  Everything else is the same as the syntax linked from the earlier comment:

http://lucene.apache.org/core/5_2_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html

Anyway, I looked into differences between ES and Lucene, to see if there's anything else we need to care about.  We've said, essentially "use a lucene query string", but elasticsearch has some additional operators that it adds over the top of lucene.

Lucene says the following are reserved:

    + - && || ! ( ) { } [ ] ^ " ~ * ? : \ /

This means, that you, as the API caller, are responsible for escaping them

ES, meanwhile, says the following are reserved:

    + - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ /

Which means we have a set that ES attaches special meaning to that Lucene doesn't:

    = > <

The =, < and > are all used in range searching, which we allow via the Lucene syntax, so I don't see any reason to escape them.

Now technically, your query "doi:10.3389/fpsyg.2013.00479" is an illegal search string, because it does not meet the Lucene query syntax requirements (you should have escaped the "/" yourself), and we shouldn't be required to do anything about it.

That said, do we want to look for special characters that should be paired, and escape them if they are not?  This would mean looking for / and " and seeing if they have an equivalent closer, and if not putting \ in front of them.  This would definitely be "being nice to the user" rather than sticking to the word of the documentation - in fact, it may even cause confusion because something a user is doing which should cause an error will actually work, so they may not notice they did it wrong.

Thoughts before I do any kind of fix?

The fix itself will involve:

1. Breaking the query string out in to its component parts (separating on unescaped ":")
2. Looking to see if the following character starts with a ".  If so, track forward counting the number of quotes - there should be an even number.  If not, separate the following string by space, then in each component escape any " and / characters.
3. Put the string back together again

Alternatively, we could throw a meaningful error when an unescaped / is found in the query string (as we do with * and ~ now.

**Comment by emanuil-tolev** [comment]
> This would definitely be "being nice to the user" rather than sticking to the word of the documentation - in fact, it may even cause confusion because something a user is doing which should cause an error will actually work, so they may not notice they did it wrong.

I think we actually did this in fv1, by escaping double quotes. At least I'm pretty sure we did.

However this is an API, not a GUI. I think finding unmatched characters is a bit much. If we could raise a sensible error there that's better. Though I guess we'd have to find the unmatched char to say "you have an unmatched char" :(.

Searching directly by DOI does sound like a very sensible thing for DOAJ to have - that way you could do a very quick and dirty check if an article is OA. I would escape forward slashes, with the view for perhaps adding a dontescape=true or escape_query=false arg later on for advanced use.

**Comment by richard-jones** [comment]
>> This would definitely be "being nice to the user" rather than sticking to the word of the documentation -
>> in fact, it may even cause confusion because something a user is doing which should cause an error 
>> will actually work, so they may not notice they did it wrong.

> I think we actually did this in fv1, by escaping double quotes. At least I'm pretty sure we did.

Yes, we did - facetview has some fairly comprehensive string escaping stuff, but it's designed around the premis that the user is providing us with the string they want to search for, not the lucene query string, so we are safe to mess with it in that way.

Finding unmatched characters does already sort of work, in so much as the ES query will fail if the string is malformed, but this is presented back to the user without any detailed information on what they did wrong.  We could route the ES error back to the user, but that doesn't feel right to me, as we'll be exposing our internals.  If we want to give them more detail, then, we need to pre-empt the ES error by analysing the query string ourselves, which is fiddly work.

Searching directly by DOI /does/ sound sensible, but I don't want to add a "treatmelikeanidiot=false" flag to the API :)  We should instead define a consistent behaviour that covers all the relevant use cases, implement it and document it and leave it at that.

Right now that would be one of:

1. Check for an unescaped "/" (since we aren't going to support regular expressions) and give a meaningful error
2. Always auto-escape "/" if it has not already been escaped.  Provided we never support regular expressions, this should work.

(2) is the one you want, so I'll go with that!  I'll pop the additional documentation here later.

**Comment by richard-jones** [comment]
OK, there's a PR in that does the job.

Updates required to the documentation:

* Use the latest lucene query syntax documentation

http://lucene.apache.org/core/5_2_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html

You may want to find a better reference - this is actually from the javadocs, but I haven't yet seen one that's more like a tutorial that is worth using.

* Add to the "disabled features" section that regex queries (pre and post fixing /) are also disallowed

* Note somewhere that all / characters will be automatically escaped for you, unless you escape them yourself.

Also worth noting, for our own benefit if not for the documentation that you cannot put a \ in a URL as-is, you must escape it.

Now your DOI query can be done in one of two ways:

    doi:10.3389/fpsyg.2013.00479
    doi:10.3389%5C/fpsyg.2013.00479
