### ISSUE TITLE
API - authentication

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#736]

**Comment by richard-jones** [comment]
@Steven-Eardley - when I ran the migration, after the end of the actual migration, the script just kept processing empty accounts until I killed it:

added account volkandemir to batch update
added account womble to batch update
added account yadollahpour to batch update
added account zavaraqi to batch update
added account - to batch update
added account - to batch update
added account - to batch update
added account - to batch update
added account - to batch update

Otherwise, the migration seemed to work fine.

**Comment by richard-jones** [comment]
Also, I notice that the 401 on unauthorised gives back a web page - should this also return a json response?

**Comment by emanuil-tolev** [comment]
(if you do add that @Steven-Eardley there's a _bad_request func that's used elsewhere for JSON errors)

**Comment by Steven-Eardley** [comment]
So in today's meeting did we agree that @emanuil-tolev will look at writing error handlers?
@richard-jones When I run the script I don't see any account names; only bulk operations:

```
$ python portality/upgrade.py -u portality/migrate/api_v1/api_auth.json
Running in dev
Loaded final config from /Users/steve/code/cl/doaj/src/doaj/dev.cfg
Upgrading account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  500 to account
writing  394 to account
```

**Comment by emanuil-tolev** [comment]
> So in today's meeting did we agree that @emanuil-tolev will look at writing error handlers?

We did.

FYI also here: I added an api_key_optional decorator so you can make a request without a key (then the route has to handle current_user being undefined) or with a key (but it has to be a real key and your api privileges must not have been revoked).
