### ISSUE TITLE
Automatic removal of journal on rejection of reapplication

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#771]
When a reapplication is rejected, a journal record should automatically be removed from DOAJ and an email sent to the publisher informing them of this.

I'd like to scope this out with @richard-jones and @emanuil-tolev and try to get this implemented before end 2015.

**Comment by richard-jones** [comment]
In light of our discussion around keeping discontinued journals in the DOAJ, is this still the desired functionality?

Otherwise, a couple of points to go through to make sure we do the right thing:

* what happens when a reapplication is rejected?
   * are there any circumstances (such as discontinuation) where the journal in the DOAJ should not be automatically removed
   * otherwise the journal should be marked as in_doaj=False
* what happens when a reapp is unrejected (which can theoretically happen)
   * should the journal be re-instated, or should it be left as-is
* are there any other status changes to the reapplication which matter
* should anything happen to a reapplication if the journal is withdrawn in the mean time?

**Comment by dommitchell** [comment]
On hold for now

**Comment by dommitchell** [comment]
No longer needed
