### ISSUE TITLE
Questions about "missing" tags in OAI

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#775]
Can I have your thoughts?

/starts/
We have a few follow up questions regarding the new data structure that DOAJ gave us. (https://doaj.org/oai.article?verb=ListRecords&metadataPrefix=oai_doaj).  We would like to use the 'oai_doaj' metadata format but it's missing a few tags that are necessary and do appear in the 'oai_dc' format (https://doaj.org/oai.article?verb=ListRecords&metadataPrefix=oai_dc).

Please see the following issues:

1)      No types in the records. In the oai_dc records I can see the <dc:type> tag.
2)      No backlinks. We would like to point the customers to the record in DOAJ as well as to the full text. In the oai_dc format I can see links to DOAJ under <dc:identifier>, starting with https://doaj.org/article/. In the oai_doaj I don't see them at all.
3)      ISSN appears also as EISSN. I see records in which the same ISSN appears both in the ISSN and EISSN tags, even though in DOAJ and in the fulltext it appears only as ISSN. For example:

- Record in DOAJ's oai: https://doaj.org/oai.article?verb=GetRecord&metadataPrefix=oai_doaj&identifier=oai:doaj.org/article:b7cfb3dd58ce40c3a10d313c7c02883e
- Record in DOAJ's native site: https://doaj.org/article/b7cfb3dd58ce40c3a10d313c7c02883e

4)      Problematic characters display in some records. see for example the following titles:
https://doaj.org/article/25481a626dc9416abaddd834a54bce9f
https://doaj.org/article/881cbd43ab994e7f9291ee42974a9391
https://doaj.org/article/e9c4a62cd87b41f98a1527a4970bdf50

/ends/

**Comment by richard-jones** [comment]
The oai_doaj format is identical to the doajArticle xsd format (one of our tests is that the oai stream validates against that schema).  Since that format doesn't include a type or a file link, that's the reason that information isn't there.  Not sure about the issn/essn field - @emanuil-tolev can you comment?

Each record has an identifier, which will allow them to retrieve both metadata records easily.  For example to see the oai_dc and oai_doaj for the same record:

https://doaj.org/oai.article?verb=GetRecord&identifier=oai:doaj.org/article:7ae829e8d4494980bd4817b88ce31f35&metadataPrefix=oai_doaj
https://doaj.org/oai.article?verb=GetRecord&identifier=oai:doaj.org/article:7ae829e8d4494980bd4817b88ce31f35&metadataPrefix=oai_dc

Othrewise, this is a request for either a third doaj metadata format, or an extension of the standard doajArticle schema.

The problematic display of characters in the article records will be because of malformed characters in article uploads.

**Comment by dommitchell** [comment]
DRAFT comment

Follow up questions:
1)      From our understanding, the type of records in the collection can be either an article or a journal (from the DOAJ website: Journals- 10,474, Articles- 1,917,620.) Is there a consistent rule that we can use to distinguish between these types according to a different parameter in the records? For example, perhaps the title is in a different?
2)      Will DOAJ be able to support deletions? According to https://doaj.org/oai.article?verb=Identify the deletions method is 'transient'.  In the past, we had many issues with records that were deleted from DOAJ but not from Primo Central and we would like to prevent this problem before it comes up again.

For (1) are they in fact using OAI correctly?
For (2), XXXXX

**Comment by dommitchell** [comment]
Comment above updated. Thinking we might need an 'OAI' label?

**Comment by richard-jones** [comment]
1) From our understanding, the type of records in the collection can be either an article or a journal (from the DOAJ website: Journals- 10,474, Articles- 1,917,620.) Is there a consistent rule that we can use to distinguish between these types according to a different parameter in the records? For example, perhaps the title is in a different?

They are available under different OAI endpoints: oai and oai.articles

2) Will DOAJ be able to support deletions?

Deletions in OAI are difficult, because they impose behaviour on the underlying system.  Right now our OAI endpoint is a date-ordered search, but if we wanted it to be a more static change-list which also supported deletes then we'd need to approach it in a different way that would be considerably more work - we'd have to keep an event log, which we don't currently do.

Whether we go that route I think depends on how serious we are about the OAI endpoint, and whether that event log would have other uses (which it could, say, in the admin area for action tracking)

**Comment by dommitchell** [comment]
Thanks for this info. Closing.
