### ISSUE TITLE
Accidentally deleted an account: can you reinstate it?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#778]
https://doaj.org/account/21600619

**Comment by dommitchell** [comment]
Or just get me the email address associated with it.

**Comment by emanuil-tolev** [comment]
Unfortunately just now this would be probably more trouble than it's worth. The few reasons are:

- we are ready to restore from backup of course, but we have a backup of the whole catalogue stored directly in the form our data store prefers for backups. In order to bring partial data out we would have to restore all of the data, same as when DOAJ goes down in some catastrophic manner and we need to pretty much recreate the infrastructure elsewhere. It is something we can do of course, as part of backup contingency, but probably not worth it (unless you think otherwise).

- if we had a test or staging server running, we'd have just taken it from there (as the data is only a few months old usually). Unfortunately these are due to be set up for the API project over the next few months, so neither is currently running. Their purpose is explicitly to help development projects, though we could have "cheated" and gotten you the email just because it would be easily accessible.

As a way around, can you find the journal with this ISSN (that the account has)? Maybe the journal contact detail would be able to help, or the general contact for the publisher of the journal? Also the DOAJ feedback inbox (on Google or your old speednames host) might contain emails with that ISSN in it.

**Comment by dommitchell** [comment]
Not important enough. Closing.
