### ISSUE TITLE
Workflow: ability to select multiple records and perform batch operations

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#800]
We have publishers where for all re/applications DOAJ criteria are met and which can be handled as one case. Possible difficulty Subject index. The following functions need to be developed:
- select all journals/applications from one publisher and:
   allocate to editorial group
   change status and insert note 
   remove / put in to DOAJ and insert note
- batch change status eg from reapplication submitted to pending
- batch edit certain fields in the application form (except for issn, journal name and other journal specific fields)
- batch edit certain fields in the journal list eg license information CC-BY-NC to CC-BY for all journals of a publisher

**Comment by greboun** [comment]
we want to be able to select multiple applications or journals 
-batch reject with insert of note
-batch accept with insert of note
-batch allocate to editorial group
-batch change status  eg from reapplication submitted to pending 
-------[batch edit certain fields in the application form (except for issn,journal name and other journal specific fields)][maybe too difficult to implement]
-batch edit certain fields in the journal list  eg license information CC-BY-NC  to CC-BY for all journals of a publisher
we have publishers, for example Copernicus where for all journal applications DOAJ criteria are met and which can be handled as one.case    ?possible difficulty   Subject index? when accepting journals as batch

**Comment by dommitchell** [comment]
Ready to be assessed.

**Comment by richard-jones** [comment]
We could do this under tnm, but not under the current block, as I'd estimate this at a fair few days dev and testing (testing, especially, as this has the opportunity to do plenty of harm to the database), so would exceed our time allocation by some margin.

I'd also slightly prefer to estimate for this separately as a mini-project since it's actually an entire new feature-set, and we would also want to spend a bit of time planning it out to make sure it's the right thing.

Let me know what you think.

**Comment by dommitchell** [comment]
@richard-jones let's get a price for that option then. This is fairly crucial to speed up ManEds work so there are cost savings to be had elsewhere. 

@greboun agree?

**Comment by greboun** [comment]
@richard-jones <https://github.com/richard-jones>
@dommitchell

Agreed   this is a very useful extension of the editing capabilities

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by dommitchell** [comment]
@richard-jones if you can estimate the work, we'll discuss this with the other TNMs at the next team hangout.

**Comment by dommitchell** [comment]
@richard-jones and scheduling please

**Comment by richard-jones** [comment]
I've considered 2 possible approaches to this:

1/ Provide the usual application/journal form to be used as a kind of "overlay" on records being edited.  This would mean that all bulk operations are done through the one form, and that the contents of that form are overlaid onto all selected items.  This includes allocation to editorial group, status changes, notes.  It wouldn't cover bulk withdraw/reinstate from the public DOAJ so easily though, so that would be a separate feature (possibly still exposed through the same page, as it is at the moment on the single journal edit form).

2/ A specific "bulk edit" area, possibly as an expandable page segment on the admin area search interfaces (in a similar location, say, as the bulk delete).  In this case we would have specific actions that could be taken (status change, withdraw/reinstate, etc), or specific metadata fields that could be edited.

(are there other obvious ways that I've overlooked?)

My thoughts on each are (both pros and cons in no particular order):

1/ Overlay form
* Could be confusing for the user - it would be harder to see both which records you are editing and what you are changing at the same time
* Higher risk of inadvertent edits - if you accidentally put something in a field you didn't mean to that could be Quite Bad!
* Would probably have to be implemented as a totally new Form and FormContext, as the crosswalk process and required fields would be totally different.  This is a lot of work, and also gives us a maintenance issue for any changes to the application form (would have to come up with a way to mitigate, may require some broader refactoring).
* Would provide maximum flexibility - any and every form element could be associated with a bulk edit

2/ Bulk Edit area
* Would be easier to present to the user alongside the records the bulk edit will affect
* Lower risk of inadvertent edits - constrain the user to modifying one or two fields at a time from a limited list of fields/options
* Would need to be implemented as a FormContext or at least to drive an existing FormContext with a "fake" version of the full application form.  Might require some refactoring of the ManEd context.
* Would be limited in its flexibility - we would want to specify every field/option that could be edited, and provide the interface.

My recommendation would be to go with (2) /if/ we can specify a short list of fields to be editable.  OTOH, if you require arbitrary fields to be editable, we may be better with (1).

There are also issues to consider in general, whichever option we take:

* bulk edits take time and memory - the UI will have to handle the user's expectations while the job is processing, and we have to be mindful that the more records being edited the longer it will take and the more memory it requires, which may impact on other user's experiences.  We may wish to consider a "maximum size" for bulk edits for pragmatic purposes.

* may clash with existing edit locks - If someone has a bulk edited record open in their browser they will have an edit lock on it.  Making the bulk update respect the edit lock will be hard/more computationally expensive, and it's not clear to me what the back-out strategy would be in case a lock is found.  Propose instead that we ignore edit locks in bulk operations.  It may be in the long run that we actually want to swap edit-locks for a more complex (but less annoying to the user) check/merge process, which would free up processes like this to not worry about other users.


@dommitchell - I don't think I can estimate for this yet, until we've had more of a discussion about the experience you're looking for.

Whichever option we go for, though, the amount of work is fairly substantial - I would guess in a similar scale to the continuations work.  So, in terms of scheduling, given the number of bits of work that are happening in parallel now, it is unlikely we could do this until the new year, unless we considered switching this and the continuations project around.  Anyway, that's just a finger in the air right now - I'll have a clearer picture when we've talked more.

**Comment by dommitchell** [comment]
Yes agree that we need more discussion. I was imagining check boxes next to each item in a search result. Imagine the article delete functionality except the 'delete articles' button is a dropdown:

reject with automatic insert of note
accept with automatic insert of note
allocate to editorial group
change status

Let's discuss.

**Comment by richard-jones** [comment]
RJ to review the work required for the above.

@dommitchell - to think about whether the checkboxes are needed

**Comment by dommitchell** [comment]
OK, facet views are enough here so no checkboxes needed at this stage. 

We might want to add them later.

**Comment by greboun** [comment]
I was just realizing today that automated batch accepts (#800) can only
work when the field for subject classification has also been filled in for
the individual journals  before.
Now the situation is that ass editors are supposed to make this
classification when checking the aplication form


Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by dommitchell** [comment]
Tom's right. Accept and reject should not be included here. Users must add notes in these instances anyway. Have updated original issue.

**Comment by dommitchell** [comment]
We have decided not to go ahead with this just now. Closing

**Comment by dommitchell** [comment]
Quote received from Richard.

**Comment by richard-jones** [comment]
We've now nearly finished the project based on this, and there are other issues surrounding it, so closing this one off
