### ISSUE TITLE
Unlock and close button sometimes doesn't work

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#808]
Clicking the unlock and close button on this record did not work. This was the second record todya.

https://doaj.org/admin/journal/5533821ba5034376b8c520bf989a2064#done

9.40am CET today

Info from developer console in Firefox:

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Use of getAttributeNode() is deprecated. Use getAttribute() instead. jquery.min.js:3:0
Use of getPreventDefault() is deprecated. Use defaultPrevented instead. jquery.min.js:3:0
This website uses a SHA-1-certifikat; it is recommended that you use signaturalgorithms that use hashfunktions stronger than SHA-1.[Läs mer]
Denna webbplats använder sig av en SHA-1-certifikat; det rekommenderas att du använder certifikat med signaturalgoritmer som använder hashfunktioner starkare än SHA-1.[Läs mer]

**Comment by richard-jones** [comment]
Can you run through for me the steps that you took prior to this, from
discovering the journal to edit through any changes you made, to finally
discovering that the button didn't work?

**Comment by dommitchell** [comment]
Sure!

Admin - journals - search, search term: 'TELOS' - edit journal (https://doaj.org/admin/journal/5533821ba5034376b8c520bf989a2064) - decided against making a change - hit unlock.

**Comment by greboun** [comment]
The same thing happened to me with an application it updated but did not
unlock and close

application
https://doaj.org/admin/suggestion/55e4b2f6550d4d16afd8b96f1f34778b#done

time  (amsterdam  3.02 pm)

using browser Chrome
js console message


*Scripts may close only the windows that were opened by it.*

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by richard-jones** [comment]
This one is a clear case of the window being opened via an external link rather than from the search.  The error:

*Scripts may close only the windows that were opened by it.*

Indicates that the browser has explicitly blocked the request by the script to close the window, and unfortunately that's beyond our ability to overcome.

I have been pondering an overall better solution, and the only thing I can come up with that might work is to have the "unlock and close" button actually redirect the user to a "you can now close this window" page.  It will increase the number of clicks to close the window from 1 to 2 in /all/ cases, and will require an additional web request, but will remove all possibilities of confusion.

Any other thoughts?

**Comment by dommitchell** [comment]
I think we leave this for now. It's sporadic enough to not warrant any more time just yet. We can revisit if it becomes more persistent.
