### ISSUE TITLE
Journal ToCs: languages should be A to Z not Z to A

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#810]
Compare https://doaj.org/toc/2409-5540 with https://doaj.org/admin/journals?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%222409\\-5540%22%2C%22default_operator%22%3A%22AND%22}}%2C%22from%22%3A0%2C%22size%22%3A10}

Language listing should be A to Z

**Comment by richard-jones** [comment]
The language list is essentially unordered, since the user can enter them in the application form in any sequence, so what comes out here ought to be random, or at most weakly connected to whatever the user did when they created the journal.  Since intermediate processing also happens on the languages (e.g. to convert them from codes to names) they could also be in different orders in different contexts (as seen here).

We can add some explicit ordering in if that's a requirement, though.  Do you prefer:

1/ always ordered by language code
2/ always ordered by language name
3/ always ordered by whatever is being displayed in context (code or name)

(I'd guess (3) and I'd recommend against (2) because it will create extra work in some contexts)

**Comment by dommitchell** [comment]
Hmm, I'm not convinced. I tested this and changed the order before I submitted this task. The ordering on the journal home page is clearly Z-A. The original ordering in the journal record was unordered, I think French was first. I changed the order manually to alphabetical ordering but no difference was made to the journal home page.

At the very least: updating the order in a journal record should change the order on the home page.

**Comment by richard-jones** [comment]
I've looked a bit deeper, and there's no explicit ordering being done on either the javascript or the ToC side.  My guess is that the list de-duplication process that the list of languages uses winds up ordering it, but this is only used on the ToC where the English names of the languages are displayed, while the admin search interface just displays the codes.

**Comment by dommitchell** [comment]
More on this. A publisher asked me to change the language ordering so I did it in test.

As the journal appears in admin before any changes. Note language ordering: EN, FR, IT, PT, ES
![anuac1](https://cloud.githubusercontent.com/assets/5955396/9224807/9a686b46-4105-11e5-92e0-432c0574f572.jpg)

and on the ToC page: PT, ES, IT, FR, EN
![anuac3](https://cloud.githubusercontent.com/assets/5955396/9224808/9a72cfc8-4105-11e5-95fc-56ce355cdbd3.jpg)

and in the Admin view to edit the journal record: EN, FR, IT, PT, ES
![anuac2](https://cloud.githubusercontent.com/assets/5955396/9224810/9a76dfb4-4105-11e5-9fa4-b86f38e0d3e6.jpg)

In the journal record in Admin, AFTER my edits: IT, EN, FR, ES, PT
![anuac4](https://cloud.githubusercontent.com/assets/5955396/9224812/9a790af0-4105-11e5-8c4b-1d4e0bb85fd3.jpg)

Still in the journal record in Admin, AFTER SAVING: EN, FR, IT, PT, ES - the order reverted
![anuac5](https://cloud.githubusercontent.com/assets/5955396/9224811/9a770a48-4105-11e5-80dc-35b763b397d9.jpg)

And on the refreshed ToC, unchanged and not matching what is in the form: PT, ES, IT, FR, EN
![anuac6](https://cloud.githubusercontent.com/assets/5955396/9224809/9a739016-4105-11e5-9d22-f530c435b46b.jpg)

It seems to me that there are two things going on which should be corrected:

1) the form reverts to the old order upon save, OR is ordering on Save. Could be a cache thing?
2) the order in Admin, or in the record itself, doesn't match what is displayed publicly.

**Comment by richard-jones** [comment]
I'm not sure why the lists are ordered the way they are in the various contexts, all I can say is that there is no explicit ordering applied anywhere in the code, so what you're seeing is a by-product of any intermediate processing that goes on.  For example, in some cases the data goes through a de-duplication process, which in python can be implemented like this:

    list(set(my_list_of_things))

sets are deduplicated automatically, but are also inherently unordered, so the list you get out of a set is in a near random order - that is, it is not possible to tell in advance how it will be ordered in a meaningful way.  It may often (because of the implementation) produce the same results for the same input list, but that result may not be the same in every context, and cannot be counted on.

So, the answer is for us to define what ordering you want in the different situations, and then write the code to do that explicitly.

**Comment by dommitchell** [comment]
> there is no explicit ordering applied anywhere in the code, so what you're seeing is a by-product of any intermediate processing that goes on

I don't understand what this means.

Could it also be a browser thing?

**Comment by emanuil-tolev** [comment]
> I don't understand what this means.
> 
> Could it also be a browser thing?

From meeting today: the above means that languages are assigned in some order by the user, but in the process of deduplicating the order is lost - they could come out in any order.

To be decided:

- order alphabetically, explicitly, when the form is saved?
- or preserve order set by user? Noted that some users seem to attach additional meaning, e.g. if English is listed first, it's "primary" and that it may be best to enable these users to specify this more explicitly in the future (not to mention a single-value primary_language field would be much easier for clients of the API to work with, I'm sure, than a list).

Up to DOAJ team - my personal, not particularly strong, opinion is that we should not have started to lose the ordering in the first place and we should find another way to deduplicate, as it breaks the UX convention of a list (things remain in the order I put them in). This can be broken with good reason of course.

**Comment by dommitchell** [comment]
For discussion at the next team meeting.

**Comment by dommitchell** [comment]
We discussed and we decided that we wouldn't do anything about this for now. Leaving for later.

**Comment by dommitchell** [comment]
Closing for now
