### ISSUE TITLE
An application or reapplication should not be save-able without a Classification

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#815]
Some applications and reapplications are being saved without a classification. 

Please make it so that at least ONE classification must be present upon saving.

**Comment by dommitchell** [comment]
@richard-jones can this be part of the workflow project?

**Comment by dommitchell** [comment]
Transferred from #520

**Comment by richard-jones** [comment]
This is hopefully quite staightforward, requiring an update to the Subject form in formcontext/forms.py ... but ... we need to see how that required field setting plays with the javascript jtree front-end, and what happens when the validation fails.  May require some UI tweaking to make it behave in a sensible way.

We could package this with the Workflow project, if that makes the most sense in terms of release timing, otherwise it can just go ahead as a separate TnM task.

@Steven-Eardley - I'll assign it to you for you to decide where it best fits in your work.

**Comment by richard-jones** [comment]
@dommitchell - we're just looking at what exactly this means.  I think that probably you want to be able to save applications without setting classifications (you may be coming back to work on it later).  Instead, should we have it so that you can't set the status "ready", "completed" or "accepted" without setting the classification?

**Comment by dommitchell** [comment]
> should we have it so that you can't set the status "ready", "completed" or "accepted" without setting the classification?

Perfect! Thanks!

**Comment by dommitchell** [comment]
FEEDBACK
I just managed to save this reapplication as 'Completed' and without any classification:

https://testdoaj.cottagelabs.com/admin/suggestion/009aa12f367944e0a18727d4d137c166#done

**Comment by Steven-Eardley** [comment]
This wasn't visible on test when you reviewed it due to some glitch with our auto-deployment, so it wasn't there! I've checked it and you should now see it rejecting the form.

One issue I still see is there's no useful feedback beyond 'there is a problem with the form' - the strangeness of the subject chooser may hide the 'this field is required' message which should appear. If this is a major issue, I can try a different approach to informing the user.

**Comment by dommitchell** [comment]
Thanks! Tested it and it works. Saw the 'this field is required' message and then it disappeared.

Could we maybe have the #first_problem scroll to the title of the box: 'Subject classification' and add a 'this field is required' next to the title there?

**Comment by dommitchell** [comment]
Now the error message has disappeared all together:
https://testdoaj.cottagelabs.com/admin/suggestion/009aa12f367944e0a18727d4d137c166#first_problem and the error message "There is a problem with the submitted form." is above the fold which means you need to scroll up to see it.

**Comment by Steven-Eardley** [comment]
Yes, that's the behaviour I saw when I wrote my comment above. I was a little surprised you'd seen a 'this field is required' message! I'm working on displaying it properly.

**Comment by dommitchell** [comment]
Looking good! Closing.
