### ISSUE TITLE
Links in Owner facet return Not Found error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#828]
https://doaj.org/admin/journals?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22admin.in_doaj%22%3A%22T%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22biomed%20central%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

You used to be able to open the links in new windows but these now return a 'Not Found' error, e.g. https://doaj.org/admin/21955840

**Comment by emanuil-tolev** [comment]
I'm not sure I follow - the values in the facets are not supposed to be real links, they're basically used by the Javascript interface so it matters what you click on, rather than what the link is. Isn't that true for most facets across all search UIs on the site? (That the links the values point to are nonexistent.)

I guess the expectation here is that you would be able to click on "Owner" in the results display. But I guess you're using this to find all accounts linked to Biomed Central (or any other publisher)?

It would be a handy feature though certainly not intended .. I'm not quite sure how the links are generated, I think they might be relative (like ```<a href="12345678">12345678</a>```) and that's why you get the 404. Not sure they would be easy to change to absolute ones, will leave @richard-jones to answer that.

**Comment by dommitchell** [comment]
Yeh, I think you are right. There *is* somewhere in the DB where one can right click and a Not Found isn't produced (User db maybe) but I think I am confusing them.

CLosing
