### ISSUE TITLE
Suggest a continuation

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#837]
Addition of a feedback link on each Journal ToC which goes to a DOAJ email address (not a contact form), for providing information about continuation/discontinuation of a journal (or anything else the user wants to email about).

Note: if, in the mean time #764 develops a contact form, we can switch the link on the ToC to point to the same form with a different subject line.

**Comment by dommitchell** [comment]
How do I see the different subject line?

**Comment by richard-jones** [comment]
I think the emails are going into the mailtrap, so you'll need to log in there and take a look at the test emails you send.

@emanuil-tolev - does @dommitchell have access to the mailtrap for the test server?

**Comment by dommitchell** [comment]
I am still confused. I do not see the different path specifically for suggesting a continuation, or is that not what you mean. It is this that is confusing me: 

> Note: if, in the mean time #764 develops a contact form, we can switch the link on the ToC to point to the same form with a different subject line.

Different subject line to what? Am I supposed to see a feedback form that says Suggestion of a continuation?

**Comment by dommitchell** [comment]
Feedback (text changes):

On a journal homepage, http://testdoaj.cottagelabs.com/toc/0974-9322 change 'Subsequent title(s):' 'Continued by:'
Change 'Previous title(s):' to 'Continues:'
Change the order so that 'Continues' always appears above 'Continued by'.

In the journal form, http://testdoaj.cottagelabs.com/admin/journal/0fb09e308a9343e997bbb7374569e02e in the Continuation information section, add a line under the heading: 'using *existing* journal records.'

Change
'Create a preceeding continuation
Create a succeeding continuation'
to
'Create a new preceeding continuation
Create a new succeeding continuation
(Adds a new record to the database.)'

Change: 'ISSN(s) this Journal replaces' to 'This journal continues (add ISSN(s)):'
Change: 'ISSN(s) this Journal is replaced by' to 'This journal is continued by (add ISSN(s)):

How big are the ISSN fields above? Can they handle #280 ?

On this page, http://testdoaj.cottagelabs.com/admin/journal/0fb09e308a9343e997bbb7374569e02e/continue?type=replaces change the text to read: 'Creating a new record for the journal that International Journal of Computer Networks & Communications continues.
Add the Journal Title and ISSN(s) that this journal continues. This will create a NEW record in DOAJ so do not use this option if the journal already exists. Once you submit this form, a new journal record will be created and you may edit the other associated metadata fields.'

Remove 'new' from the labels of the 3 fields that follow.

On this page, http://testdoaj.cottagelabs.com/admin/journal/0fb09e308a9343e997bbb7374569e02e/continue?type=is_replaced_by change the text to read: 'Creating a new journal record for the journal that International Journal of Computer Networks & Communications in continued by.
Add the Journal Title and ISSN(s) that this journal is continued by. Once you submit this form, a new journal record will be created and you may edit the other associated metadata fields.'

Remove 'new' from the labels of the 3 fields that follow.

**Comment by dommitchell** [comment]
@richard-jones feedback in the comment above now updated and ready to go.

**Comment by dommitchell** [comment]
I realise my feedback is probably attached to the wrong issue but at least its all in one place.

**Comment by dommitchell** [comment]
Upon submitting feedback the confirmation contains HTML tagging:

<strong>Thank you!</strong> Your message has been sent, we'll get back to you as soon as we can. 

Please remove that HTML tagging and change the text to read:
Thank you for your feedback which has been received by the DOAJ Team.



> Note: if, in the mean time #764 develops a contact form, we can switch the link on the ToC to point to the same form with a different subject line.

Still unsure how to test this. I have looked in Mailtrap and can see that the Subject header is: Message from contact form - dom@doaj.org
What's the difference?

**Comment by richard-jones** [comment]
I've made the text change for the next PR

With regard to testing the subject line, I realised that I was misleading.

There are 2 things that vary depending on the context of the email:

1/ If the email is sent from a link on a ToC, then the message body is pre-populated with some useful context information, like "More information on journal 'Open Thermodynamics Journal' (ISSN: 1874-396X)".  The subject line remains the same as any other ordinary contact request.

2/ If the email is sent from a the contact form where the hidden "subject" field has been filled in, then the message subject will be prefixed with "[spam?]".

It will be hard for you to trigger (2), as it will mean filling the form in as if you are a bot!

**Comment by dommitchell** [comment]
Ah-ha! Now I understand. Great. In that case I have tested the email function. Shall look forward to the text changes.

**Comment by richard-jones** [comment]
Ok, I've now made the other text changes from the comment higher up.  PR for continuations due a bit later today, once I've looked at #1034 to see if I can reproduce/fix.

**Comment by dommitchell** [comment]
All reviewed and ready to go live! Thanks!
