### ISSUE TITLE
Bug: what causes this to happen?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#853]
7.20 UK this morning. Search on "Journal of applied sciences in environmental sanitation" in Admin returned this page.
![oops](https://cloud.githubusercontent.com/assets/5955396/9754666/e3e868e4-56cb-11e5-9987-2f5928d825e2.jpg)

**Comment by emanuil-tolev** [comment]
How weird. Did it work afterwards? After a page refresh? Or after going in again to the admin search?

It kinda looks like it's on the second page of results (from a previous query) and then you put a new query in, and it's still on the 2nd page. Except that 2nd page of 1 result is the weird thing above.

If it is that it might be a bit tricky to decide what to do, since part of the reason it's done that way is probably because we can't reset which page you are on on every new query - it's easy to cause a query by e.g. having focus on the search box and hitting a key (like any key, even Shift or Control or a space), and then you're back to page 1.

**Comment by emanuil-tolev** [comment]
Yeah, this is the problem. So go to the admin search, click "next page" then choose a value from a facet. It will reset your page (correctly - now the results are different so you should be on page 1).

OK now hit the clear button (the black X - "clear all search settings and start again" tooltip). Go to page 2 of the default results. Put in ```Journal of applied sciences in environmental sanitation```. You will still be on page 2 of the ~230 results!

So a new query caused by the search box simply does not reset the page you are on. Only facets reset it.

We can easily make it reset the page but I'd be cautious of this because e.g. for me it refreshes the results when I move to another tab and then back. It'd be mighty annoying to be on page 5 or 10 of some results, go to another tab to look up something, come back and go to page 1!

**Comment by emanuil-tolev** [comment]
So I'd propose to leave it as is and just be aware it does that (unless it's often and annoying) as the alternatives are either potentially more annoying, or very fiddly (e.g. trying to refine when a query is issued from the search box so it doesn't trigger on switching tabs, but still triggers always when users want).

**Comment by dommitchell** [comment]
> How weird. Did it work afterwards? After a page refresh? Or after going in again to the admin search?

Nope. Tried all those and it didn't work.

Closing for now bit good to know why it happened.
