### ISSUE TITLE
Bug: lost the colour on the facet removal crosses

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#854]
I am certain these haven't always been white! They're near invisible now.

![crosses](https://cloud.githubusercontent.com/assets/5955396/9760633/18aeb2f6-56f7-11e5-9161-3d6027ac56ba.jpg)

**Comment by emanuil-tolev** [comment]
Wow, that's so weird.

I found the culprit, as part of the new social media icon on the page we had to upgrade the FontAwesome library so we could get the icon without, like, recreating it ourselves in the style of the others. Unfortunately that seems to have had this interesting effect. The cross is supposed to be a certain shade of blue.

**Comment by emanuil-tolev** [comment]
Although I'm struggling to understand what that has to do with this icon, since this is an icon from Bootstrap, a core style library we use. It doesn't come from FontAwesome.

**Comment by emanuil-tolev** [comment]
Hahah, I got it, the old version of FontAwesome would actually override Bootstrap icons. The Bootstrap ones don't take custom colours at all, but we were unwittingly using FontAwesome ones, which look the same, except you can colour them. How's that for a subtle bug :).

I've got a hotfix up for review. It's simple, but I want it reviewed since there are many ways to skin this particular cat and I want to make the change maintainable so we have an easy way of making future changes like this, rather than heap on style hacks. I think I've done it a good way.

**Comment by Steven-Eardley** [comment]
@emanuil-tolev Seriously good catch! Looks like I should've eyeballed more of the site when I upgraded the library. Thanks for taking care of this.

**Comment by Steven-Eardley** [comment]
Fix on live now, @dommitchell

**Comment by dommitchell** [comment]
Great! Closing.
