### ISSUE TITLE
Missing language code in XSD file

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#857]
/snip/
We are trying to generate XML file for DOAJ upload (for SIC journal for literature and literal translation) and there is a problem validating generated XML file with specified XSD schema (https://doaj.org/static/doaj/doajArticles.xsd) because language code in linked XSD file for Croatian is missing!

What should we do? shortcode for language shoud be "hrv" but this is not specified in language xsd schema. 
/snip/

**Comment by emanuil-tolev** [comment]
Yeah that code changed in 2009, we do have the old one - scr. We should probably define a process for updating our language stuff, including that schema (which was obviously generated / added a long time ago).

I'll update the schema (and leave the old code in - unless you'd like me to remove it?) but for now you can tell him "scr" will work for what he wants, if he doesn't mind of course (like if it's a lot of work, probably best to wait for us to roll out the update which is very simple).

**Comment by richard-jones** [comment]
Have we rolled out this update?

I have removed the bug tag, as this is a long-term maintenance issue, rather than a defect.  I've tagged it tnm to cover the updates required.

Do we need to talk about having a review process for standard external information (such as the XSD dependencies discussed here, plus the country/locale information that we also use)?

**Comment by emanuil-tolev** [comment]
> Do we need to talk about having a review process for standard external information (such as the XSD dependencies discussed here, plus the country/locale information that we also use)?

Yes

> Have we rolled out this update?

No. I'm not 100% sure I should be modifying the ISO XSD file. We should probably get a newer one and check if "hrv" is in there.

**Comment by dommitchell** [comment]
Related issue here: what we do about updates here? Do we need to constantly keep abreast of the changes to the NISO lists?

Richard to investigate.

**Comment by richard-jones** [comment]
I've done some digging, just to make sure we know where we're starting from, and this is the situation.

We currently maintain 2 standard lists of all things geo-related:

* an XSD of the ISO 639-2 language codes
* a JSON document of the ISO 3166 country codes and related info like currencies

Ultimately, we should have a process for keeping these both fresh.

From the perspective of the XSD, the canonical source of truth is the Library of Congress, and they have the following pages:

The actual page for the ISO standard
http://www.loc.gov/standards/iso639-2/

A change log
http://www.loc.gov/standards/iso639-2/php/code_changes.php

A machine readable txt file
http://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt

It appears, therefore, that the XSD was manufactured by the previous developers, most likely from this last link.

I propose that we maintain our own copy of that LoC txt file, and have a script which can re-generate the XSD at will.  This would allow us to keep up with any changes, and also to mix in our own customisations or enhancements (e.g. supporting defunct language codes, or overriding the standard names with our own ones).

Note that a quick review of the change log shows that this list does not change fast, and the last change was 4+ years ago.

As for the ISO 3166 dataset, do we know where we sourced this?  It is quite comprehensive, and a review of the ISO website shows you have to pay for their version of it, which is not ideal.

**Comment by emanuil-tolev** [comment]
> a JSON document of the ISO 3166 country codes and related info like currencies

> As for the ISO 3166 dataset, do we know where we sourced this? It is quite comprehensive, and a review of the ISO website shows you have to pay for their version of it, which is not ideal.

I got this from a github repository. I don't remember the URL - I actually recall thinking of this problem at the time, and thought I had recorded the URL somewhere in the DOAJ documentation or code, but can't find it at the moment.

It was a similar dataset to https://github.com/datasets/country-codes however. This repo features links to various sources of the data.

There is another option, a Python package: https://pypi.python.org/pypi/pycountry .It is currently up to date. The underlying ISO information is sourced from the Debian Linux project: https://anonscm.debian.org/cgit/pkg-isocodes/iso-codes.git/ (used as git submodule, then parsed by the Python package). The Debian ISO data appears to be very well maintained, last change 18h ago.

The Python package seems like one of the nicer options at the moment, though of course nobody guarantees maintenance will continue. But it is possible for us to take over maintaining it if nobody else does (since it's running so well already, we just have to update submodule pointing to the Debian source data occasionally). In terms of risk to the actual data being maintained, the Debian project is as solid open-source backing as you can ask for.

**Comment by emanuil-tolev** [comment]
Note: ideally we need pycountry to replace

- currency name
- currency 3-letter code
- country name
- country 2-char code
- language name 
- language 3-char code 
- language 2-char code

**Comment by dommitchell** [comment]
To reiterate what I said yesterday: I don't want this to become a massive task and for us to spend a disproportionate amount of time on this.

**Comment by richard-jones** [comment]
Did we make a decision, though, on what we should do about this?  Was it just to review the capabilities on pycountry?

**Comment by dommitchell** [comment]
I'd really like us to keep this simple and add the missing country code only. I realise that there is the possibility that another update maybe needed soon but this has been the only one since 2012. 

Can you just add the missing code?

**Comment by dommitchell** [comment]
@richard-jones this one should be picked up as part of the refactor project
