### ISSUE TITLE
Password reset email redirect to https

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#880]
Email that gets sent:

A password reset request for account '13960466' has been received and processed.
Please visit http://doaj.org/account/reset/417fef5eb29847fa990899e5d080a814 and enter your new password.

Clicking the link redirects to https:// which leads to a page not found.

Possible bug?

**Comment by emanuil-tolev** [comment]
Nah, I highly doubt it's the HTTPS part (though we should be generating it with HTTPS to begin with, that's true). We need to refactor this across the system actually, there's a couple of places where it says "generate a link with the same schema as the page the user is accessing now" but the problem is it believes the schema is HTTP due to the way it's set up in production, despite it being HTTPS. So we should just go for a hardcoded base url in the settings - everywhere. Should only take about half an hour to do.

That reset key (417fef5eb29847fa990899e5d080a814) doesn't exist in the index. It gets deleted after a new password is set, so you might need to regenerate it if that person has clicked on the link and set themselves a password - the link isn't going to work after that.

Can you clarify how you got to that link? I know copies of some emails are sent to DOAJ's inbox, so if you were looking to help a user and they've already set a password successfully, the link is not going to work (as per the above).

**Comment by emanuil-tolev** [comment]
> Can you clarify how you got to that link? I know copies of some emails are sent to DOAJ's inbox, so if you were looking to help a user and they've already set a password successfully, the link is not going to work (as per the above).

Also if you're looking to help a user and they still don't know their password (?!) ask them to use the forgotten password facility again - this should generate a new reset link and that'll work until they set a password using it.

**Comment by dommitchell** [comment]
> Can you clarify how you got to that link? I know copies of some emails are sent to DOAJ's inbox, so if you were looking to help a user and they've already set a password successfully, the link is not going to work (as per the above).
> 
> Also if you're looking to help a user and they still don't know their password (?!) ask them to use the forgotten password facility again - this should generate a new reset link and that'll work until they set a password using it.

Hmm, that's the problem. When they get the email with the link, they click it and get:

Not found

Sorry, the item you were looking for is not there.

DOAJ has migrated to a new, open source platform. Due to the upgrade, certain old links may not work.

**Comment by emanuil-tolev** [comment]
> Hmm, that's the problem. When they get the email with the link, they click it and get:

Wow, really. OK, that's a bad bug if so. I can set a temporary password and email it to you to forward to them (they can change it once they login directly from the my account page). Just so they can get in - obviously we'll need to check that reset problem.

**Comment by dommitchell** [comment]
> I can set a temporary password and email it to you to forward to them

That's OK. No need. That's my work around and I've done that already. 

I wonder if this is all related to preceding or trailing spaces in usernames?

**Comment by emanuil-tolev** [comment]
Well .. it could be, though I didn't see that in their account. The thing is the reset key didn't exist, and you said they weren't able to reset their password successfully (which is when it would get deleted).

I just tried it and it seems to work instantaneously, and the link worked for me. I was worried the forgotten pw feature wasn't working at all, but that doesn't seem to be the case ... Best I could do is try that account on the test site, the email will land in mailtrap.io .

Seems to work? http://testdoaj.cottagelabs.com/account/reset/34ebce50afc048a1ab2fa4043a023a29 (note this is the exact link from the email for that account on Test - plain http, still works).

**Comment by emanuil-tolev** [comment]
The reset link does last only 24h by the way, I think we decided on this way back when introducing it. I noticed it doesn't say that in the email. Could that be the issue here?

**Comment by dommitchell** [comment]
> I was worried the forgotten pw feature wasn't working at all,

Sorry, I should have said it is only for some password requests.

> The reset link does last only 24h by the way, I think we decided on this way back when introducing it. I noticed it doesn't say that in the email. Could that be the issue here?

Hmm, yep. I know that too. Leave this with me. If I get another example, I can leave it here.

Closing for now.
