### ISSUE TITLE
Number of countries with journals in DOAJ

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#881]
A manual count of the countries list in Admin reveals 125 countries in DOAJ:

https://doaj.org/admin/journals?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22admin.in_doaj%22%3A%22T%22}}]}}%2C%22query%22%3A{%22match_all%22%3A{}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

and yet the home page states 134. Where is the discrepancy coming from?

**Comment by emanuil-tolev** [comment]
Hmm, the facet in the admin UI is indeed 125 countries long when in_doaj is set to True.

That is also the case for the homepage stats (they look at in_doaj == True).

Going to need a bit more investigation than cursory look I think. They should really be the same from what I can see.

**Comment by emanuil-tolev** [comment]
Unless adding articles into the mix somehow adds more countries...? E.g. some articles' journal info out of sync..? That could possibly be it, the ```index``` part of some articles not being up to date since the homepage counts by ```index.country.exact``` and the admin UI's facet is on ```index.country.exact``` as well - but the admin UI only looks at journals, and the homepage stats look at all article and journal records.

We should probably think about syncing article and journal data anyway, so let's add to next meeting.

**Comment by richard-jones** [comment]
Just adding this to the Harvester milestone, as it might be that the journalinfo script will clear this confusion up.  If not, we can look again.

**Comment by richard-jones** [comment]
I've just reviewed this, and the numbers aren't the same still (though they are closer than before).  Probably there's a subtle difference in filtering that's causing the variance.

**Comment by dommitchell** [comment]
Closing and not so much of a problem just now
