### ISSUE TITLE
Unable to delete articles

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#924]
Any idea why this delete doesn't work?

http://bit.ly/1MYVDR3

It selects 122 articles and then says it is deleting 0

**Comment by richard-jones** [comment]
My guess is that the query string with the URL in it is breaking things.  Probably I forgot to add the appropriate special character escapes to the string when I send it to the delete routing, which means the search isn't working correctly.

**Comment by emanuil-tolev** [comment]
FYI the request (a POST) sends this

```
q:{"query":{"filtered":{"filter":{"bool":{"must":[{"term":{"_type":"article"}}]}},"query":{"query_string":{"query":"https://journal.atla.com/ojs/index.php/theolib/article/view/","default_operator":"AND"}}}},"from":0,"size":10}
```

Seems like your hunch is right. Is it possible to send the exact same query facetview2 itself would send? Or rather perhaps, what is preventing us from reusing that query building functionality (since this feature already works by using the same filters and freetext query that facetview uses)?

That might help avoid similar situations and more importantly, if we do a big refactor of how facetview handles queries and ES errors in the future (e.g. by upgrading/replacing facetview), this feature wouldn't require further changes or much thought to continue working.

**Comment by dommitchell** [comment]
@emanuil-tolev @richard-jones can you update me on this one? I'd like to get this publisher's articles deleted. Or can you delete them for me?

**Comment by dommitchell** [comment]
Another request to delete by URL: http://bit.ly/1lLW3OT

Can you fix this one soon?

**Comment by dommitchell** [comment]
And a third: http://bit.ly/1SBV0xo

**Comment by emanuil-tolev** [comment]
@richard-jones Looking at the initial search @dommitchell reported a problem about, this is the query that I extracted:

```
{"query":{"filtered":{"filter":{"bool":{"must":[{"term":{"_type":"article"}}]}},"query":{"query_string":{"query":"https\\:\\/\\/journal.atla.com\\/ojs\\/index.php\\/theolib\\/article\\/view\\/","default_operator":"AND"}}}},"from":0,"size":10}
```

Now when I ran the article delete script, it said it'd delete 122 articles just like the UI does, but in fact it did not delete anything. I had to add the ```--ignore-paging``` argument (which I added a while back) which strips out the from: and the size: from the query. The delete then works fine. I would have expected the UI delete to already do this (otherwise this feature would rarely work), but it's another avenue to explore if you find nothing wrong with its encoding of / or special chars.

**Comment by emanuil-tolev** [comment]
@dommitchell your three requests above should be handled now.

**Comment by dommitchell** [comment]
Thank you! Can I delete based on a search using URL myself now?

**Comment by emanuil-tolev** [comment]
I haven't changed the code @dommitchell , sorry - just ran your deletes so they don't hang around too long. We still need to find out exactly what in a URL causes it to behave like that.

**Comment by richard-jones** [comment]
Note to self: try querying with a URL and see if we can replicate this issue in general, then we will have something to work on for a fix.

**Comment by richard-jones** [comment]
Ok, tracked this down to incorrect serialisation of the query string in the javascript client.  hotfix PR in.

**Comment by richard-jones** [comment]
A fix for this has been deployed, but an error has arisen attempting to delete by DOI stub:

10.3389/conf.neuro

@emanuil-tolev or @Steven-Eardley - anything in the logs associated with this?

In the mean time, I will try to re-create in a local dev environment.

**Comment by richard-jones** [comment]
I have looked a bit further in to this but have made no headway.  It is our feeling that this is another timeout issue, and can only be resolved by the addition of a back-end aysnchronous processor for these kinds of tasks.

**Comment by richard-jones** [comment]
This issue is now obsolete with the new background processor code
