### ISSUE TITLE
Too many automated password reset emails getting in stuck in institutional firewalls

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#946]
Here's the text:

A password reset request for account '1759667X' has been received and processed.
Please visit http://doaj.org/account/reset/a4e374ce6c3948d49413bc5839375f60 and enter your new password.

If you are the user '1759667X' and you requested this change, please visit that link now and set the password to something of your preference.

If you are the user '1759667X' and you did not request this change, you can ignore this email.

Regards,
The DOAJ Team
/ends/

Any ideas how we can make this less spammy? High priority only because I would like some comments on this asap. Will remove label after that,

**Comment by emanuil-tolev** [comment]
Oh god. Have you guys worked with copywriters before, e.g. around some marketing / events / OA week / publisher comms...? If you have a competent one of those, that's the fastest way (as they'd have to keep up to date on what goes and what doesn't). Otherwise we can get up to speed on this as we do understand the mechanisms underlying the email ecosystem, but it might take longer. It's a bit of a dark art, and people put a lot of trial and error that they then distribute as blog posts and even books.

**Comment by emanuil-tolev** [comment]
![password_reset_email_stats](https://cloud.githubusercontent.com/assets/1190172/11336385/c96d9d12-91dc-11e5-8c72-968398320fdd.png)

Deliverability looks alright, but it might not be able to detect the emails being assassinated after they enter the institution's network. Note that because they're plain-text, Mandrill probably can't do click rate and open rate detection (e.g. it can't really be 0, I saw that somebody requested a reset TO feedback@doaj.org [so the team] and would have obviously opened it!).

Our (CL) Mandrill account rep is "Excellent" and avg deliverability of DOAJ emails over the last 3 months is 99.7% so that part's alright. Maybe we should add this topic (email analytics) to #942 .

Some useful links are:

http://kb.mailchimp.com/delivery/spam-filters/about-spam-filters  (there have been exactly 0 Spam complaints against any CL emails, incl. DOAJ, over the last 3 months)
https://sendgrid.com/blog/how-to-keep-your-password-reset-emails-out-of-the-spam-folder/  (can't see anything actionable from this as it either doesn't apply or we're doing it, but good info)

And finally overview of DOAJ emailing over last 90 days

![image](https://cloud.githubusercontent.com/assets/1190172/11336503/a2566208-91dd-11e5-9122-f69865a69a06.png)

So, what to do next - when I've time I'll review other recommendations in http://kb.mailchimp.com/delivery/spam-filters/about-spam-filters , but you can too - especially around subject lines and body text.

**Comment by emanuil-tolev** [comment]
> Our (CL) Mandrill account rep is "Excellent" and avg deliverability of DOAJ emails over the last 3 months is 99.7% so that part's alright. Maybe we should add this topic (email analytics) to #942 .

If you're interested in these stats we could give you a separate Mandrill DOAJ account and change over to it (it's free up to 12k emails / month which we've never reached). We set this one up in a bit of hurry back in 2013 when everything was in a bit of a hurry. That's something for #942 to discuss.

**Comment by dommitchell** [comment]
Closing
