### ISSUE TITLE
ISSN dropdown in metadata upload form shows both ISSNs

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#949]
https://doaj.org/publisher/metadata

If a journal has two ISSNs, both of them are shown in both dropdowns in this form. 

Only print issns should show in the Print dropdown and only e issns should show in the Electronic dropdown.

Is this agnostic just now because of ISSN discrepancies?

**Comment by richard-jones** [comment]
This works this way just because the auto-complete uses a generic "issn" field in the index to do the auto-complete.  To separate the print and electronic issns here we'd need to make some changes to the index structure, and to the auto-complete code.  All very doable, but probably more than a day's work.  Let me know if you want us to put it under tnm.

**Comment by dommitchell** [comment]
@richard-jones I imagine that there are advantages to having the ISSNs separated in the index right?
