### ISSUE TITLE
Reapplication submitted but not recorded in the system

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#950]
https://doaj.org/admin/suggestion/c2c2bba6cef74383bd570687cf00dde1
Application status: Reapplication Pending
and yet the publisher got a confirmation email.

From: <feedback@doaj.org>
Date: 2015-09-01 16:23 GMT-06:00
Subject: Directory of Open Access Journals - reapplication received

Dear Publisher,

Revista en Ciencias del Movimiento Humano y Salud

Thank you for completing your reapplication to DOAJ which has been safely received!

Please save this email as a record of when you submitted your reapplication. We are unable to reply to emails requesting a status update for reapplications that are less than 3 months old.

Yours faithfully,

The DOAJ Editorial Team

**Comment by dommitchell** [comment]
I'd like some feedback on this one and reassurance that this isn't widespread.

**Comment by emanuil-tolev** [comment]
> Date: 2015-09-01 16:23 GMT-06:00

I had the idea it was perhaps submitted when there was a problem (the one that caused us to expand to 3 servers for reliability), but .. there were no problems within days of that date, so it's not that. Going to have to reproduce this, which will probably be pretty hard.

FYI for @Steven-Eardley and @richard-jones the reapplication record was totally empty and just said "Reapplication Pending" as status. Now the publisher has reapplied (again I presume), so the record is now actually filled. Also discounts the possibility of the problem being this specific reapplication - we haven't changed application stuff around 1 Sept 2015, or since, and yet they obviously submitted it successfully the 2nd time.

**Comment by dommitchell** [comment]
I don't want to you to spend time on this that will detract you from other stuff. I just want to know: is there any way of telling whether this was a one-off or if the problem is more widespread?

**Comment by emanuil-tolev** [comment]
We're investigating the possibility first and foremost that it wasn't related to operations problems with running the site, since I managed to figure out that actually we did have that nasty problem around 2nd Sept! So me and Steve will take a look at the ol' backup for the server that was out of sync at the time. If we do find it there, then we know it was a one-off, and I can give you that reassurance :). We know the nasty problem won't happen again since we rearchitected the entire deployment with the goal of avoiding it (now have odd number of servers, requiring a quorum).

**Comment by emanuil-tolev** [comment]
> I don't want to you to spend time on this that will detract you from other stuff. I just want to know: is there any way of telling whether this was a one-off or if the problem is more widespread?

OK good news: this was definitely, definitely a one-off. The code and application architecture do not make this a systematic or even an intermittent problem.

Steve and I analysed the old dataset I had kept from the split-brain situation on 2 Sept 2015, and we found the missing reapplication. I did do some analysis but not something which could've caught the difference in a record (time constraints basically, have to keep other DOAJ things going too, and ultimately it looked like there weren't very many differences between the two "brains").

So we have:

- a full dump of the "wrong brain" from 2 Sept 2015 roughly 11:16
- a full dump of the "correct brain" (the one I chose to promote to be the "production brain" at the time) from 2 Sept 2015 17:52
- a desire to know what records were
    - in the "wrong brain" but not in the "correct brain"
    - in both "brains", but the records themselves differ (cue our friend with his reapplication that started this issue). Specifically we are interested in records whose last_updated is **newer** in the "wrong brain" than it is in the "correct brain". That means that some changes *may* have been lost (like this reapplication submission).

So that's it, we're hoping to produce an exhaustive list of what data was "lost" during the problem. And we can restore it, obviously, though exactly how depends on the amount of data - I don't think it's very much at all, so we might need to do some manual entry through the UI as that might be simplest.

We haven't spent too long on this yet, but it strikes me as important to do this - I actually thought after my very cursory initial analysis that there's a good chance that *nothing* was lost, but I was obviously wrong. We won't spend more than a few hours per week on this so we can move along all the other developments, and hopefully we'll be finished within a few weeks (and most importantly, well before reapplications close).

**Comment by dommitchell** [comment]
OK sounds good! I am reassured that this isn't a huge problem but will definitely be interested in your findings.

**Comment by richard-jones** [comment]
@emanuil-tolev @Steven-Eardley - I think we resolved that this was due to the split brain issue; did you need to do any further digging, or can we close this off?

**Comment by emanuil-tolev** [comment]
Another report from #882 

* * *

https://doaj.org/admin/suggestion/6de7441d4c604769bc8931ee0c0f90a9

Publisher submitted reapplication on 2nd Sept and got a confirmation email:

feedback@doaj.org 
To
XXXXX
Sep 2 at 12:47 PM
Dear Publisher,

Journal of Knowledge & Health

Thank you for completing your reapplication to DOAJ which has been safely received!

Please save this email as a record of when you submitted your reapplication. We are unable to reply to emails requesting a status update for reapplications that are less than 3 months old.

Yours faithfully,

The DOAJ Editorial Team
+++++++++++++++++++++

I have had 2 other reports of this (but neither were able to produce a confirmation email). Wonder if it was when we were having the cluster problems?

**Comment by dommitchell** [comment]
Closing
