### ISSUE TITLE
File system error when reading file

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#953]
Why would this error be invoked? I presume it is a system error and not an XML error? Account 01013122

![01013122](https://cloud.githubusercontent.com/assets/5955396/11416810/6b259e94-9411-11e5-8880-888a8f2a4985.jpg)

**Comment by emanuil-tolev** [comment]
This is raised when the file can be ingested but another problem occurs during processing, with file system problems being most likely. It's kind of a "last stand" so it isn't most descriptive (it is most likely a filesystem error in the sense of some OS-level problem of reading the XML file, but there is a chance of something else entirely). Unfortunately for some reason the specifics are not printed to the log. Does this persist if they reupload? There were no known problems at 23:12 yesterday.

The lack of specific info in the log is probably a symptom of the relative rush while introducing this particular functionality (since it almost never happens it didn't get noticed). I think it can be enhanced nicely without too much effort. Maybe create a new issue? All we need to do is print exception details when a non-IngestException is captured + think of a better user-facing error message if at all possible

**Comment by dommitchell** [comment]
This was temporary. CLosing
