### ISSUE TITLE
Add new order by... option to search

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#959]
Users of public journals search should be able to sort by APC, ascending and descending.

http://bit.ly/1PXInww

Please assess and quote for tnm

**Comment by richard-jones** [comment]
The challenge with this is that the APCs may be in different currencies, so it's difficult to objectively sort them.

We would need to convert the supplied currency to a standard, EUR/USD probably, /at the time it was paid/, and then we could offer normalised sorting over it.

Otherwise, we'd need to introduce an APC Currency facet first, and only then permit ordering by it when one is selected.  That would involve dynamically modifying the sort options during queries, which is possible but a bit fiddly.

Either way, a bit of a pain, so bouncing back to you @dommitchell for review (which I realise you may not do for a while, of course!).

**Comment by dommitchell** [comment]
Leaving for now
