### ISSUE TITLE
Reapplication accepted email should go to journal contact listed in reapplication record.

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#962]
Please change it so that when a reapplication is accepted, the confirmation email goes to the Journal Contact listed in the accepted reapplication record (Questions 9 and 10) and *not* the contact in the account or the original application.

**Comment by richard-jones** [comment]
I've been taking a look at this, and it is actually surprisingly fiddly. Or rather, getting the right user experience is.  Here's the current setup:

1. A "suggester" creates a new application, and they provide a "contact"
2. When the application is accepted, the "suggester" gets a user account created for them (if one didn't already exist) and an account activation email is sent
3. Then a Congratulations email is sent to the "suggester", referencing the account creation email, and giving them maintenance instructions

If we switch to sending email (3) to the "contact" rather than the "suggester", then the content of the email will be wrong.  There are a couple of options, that I can see:

1. Send an email to the "contact" just informing them.  Also send the maintenance instructions to the "suggester"
2. Create an account for the "contact" instead or as well, and send them the maintenance instructions instead.

I think probably (1) is the right way to go.  There are a couple of email templates that matter:

https://github.com/DOAJ/doaj/blob/develop/portality/templates/email/publisher_application_accepted.txt
https://github.com/DOAJ/doaj/blob/develop/portality/templates/email/publisher_reapplication_accepted.txt

@dommitchell - how do you want to approach it?

**Comment by dommitchell** [comment]
I agree. (1) is the way to go. I can edit the letter templates, no problem.

**Comment by richard-jones** [comment]
Ok, I've implemented this in my feature branch so that now on acceptance an email is sent to both the owner and the contact.

@dommitchell - Before I create a PR, do you think you could do me the text for each of the 4 email templates?  You can tweak them later, but I'd like to get them as close to correct as possible for the initial version, so that when we merge it with the live version it's immediately in the right state.

I need text for the following situations:

* Owner's email, when it's an application
* Owner's email, when it's a reapplication
* Contact's email, when it's an application
* Contact's email, when it's a reapplication

You can use the existing application email as a template:

https://github.com/DOAJ/doaj/blob/develop/portality/templates/email/publisher_application_accepted.txt

You'll have access to all the same variables (publisher_name, etc)

**Comment by dommitchell** [comment]
Leaving the texts here. Please let me know if they will work.

[Reapplication_owner_email.txt](https://github.com/DOAJ/doaj/files/426888/Reapplication_owner_email.txt)
[Reapplication_contact_email.txt](https://github.com/DOAJ/doaj/files/426889/Reapplication_contact_email.txt)
[Application_owner_email.txt](https://github.com/DOAJ/doaj/files/426891/Application_owner_email.txt)
[Application_contact_email.txt](https://github.com/DOAJ/doaj/files/426890/Application_contact_email.txt)

**Comment by emanuil-tolev** [comment]
This is now available to test by accepting an application at https://testdoaj.cottagelabs.com/ .
Check the emails sent at https://mailtrap.io/inboxes/26512/messages . Ping me for the mailtrap credentials, I've sent them around before. Developers will have them in their dev.cfg.

**Comment by dommitchell** [comment]
Tested and seen the emails in Mailtrap. Looking good!
