### ISSUE TITLE
Hotfixes to application form

### ISSUE THREAD

**Issue by greboun** [DOAJ/doaj#972]
ON HOLD UNTIL REAPPLICATION SHUTDOWN

We would like to see the following changes as listed in #137 prioritized:
as per our discussion on 1/5/2016 'remove' can be replaced by 'Hide from public view'
- Question 47: remove the 'No' option
- Question 51: remove OAKlist. OAKlist has been decommissioned.
-  Question 52: remove 'Other'.
-  Question 54: remove 'Other'.

One more question
could the admin /editor view of the application form be easily edited to highlight the questions that determine acceptance / rejection into DOAJ?    eg **text bold faced**  or **numbering in bold**

**Comment by richard-jones** [comment]
When doing this we need to bear in mind that some applications may have these values set, so we need a migration strategy, or a legacy data strategy.

Propose that we first check to see how many records will be affected, then make a decision what to do.  If those records are rejected, for example, we might just want to delete them.

@greboun with regard to your question - yes, this would be possible - we'd provide custom descriptions to the fields that were relevant.  If you want us to go ahead with that also under tnm, could you open a new issue, and list the questions you want to appear in bold.  This doesn't have to wait until the reapplication shutdown, so we can do that now, independently of the above.

Assigning this to you, for review - just unassign yourself when you have decided what to do about the above.

**Comment by emanuil-tolev** [comment]
> When doing this we need to bear in mind that some applications may have these values set, so we need a migration strategy, or a legacy data strategy.



> Question 47: remove the 'No' option

There are 4,154 applications which have selected "No". A number (72) are Accepted, so we do need to think what to do here. Maybe set some kind of text in the "Other" box after removing the "No" option.



> Question 51: remove OAKlist. OAKlist has been decommissioned.

OK, shall we just remove the OAKlist answer from all 132 who have answered this? In addition, if it was their only answer, we will set their Deposit Policy answer to "None" (tech note, do this by deleting .deposit_policy completely - I checked that this is what the form does on setting the None answer).

> Question 52: remove 'Other'.
> Question 54: remove 'Other'.

OK, again, shall we just drop the values that people have put in here over time? And set the answers to "No" (since it wasn't a Yes to begin with). These are required questions so we need to set something, otherwise the application objects become incomplete and you won't be able to save them (even if editing unrelated information, or trying to reject them).

**Comment by emanuil-tolev** [comment]
> Question 47: remove the 'No' option
> There are 4,154 applications which have selected "No". A number (72) are Accepted, so we do need to think what to do here. Maybe set some kind of text in the "Other" box after removing the "No" option.

https://doaj.org/admin/applications?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22%5C%22Not%20CC%5C%5C-like%5C%22%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22sort%22%3A%5B%7B%22_score%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22from%22%3A0%2C%22size%22%3A10%7D

**Comment by emanuil-tolev** [comment]
> There are 4,154 applications which have selected "No". A number (72) are Accepted, so we do need to think what to do here. Maybe set some kind of text in the "Other" box after removing the "No" option.
> 
> EDIT: See URL https://doaj.org/admin/applications?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22%5C%22Not%20CC%5C%5C-like%5C%22%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22sort%22%3A%5B%7B%22_score%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22from%22%3A0%2C%22size%22%3A10%7D . It shows 4,155 so not entirely accurate search, but will do for illustrative purposes here ;).

Migrate all Not-CC-Like to Publisher's own licence for *both applications and journals*. (This would show up in the Other box on the edit appl/journal page.)

**Comment by dommitchell** [comment]
Question 47
> There are 4,154 applications which have selected "No". A number (72) are Accepted, so we do need to think what to do here. Maybe set some kind of text in the "Other" box after removing the "No" option.
> EDIT: Have answer for this. Migrate all Not-CC-Like to Publisher's own licence for both applications and journals. (This would show up in the Other box on the edit appl/journal page.)

@greboun if a journal selected 'no' then wasn't that grounds for automatic rejection?

Question 51

> OK, shall we just remove the OAKlist answer from all 132 who have answered this?

Yes please but please migrate them to Sherpa/Romeo since all OAKlist records were incorporated into that.

Questions 52 and 54
> OK, again, shall we just drop the values that people have put in here over time? And set the answers to "No"

Yes, this would be perfect!

**Comment by emanuil-tolev** [comment]
Just to note, in last meeting (13 Sept), @dommitchell said I should stop working on this for now, since there was something of great (editorial) importance he needed to discuss with @greboun before this can proceed. I can't actually recall the details now though. Anyway, I'll finish this up as soon as we know we can do it.

**Comment by dommitchell** [comment]
@emanuil-tolev apologies for the delay. 

> There are 4,154 applications which have selected "No". A number (72) are Accepted, so we do need to think what to do here. Maybe set some kind of text in the "Other" box after removing the "No" option.

Yes, please go ahead and do this.

**Comment by greboun** [comment]
@emanuil-tolev suggest you use the text   " publisher specific licensing"

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by dommitchell** [comment]
@greboun we use 'Publisher's own license' on the site already. Might be tidier to use that? http://bit.ly/2cFMv3B

**Comment by greboun** [comment]
@dommitchell  yes Agreed!

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by emanuil-tolev** [comment]
Hotfix for this is in technical review - it's been a little more challenging than I assumed when estimating, mostly due to some technical debt having been built up over time.

The nature of tech debt is that we should be paying a bit more attention to refactoring things more during new projects, or we'll end up with tasks taking longer than expected (or just longer than they need be). As we've always done, when we're about to start new projects, we'll point out pain points that need re-developing as the DOAJ's requirements have changed over time.

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ @greboun Could you guys test this on the test server?

For example: http://testdoaj.cottagelabs.com/admin/journal/02d821123673428b83d65c6db2612a14

Data as it was before the migration:

![image](https://cloud.githubusercontent.com/assets/1190172/20277857/4c01a6b6-aa9a-11e6-87c1-b5b769d27dcd.png)

See

- question 45 (heading not visible, but it's the licence question, with a 'No' answer selected)
- question 48 (OAKlist selected)
- question 49 (Other selected and filled)
- question 51 (Other selected and filled)

Check what it says now:

http://testdoaj.cottagelabs.com/admin/journal/02d821123673428b83d65c6db2612a14#done

I think it looks good, like it worked well, but let me know if anything is off with the record.

Do any other checks you can think of overall on the test system related to this issue, and if you're happy, we can roll it out live.

**Comment by ClaraDOAJ** [comment]
Will do!

Clara Armengou
DOAJ - Community Manager

**Comment by dommitchell** [comment]
I just realised I hadn't said anything on this. I tested it and it looked
fine to me. Many thanks!

Clara Armengou
DOAJ - Community Manager

**Comment by emanuil-tolev** [comment]
Oh cool. Will look to roll it out in the next few days then.

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ This was rolled out today, so if you'd like to have a quick look at some journals and applications on live and review this? If it's satisfactory just close it.

**Comment by richard-jones** [comment]
@ClaraDOAJ - can I just prod you to review this and close it if you are happy no more needs to be done
