### ISSUE TITLE
Browser "back" and "forward" buttons don't change DOAJ search results

### ISSUE THREAD

**Issue by remocrevo** [DOAJ/doaj#986]
After choosing various search facets in DOAJ, using the browser's "back" and "forward" buttons do change the URL in the address bar, but don't produce any change in the search results list.  This is true on Windows 7 in Firefox, IE and Chrome.

**Comment by emanuil-tolev** [comment]
@remocrevo can you paste here:

1/ the results of http://whatsmyuseragent.com/
2/ the final search URL you end up with after selecting the various facets you need

I've tried reproducing your problem with http://browserstack.com and it does appear to work fine with both latest and slightly older (e.g. Firefox 42) versions of the browsers.

**Comment by remocrevo** [comment]
I am on Firefox ESR 38.6.0, but seeing the same behavior in IE 11 and Chrome 48.

User agents are:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36

Final search URL doesn't seem to matter, as I get the same behavior all through the search UI. Here's a simple way I can reproduce the problem:
1. Start at doaj.org/search
2. Search for "medicine". Search results change.
3. Click browser back button. No change in search results.

I can replace step 2 with clicking any series of facets or doing multiple searches in a row, and then any series of clicking back and forward buttons have no affect except for changing the URL in my address bar.  No Javascript errors.  Let me know if I can provide more helpful information.

**Comment by emanuil-tolev** [comment]
Oh, sorry, for some reason I'd got it into my head that you meant the fwd/back arrows in the search *results* on /search. You are right of course, it doesn't refresh the results.

The reason the address bar changes is to enable sharing the URL of the current (meaning latest) search, but I can see your point. Currently we just push URLs onto the browsers history for the window with Javascript - I actually expected this to magically make it comply with the best possible behaviour. Either modern browsers have a reason to not refresh the page or the method we're using needs to be improved.

@richard-jones @Steven-Eardley Our search URLs do not represent the current state when navigated to with fwd/back. We read in the state from the URL into facetview on page refresh (/load) so one quick and annoying thing would be to make it refresh when the URL changes (various JS libraries support watching the URL I believe). Less annoyingly, we would use such a watcher, but instead of refreshing we would re-parse the URL into facetview and just call doSearch(). So the page won't flash but the results will change.

I can look into it, probably tomorrow, mostly to see if the obvious complexity - the URL change watching - can be handled easily, and how easily, so that we can provide an estimate and this can be prioritised.

**Comment by richard-jones** [comment]
Looks like to support browser buttons we need to use popstate:

http://stackoverflow.com/questions/22751023/history-pushstate-fails-browser-back-and-forward-button

Pinging over to @greboun to determine if this should be looked into futher, and if so, whether under tnm.
